// POV-Ray scripts for LDraw models and scenes
// Copyright (C) 2019  Michael Horvath
// 
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
// 
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA


// row 1 - Black
#ifdef (ldTex0) #ifndef (MJHTex0) #declare MJHTex0 = ldTex0; #end #end
#ifdef (ldTex0) #ifndef (MJHTex0Slope) #declare MJHTex0Slope = ldTex0; #end #end
#ifdef (ldMat0) #ifndef (MJHMat0) #declare MJHMat0 = ldMat0; #end #end
#ifdef (ldMat0) #ifndef (MJHMat0Slope) #declare MJHMat0Slope = ldMat0; #end #end

// row 2 - Blue
#ifdef (ldTex1) #ifndef (MJHTex1) #declare MJHTex1 = ldTex1; #end #end
#ifdef (ldTex1) #ifndef (MJHTex1Slope) #declare MJHTex1Slope = ldTex1; #end #end
#ifdef (ldMat1) #ifndef (MJHMat1) #declare MJHMat1 = ldMat1; #end #end
#ifdef (ldMat1) #ifndef (MJHMat1Slope) #declare MJHMat1Slope = ldMat1; #end #end

// row 3 - Green
#ifdef (ldTex2) #ifndef (MJHTex2) #declare MJHTex2 = ldTex2; #end #end
#ifdef (ldTex2) #ifndef (MJHTex2Slope) #declare MJHTex2Slope = ldTex2; #end #end
#ifdef (ldMat2) #ifndef (MJHMat2) #declare MJHMat2 = ldMat2; #end #end
#ifdef (ldMat2) #ifndef (MJHMat2Slope) #declare MJHMat2Slope = ldMat2; #end #end

// row 4 - Dark_Turquoise
#ifdef (ldTex3) #ifndef (MJHTex3) #declare MJHTex3 = ldTex3; #end #end
#ifdef (ldTex3) #ifndef (MJHTex3Slope) #declare MJHTex3Slope = ldTex3; #end #end
#ifdef (ldMat3) #ifndef (MJHMat3) #declare MJHMat3 = ldMat3; #end #end
#ifdef (ldMat3) #ifndef (MJHMat3Slope) #declare MJHMat3Slope = ldMat3; #end #end

// row 5 - Red
#ifdef (ldTex4) #ifndef (MJHTex4) #declare MJHTex4 = ldTex4; #end #end
#ifdef (ldTex4) #ifndef (MJHTex4Slope) #declare MJHTex4Slope = ldTex4; #end #end
#ifdef (ldMat4) #ifndef (MJHMat4) #declare MJHMat4 = ldMat4; #end #end
#ifdef (ldMat4) #ifndef (MJHMat4Slope) #declare MJHMat4Slope = ldMat4; #end #end

// row 6 - Dark_Pink
#ifdef (ldTex5) #ifndef (MJHTex5) #declare MJHTex5 = ldTex5; #end #end
#ifdef (ldTex5) #ifndef (MJHTex5Slope) #declare MJHTex5Slope = ldTex5; #end #end
#ifdef (ldMat5) #ifndef (MJHMat5) #declare MJHMat5 = ldMat5; #end #end
#ifdef (ldMat5) #ifndef (MJHMat5Slope) #declare MJHMat5Slope = ldMat5; #end #end

// row 7 - Brown
#ifdef (ldTex6) #ifndef (MJHTex6) #declare MJHTex6 = ldTex6; #end #end
#ifdef (ldTex6) #ifndef (MJHTex6Slope) #declare MJHTex6Slope = ldTex6; #end #end
#ifdef (ldMat6) #ifndef (MJHMat6) #declare MJHMat6 = ldMat6; #end #end
#ifdef (ldMat6) #ifndef (MJHMat6Slope) #declare MJHMat6Slope = ldMat6; #end #end

// row 8 - Light_Grey
#ifdef (ldTex7) #ifndef (MJHTex7) #declare MJHTex7 = ldTex7; #end #end
#ifdef (ldTex7) #ifndef (MJHTex7Slope) #declare MJHTex7Slope = ldTex7; #end #end
#ifdef (ldMat7) #ifndef (MJHMat7) #declare MJHMat7 = ldMat7; #end #end
#ifdef (ldMat7) #ifndef (MJHMat7Slope) #declare MJHMat7Slope = ldMat7; #end #end

// row 9 - Dark_Grey
#ifdef (ldTex8) #ifndef (MJHTex8) #declare MJHTex8 = ldTex8; #end #end
#ifdef (ldTex8) #ifndef (MJHTex8Slope) #declare MJHTex8Slope = ldTex8; #end #end
#ifdef (ldMat8) #ifndef (MJHMat8) #declare MJHMat8 = ldMat8; #end #end
#ifdef (ldMat8) #ifndef (MJHMat8Slope) #declare MJHMat8Slope = ldMat8; #end #end

// row 10 - Light_Blue
#ifdef (ldTex9) #ifndef (MJHTex9) #declare MJHTex9 = ldTex9; #end #end
#ifdef (ldTex9) #ifndef (MJHTex9Slope) #declare MJHTex9Slope = ldTex9; #end #end
#ifdef (ldMat9) #ifndef (MJHMat9) #declare MJHMat9 = ldMat9; #end #end
#ifdef (ldMat9) #ifndef (MJHMat9Slope) #declare MJHMat9Slope = ldMat9; #end #end

// row 11 - Bright_Green
#ifdef (ldTex10) #ifndef (MJHTex10) #declare MJHTex10 = ldTex10; #end #end
#ifdef (ldTex10) #ifndef (MJHTex10Slope) #declare MJHTex10Slope = ldTex10; #end #end
#ifdef (ldMat10) #ifndef (MJHMat10) #declare MJHMat10 = ldMat10; #end #end
#ifdef (ldMat10) #ifndef (MJHMat10Slope) #declare MJHMat10Slope = ldMat10; #end #end

// row 12 - Light_Turquoise
#ifdef (ldTex11) #ifndef (MJHTex11) #declare MJHTex11 = ldTex11; #end #end
#ifdef (ldTex11) #ifndef (MJHTex11Slope) #declare MJHTex11Slope = ldTex11; #end #end
#ifdef (ldMat11) #ifndef (MJHMat11) #declare MJHMat11 = ldMat11; #end #end
#ifdef (ldMat11) #ifndef (MJHMat11Slope) #declare MJHMat11Slope = ldMat11; #end #end

// row 13 - Salmon
#ifdef (ldTex12) #ifndef (MJHTex12) #declare MJHTex12 = ldTex12; #end #end
#ifdef (ldTex12) #ifndef (MJHTex12Slope) #declare MJHTex12Slope = ldTex12; #end #end
#ifdef (ldMat12) #ifndef (MJHMat12) #declare MJHMat12 = ldMat12; #end #end
#ifdef (ldMat12) #ifndef (MJHMat12Slope) #declare MJHMat12Slope = ldMat12; #end #end

// row 14 - Pink
#ifdef (ldTex13) #ifndef (MJHTex13) #declare MJHTex13 = ldTex13; #end #end
#ifdef (ldTex13) #ifndef (MJHTex13Slope) #declare MJHTex13Slope = ldTex13; #end #end
#ifdef (ldMat13) #ifndef (MJHMat13) #declare MJHMat13 = ldMat13; #end #end
#ifdef (ldMat13) #ifndef (MJHMat13Slope) #declare MJHMat13Slope = ldMat13; #end #end

// row 15 - Yellow
#ifdef (ldTex14) #ifndef (MJHTex14) #declare MJHTex14 = ldTex14; #end #end
#ifdef (ldTex14) #ifndef (MJHTex14Slope) #declare MJHTex14Slope = ldTex14; #end #end
#ifdef (ldMat14) #ifndef (MJHMat14) #declare MJHMat14 = ldMat14; #end #end
#ifdef (ldMat14) #ifndef (MJHMat14Slope) #declare MJHMat14Slope = ldMat14; #end #end

// row 16 - White
#ifdef (ldTex15) #ifndef (MJHTex15) #declare MJHTex15 = ldTex15; #end #end
#ifdef (ldTex15) #ifndef (MJHTex15Slope) #declare MJHTex15Slope = ldTex15; #end #end
#ifdef (ldMat15) #ifndef (MJHMat15) #declare MJHMat15 = ldMat15; #end #end
#ifdef (ldMat15) #ifndef (MJHMat15Slope) #declare MJHMat15Slope = ldMat15; #end #end

// row 17 - Main_Colour
#ifdef (ldTex16) #ifndef (MJHTex16) #declare MJHTex16 = ldTex16; #end #end
#ifdef (ldTex16) #ifndef (MJHTex16Slope) #declare MJHTex16Slope = ldTex16; #end #end
#ifdef (ldMat16) #ifndef (MJHMat16) #declare MJHMat16 = ldMat16; #end #end
#ifdef (ldMat16) #ifndef (MJHMat16Slope) #declare MJHMat16Slope = ldMat16; #end #end

// row 18 - Light_Green
#ifdef (ldTex17) #ifndef (MJHTex17) #declare MJHTex17 = ldTex17; #end #end
#ifdef (ldTex17) #ifndef (MJHTex17Slope) #declare MJHTex17Slope = ldTex17; #end #end
#ifdef (ldMat17) #ifndef (MJHMat17) #declare MJHMat17 = ldMat17; #end #end
#ifdef (ldMat17) #ifndef (MJHMat17Slope) #declare MJHMat17Slope = ldMat17; #end #end

// row 19 - Light_Yellow
#ifdef (ldTex18) #ifndef (MJHTex18) #declare MJHTex18 = ldTex18; #end #end
#ifdef (ldTex18) #ifndef (MJHTex18Slope) #declare MJHTex18Slope = ldTex18; #end #end
#ifdef (ldMat18) #ifndef (MJHMat18) #declare MJHMat18 = ldMat18; #end #end
#ifdef (ldMat18) #ifndef (MJHMat18Slope) #declare MJHMat18Slope = ldMat18; #end #end

// row 20 - Tan
#ifdef (ldTex19) #ifndef (MJHTex19) #declare MJHTex19 = ldTex19; #end #end
#ifdef (ldTex19) #ifndef (MJHTex19Slope) #declare MJHTex19Slope = ldTex19; #end #end
#ifdef (ldMat19) #ifndef (MJHMat19) #declare MJHMat19 = ldMat19; #end #end
#ifdef (ldMat19) #ifndef (MJHMat19Slope) #declare MJHMat19Slope = ldMat19; #end #end

// row 21 - Light_Violet
#ifdef (ldTex20) #ifndef (MJHTex20) #declare MJHTex20 = ldTex20; #end #end
#ifdef (ldTex20) #ifndef (MJHTex20Slope) #declare MJHTex20Slope = ldTex20; #end #end
#ifdef (ldMat20) #ifndef (MJHMat20) #declare MJHMat20 = ldMat20; #end #end
#ifdef (ldMat20) #ifndef (MJHMat20Slope) #declare MJHMat20Slope = ldMat20; #end #end

// row 22 - Glow_In_Dark_Opaque
#ifdef (ldTex21) #ifndef (MJHTex21) #declare MJHTex21 = ldTex21; #end #end
#ifdef (ldTex21) #ifndef (MJHTex21Slope) #declare MJHTex21Slope = ldTex21; #end #end
#ifdef (ldMat21) #ifndef (MJHMat21) #declare MJHMat21 = ldMat21; #end #end
#ifdef (ldMat21) #ifndef (MJHMat21Slope) #declare MJHMat21Slope = ldMat21; #end #end

// row 23 - Purple
#ifdef (ldTex22) #ifndef (MJHTex22) #declare MJHTex22 = ldTex22; #end #end
#ifdef (ldTex22) #ifndef (MJHTex22Slope) #declare MJHTex22Slope = ldTex22; #end #end
#ifdef (ldMat22) #ifndef (MJHMat22) #declare MJHMat22 = ldMat22; #end #end
#ifdef (ldMat22) #ifndef (MJHMat22Slope) #declare MJHMat22Slope = ldMat22; #end #end

// row 24 - Dark_Blue_Violet
#ifdef (ldTex23) #ifndef (MJHTex23) #declare MJHTex23 = ldTex23; #end #end
#ifdef (ldTex23) #ifndef (MJHTex23Slope) #declare MJHTex23Slope = ldTex23; #end #end
#ifdef (ldMat23) #ifndef (MJHMat23) #declare MJHMat23 = ldMat23; #end #end
#ifdef (ldMat23) #ifndef (MJHMat23Slope) #declare MJHMat23Slope = ldMat23; #end #end

// row 25 - Edge_Colour
#ifdef (ldTex24) #ifndef (MJHTex24) #declare MJHTex24 = ldTex24; #end #end
#ifdef (ldTex24) #ifndef (MJHTex24Slope) #declare MJHTex24Slope = ldTex24; #end #end
#ifdef (ldMat24) #ifndef (MJHMat24) #declare MJHMat24 = ldMat24; #end #end
#ifdef (ldMat24) #ifndef (MJHMat24Slope) #declare MJHMat24Slope = ldMat24; #end #end

// row 26 - Orange
#ifdef (ldTex25) #ifndef (MJHTex25) #declare MJHTex25 = ldTex25; #end #end
#ifdef (ldTex25) #ifndef (MJHTex25Slope) #declare MJHTex25Slope = ldTex25; #end #end
#ifdef (ldMat25) #ifndef (MJHMat25) #declare MJHMat25 = ldMat25; #end #end
#ifdef (ldMat25) #ifndef (MJHMat25Slope) #declare MJHMat25Slope = ldMat25; #end #end

// row 27 - Magenta
#ifdef (ldTex26) #ifndef (MJHTex26) #declare MJHTex26 = ldTex26; #end #end
#ifdef (ldTex26) #ifndef (MJHTex26Slope) #declare MJHTex26Slope = ldTex26; #end #end
#ifdef (ldMat26) #ifndef (MJHMat26) #declare MJHMat26 = ldMat26; #end #end
#ifdef (ldMat26) #ifndef (MJHMat26Slope) #declare MJHMat26Slope = ldMat26; #end #end

// row 28 - Lime
#ifdef (ldTex27) #ifndef (MJHTex27) #declare MJHTex27 = ldTex27; #end #end
#ifdef (ldTex27) #ifndef (MJHTex27Slope) #declare MJHTex27Slope = ldTex27; #end #end
#ifdef (ldMat27) #ifndef (MJHMat27) #declare MJHMat27 = ldMat27; #end #end
#ifdef (ldMat27) #ifndef (MJHMat27Slope) #declare MJHMat27Slope = ldMat27; #end #end

// row 29 - Dark_Tan
#ifdef (ldTex28) #ifndef (MJHTex28) #declare MJHTex28 = ldTex28; #end #end
#ifdef (ldTex28) #ifndef (MJHTex28Slope) #declare MJHTex28Slope = ldTex28; #end #end
#ifdef (ldMat28) #ifndef (MJHMat28) #declare MJHMat28 = ldMat28; #end #end
#ifdef (ldMat28) #ifndef (MJHMat28Slope) #declare MJHMat28Slope = ldMat28; #end #end

// row 30 - Bright_Pink
#ifdef (ldTex29) #ifndef (MJHTex29) #declare MJHTex29 = ldTex29; #end #end
#ifdef (ldTex29) #ifndef (MJHTex29Slope) #declare MJHTex29Slope = ldTex29; #end #end
#ifdef (ldMat29) #ifndef (MJHMat29) #declare MJHMat29 = ldMat29; #end #end
#ifdef (ldMat29) #ifndef (MJHMat29Slope) #declare MJHMat29Slope = ldMat29; #end #end

// row 31 - Medium_Lavender
#ifdef (ldTex30) #ifndef (MJHTex30) #declare MJHTex30 = ldTex30; #end #end
#ifdef (ldTex30) #ifndef (MJHTex30Slope) #declare MJHTex30Slope = ldTex30; #end #end
#ifdef (ldMat30) #ifndef (MJHMat30) #declare MJHMat30 = ldMat30; #end #end
#ifdef (ldMat30) #ifndef (MJHMat30Slope) #declare MJHMat30Slope = ldMat30; #end #end

// row 32 - Lavender
#ifdef (ldTex31) #ifndef (MJHTex31) #declare MJHTex31 = ldTex31; #end #end
#ifdef (ldTex31) #ifndef (MJHTex31Slope) #declare MJHTex31Slope = ldTex31; #end #end
#ifdef (ldMat31) #ifndef (MJHMat31) #declare MJHMat31 = ldMat31; #end #end
#ifdef (ldMat31) #ifndef (MJHMat31Slope) #declare MJHMat31Slope = ldMat31; #end #end

// row 33 - Trans_Black_IR_Lens
#ifdef (ldTex32) #ifndef (MJHTex32) #declare MJHTex32 = ldTex32; #end #end
#ifdef (ldTex32) #ifndef (MJHTex32Slope) #declare MJHTex32Slope = ldTex32; #end #end
#ifdef (ldMat32) #ifndef (MJHMat32) #declare MJHMat32 = ldMat32; #end #end
#ifdef (ldMat32) #ifndef (MJHMat32Slope) #declare MJHMat32Slope = ldMat32; #end #end

// row 34 - Trans_Dark_Blue
#ifdef (ldTex33) #ifndef (MJHTex33) #declare MJHTex33 = ldTex33; #end #end
#ifdef (ldTex33) #ifndef (MJHTex33Slope) #declare MJHTex33Slope = ldTex33; #end #end
#ifdef (ldMat33) #ifndef (MJHMat33) #declare MJHMat33 = ldMat33; #end #end
#ifdef (ldMat33) #ifndef (MJHMat33Slope) #declare MJHMat33Slope = ldMat33; #end #end

// row 35 - Trans_Green
#ifdef (ldTex34) #ifndef (MJHTex34) #declare MJHTex34 = ldTex34; #end #end
#ifdef (ldTex34) #ifndef (MJHTex34Slope) #declare MJHTex34Slope = ldTex34; #end #end
#ifdef (ldMat34) #ifndef (MJHMat34) #declare MJHMat34 = ldMat34; #end #end
#ifdef (ldMat34) #ifndef (MJHMat34Slope) #declare MJHMat34Slope = ldMat34; #end #end

// row 36 - Trans_Bright_Green
#ifdef (ldTex35) #ifndef (MJHTex35) #declare MJHTex35 = ldTex35; #end #end
#ifdef (ldTex35) #ifndef (MJHTex35Slope) #declare MJHTex35Slope = ldTex35; #end #end
#ifdef (ldMat35) #ifndef (MJHMat35) #declare MJHMat35 = ldMat35; #end #end
#ifdef (ldMat35) #ifndef (MJHMat35Slope) #declare MJHMat35Slope = ldMat35; #end #end

// row 37 - Trans_Red
#ifdef (ldTex36) #ifndef (MJHTex36) #declare MJHTex36 = ldTex36; #end #end
#ifdef (ldTex36) #ifndef (MJHTex36Slope) #declare MJHTex36Slope = ldTex36; #end #end
#ifdef (ldMat36) #ifndef (MJHMat36) #declare MJHMat36 = ldMat36; #end #end
#ifdef (ldMat36) #ifndef (MJHMat36Slope) #declare MJHMat36Slope = ldMat36; #end #end

// row 38 - Trans_Dark_Pink
#ifdef (ldTex37) #ifndef (MJHTex37) #declare MJHTex37 = ldTex37; #end #end
#ifdef (ldTex37) #ifndef (MJHTex37Slope) #declare MJHTex37Slope = ldTex37; #end #end
#ifdef (ldMat37) #ifndef (MJHMat37) #declare MJHMat37 = ldMat37; #end #end
#ifdef (ldMat37) #ifndef (MJHMat37Slope) #declare MJHMat37Slope = ldMat37; #end #end

// row 39 - Trans_Neon_Orange
#ifdef (ldTex38) #ifndef (MJHTex38) #declare MJHTex38 = ldTex38; #end #end
#ifdef (ldTex38) #ifndef (MJHTex38Slope) #declare MJHTex38Slope = ldTex38; #end #end
#ifdef (ldMat38) #ifndef (MJHMat38) #declare MJHMat38 = ldMat38; #end #end
#ifdef (ldMat38) #ifndef (MJHMat38Slope) #declare MJHMat38Slope = ldMat38; #end #end

// row 40 - Trans_Very_Light_Blue
#ifdef (ldTex39) #ifndef (MJHTex39) #declare MJHTex39 = ldTex39; #end #end
#ifdef (ldTex39) #ifndef (MJHTex39Slope) #declare MJHTex39Slope = ldTex39; #end #end
#ifdef (ldMat39) #ifndef (MJHMat39) #declare MJHMat39 = ldMat39; #end #end
#ifdef (ldMat39) #ifndef (MJHMat39Slope) #declare MJHMat39Slope = ldMat39; #end #end

// row 41 - Trans_Black
#ifdef (ldTex40) #ifndef (MJHTex40) #declare MJHTex40 = ldTex40; #end #end
#ifdef (ldTex40) #ifndef (MJHTex40Slope) #declare MJHTex40Slope = ldTex40; #end #end
#ifdef (ldMat40) #ifndef (MJHMat40) #declare MJHMat40 = ldMat40; #end #end
#ifdef (ldMat40) #ifndef (MJHMat40Slope) #declare MJHMat40Slope = ldMat40; #end #end

// row 42 - Trans_Medium_Blue
#ifdef (ldTex41) #ifndef (MJHTex41) #declare MJHTex41 = ldTex41; #end #end
#ifdef (ldTex41) #ifndef (MJHTex41Slope) #declare MJHTex41Slope = ldTex41; #end #end
#ifdef (ldMat41) #ifndef (MJHMat41) #declare MJHMat41 = ldMat41; #end #end
#ifdef (ldMat41) #ifndef (MJHMat41Slope) #declare MJHMat41Slope = ldMat41; #end #end

// row 43 - Trans_Neon_Green
#ifdef (ldTex42) #ifndef (MJHTex42) #declare MJHTex42 = ldTex42; #end #end
#ifdef (ldTex42) #ifndef (MJHTex42Slope) #declare MJHTex42Slope = ldTex42; #end #end
#ifdef (ldMat42) #ifndef (MJHMat42) #declare MJHMat42 = ldMat42; #end #end
#ifdef (ldMat42) #ifndef (MJHMat42Slope) #declare MJHMat42Slope = ldMat42; #end #end

// row 44 - Trans_Light_Blue
#ifdef (ldTex43) #ifndef (MJHTex43) #declare MJHTex43 = ldTex43; #end #end
#ifdef (ldTex43) #ifndef (MJHTex43Slope) #declare MJHTex43Slope = ldTex43; #end #end
#ifdef (ldMat43) #ifndef (MJHMat43) #declare MJHMat43 = ldMat43; #end #end
#ifdef (ldMat43) #ifndef (MJHMat43Slope) #declare MJHMat43Slope = ldMat43; #end #end

// row 45 - Trans_Bright_Reddish_Lilac
#ifdef (ldTex44) #ifndef (MJHTex44) #declare MJHTex44 = ldTex44; #end #end
#ifdef (ldTex44) #ifndef (MJHTex44Slope) #declare MJHTex44Slope = ldTex44; #end #end
#ifdef (ldMat44) #ifndef (MJHMat44) #declare MJHMat44 = ldMat44; #end #end
#ifdef (ldMat44) #ifndef (MJHMat44Slope) #declare MJHMat44Slope = ldMat44; #end #end

// row 46 - Trans_Pink
#ifdef (ldTex45) #ifndef (MJHTex45) #declare MJHTex45 = ldTex45; #end #end
#ifdef (ldTex45) #ifndef (MJHTex45Slope) #declare MJHTex45Slope = ldTex45; #end #end
#ifdef (ldMat45) #ifndef (MJHMat45) #declare MJHMat45 = ldMat45; #end #end
#ifdef (ldMat45) #ifndef (MJHMat45Slope) #declare MJHMat45Slope = ldMat45; #end #end

// row 47 - Trans_Yellow
#ifdef (ldTex46) #ifndef (MJHTex46) #declare MJHTex46 = ldTex46; #end #end
#ifdef (ldTex46) #ifndef (MJHTex46Slope) #declare MJHTex46Slope = ldTex46; #end #end
#ifdef (ldMat46) #ifndef (MJHMat46) #declare MJHMat46 = ldMat46; #end #end
#ifdef (ldMat46) #ifndef (MJHMat46Slope) #declare MJHMat46Slope = ldMat46; #end #end

// row 48 - Trans_Clear
#ifdef (ldTex47) #ifndef (MJHTex47) #declare MJHTex47 = ldTex47; #end #end
#ifdef (ldTex47) #ifndef (MJHTex47Slope) #declare MJHTex47Slope = ldTex47; #end #end
#ifdef (ldMat47) #ifndef (MJHMat47) #declare MJHMat47 = ldMat47; #end #end
#ifdef (ldMat47) #ifndef (MJHMat47Slope) #declare MJHMat47Slope = ldMat47; #end #end

// row 49 - Trans_Purple
#ifdef (ldTex52) #ifndef (MJHTex52) #declare MJHTex52 = ldTex52; #end #end
#ifdef (ldTex52) #ifndef (MJHTex52Slope) #declare MJHTex52Slope = ldTex52; #end #end
#ifdef (ldMat52) #ifndef (MJHMat52) #declare MJHMat52 = ldMat52; #end #end
#ifdef (ldMat52) #ifndef (MJHMat52Slope) #declare MJHMat52Slope = ldMat52; #end #end

// row 50 - Trans_Neon_Yellow
#ifdef (ldTex54) #ifndef (MJHTex54) #declare MJHTex54 = ldTex54; #end #end
#ifdef (ldTex54) #ifndef (MJHTex54Slope) #declare MJHTex54Slope = ldTex54; #end #end
#ifdef (ldMat54) #ifndef (MJHMat54) #declare MJHMat54 = ldMat54; #end #end
#ifdef (ldMat54) #ifndef (MJHMat54Slope) #declare MJHMat54Slope = ldMat54; #end #end

// row 51 - Trans_Orange
#ifdef (ldTex57) #ifndef (MJHTex57) #declare MJHTex57 = ldTex57; #end #end
#ifdef (ldTex57) #ifndef (MJHTex57Slope) #declare MJHTex57Slope = ldTex57; #end #end
#ifdef (ldMat57) #ifndef (MJHMat57) #declare MJHMat57 = ldMat57; #end #end
#ifdef (ldMat57) #ifndef (MJHMat57Slope) #declare MJHMat57Slope = ldMat57; #end #end

// row 52 - Chrome_Antique_Brass
#ifdef (ldTex60) #ifndef (MJHTex60) #declare MJHTex60 = ldTex60; #end #end
#ifdef (ldTex60) #ifndef (MJHTex60Slope) #declare MJHTex60Slope = ldTex60; #end #end
#ifdef (ldMat60) #ifndef (MJHMat60) #declare MJHMat60 = ldMat60; #end #end
#ifdef (ldMat60) #ifndef (MJHMat60Slope) #declare MJHMat60Slope = ldMat60; #end #end

// row 53 - Chrome_Blue
#ifdef (ldTex61) #ifndef (MJHTex61) #declare MJHTex61 = ldTex61; #end #end
#ifdef (ldTex61) #ifndef (MJHTex61Slope) #declare MJHTex61Slope = ldTex61; #end #end
#ifdef (ldMat61) #ifndef (MJHMat61) #declare MJHMat61 = ldMat61; #end #end
#ifdef (ldMat61) #ifndef (MJHMat61Slope) #declare MJHMat61Slope = ldMat61; #end #end

// row 54 - Chrome_Green
#ifdef (ldTex62) #ifndef (MJHTex62) #declare MJHTex62 = ldTex62; #end #end
#ifdef (ldTex62) #ifndef (MJHTex62Slope) #declare MJHTex62Slope = ldTex62; #end #end
#ifdef (ldMat62) #ifndef (MJHMat62) #declare MJHMat62 = ldMat62; #end #end
#ifdef (ldMat62) #ifndef (MJHMat62Slope) #declare MJHMat62Slope = ldMat62; #end #end

// row 55 - Chrome_Pink
#ifdef (ldTex63) #ifndef (MJHTex63) #declare MJHTex63 = ldTex63; #end #end
#ifdef (ldTex63) #ifndef (MJHTex63Slope) #declare MJHTex63Slope = ldTex63; #end #end
#ifdef (ldMat63) #ifndef (MJHMat63) #declare MJHMat63 = ldMat63; #end #end
#ifdef (ldMat63) #ifndef (MJHMat63Slope) #declare MJHMat63Slope = ldMat63; #end #end

// row 56 - Chrome_Black
#ifdef (ldTex64) #ifndef (MJHTex64) #declare MJHTex64 = ldTex64; #end #end
#ifdef (ldTex64) #ifndef (MJHTex64Slope) #declare MJHTex64Slope = ldTex64; #end #end
#ifdef (ldMat64) #ifndef (MJHMat64) #declare MJHMat64 = ldMat64; #end #end
#ifdef (ldMat64) #ifndef (MJHMat64Slope) #declare MJHMat64Slope = ldMat64; #end #end

// row 57 - Rubber_Yellow
#ifdef (ldTex65) #ifndef (MJHTex65) #declare MJHTex65 = ldTex65; #end #end
#ifdef (ldTex65) #ifndef (MJHTex65Slope) #declare MJHTex65Slope = ldTex65; #end #end
#ifdef (ldMat65) #ifndef (MJHMat65) #declare MJHMat65 = ldMat65; #end #end
#ifdef (ldMat65) #ifndef (MJHMat65Slope) #declare MJHMat65Slope = ldMat65; #end #end

// row 58 - Rubber_Trans_Yellow
#ifdef (ldTex66) #ifndef (MJHTex66) #declare MJHTex66 = ldTex66; #end #end
#ifdef (ldTex66) #ifndef (MJHTex66Slope) #declare MJHTex66Slope = ldTex66; #end #end
#ifdef (ldMat66) #ifndef (MJHMat66) #declare MJHMat66 = ldMat66; #end #end
#ifdef (ldMat66) #ifndef (MJHMat66Slope) #declare MJHMat66Slope = ldMat66; #end #end

// row 59 - Rubber_Trans_Clear
#ifdef (ldTex67) #ifndef (MJHTex67) #declare MJHTex67 = ldTex67; #end #end
#ifdef (ldTex67) #ifndef (MJHTex67Slope) #declare MJHTex67Slope = ldTex67; #end #end
#ifdef (ldMat67) #ifndef (MJHMat67) #declare MJHMat67 = ldMat67; #end #end
#ifdef (ldMat67) #ifndef (MJHMat67Slope) #declare MJHMat67Slope = ldMat67; #end #end

// row 60 - Very_Light_Orange
#ifdef (ldTex68) #ifndef (MJHTex68) #declare MJHTex68 = ldTex68; #end #end
#ifdef (ldTex68) #ifndef (MJHTex68Slope) #declare MJHTex68Slope = ldTex68; #end #end
#ifdef (ldMat68) #ifndef (MJHMat68) #declare MJHMat68 = ldMat68; #end #end
#ifdef (ldMat68) #ifndef (MJHMat68Slope) #declare MJHMat68Slope = ldMat68; #end #end

// row 61 - Bright_Reddish_Lilac
#ifdef (ldTex69) #ifndef (MJHTex69) #declare MJHTex69 = ldTex69; #end #end
#ifdef (ldTex69) #ifndef (MJHTex69Slope) #declare MJHTex69Slope = ldTex69; #end #end
#ifdef (ldMat69) #ifndef (MJHMat69) #declare MJHMat69 = ldMat69; #end #end
#ifdef (ldMat69) #ifndef (MJHMat69Slope) #declare MJHMat69Slope = ldMat69; #end #end

// row 62 - Reddish_Brown
#ifdef (ldTex70) #ifndef (MJHTex70) #declare MJHTex70 = ldTex70; #end #end
#ifdef (ldTex70) #ifndef (MJHTex70Slope) #declare MJHTex70Slope = ldTex70; #end #end
#ifdef (ldMat70) #ifndef (MJHMat70) #declare MJHMat70 = ldMat70; #end #end
#ifdef (ldMat70) #ifndef (MJHMat70Slope) #declare MJHMat70Slope = ldMat70; #end #end

// row 63 - Light_Bluish_Grey
#ifdef (ldTex71) #ifndef (MJHTex71) #declare MJHTex71 = ldTex71; #end #end
#ifdef (ldTex71) #ifndef (MJHTex71Slope) #declare MJHTex71Slope = ldTex71; #end #end
#ifdef (ldMat71) #ifndef (MJHMat71) #declare MJHMat71 = ldMat71; #end #end
#ifdef (ldMat71) #ifndef (MJHMat71Slope) #declare MJHMat71Slope = ldMat71; #end #end

// row 64 - Dark_Bluish_Grey
#ifdef (ldTex72) #ifndef (MJHTex72) #declare MJHTex72 = ldTex72; #end #end
#ifdef (ldTex72) #ifndef (MJHTex72Slope) #declare MJHTex72Slope = ldTex72; #end #end
#ifdef (ldMat72) #ifndef (MJHMat72) #declare MJHMat72 = ldMat72; #end #end
#ifdef (ldMat72) #ifndef (MJHMat72Slope) #declare MJHMat72Slope = ldMat72; #end #end

// row 65 - Medium_Blue
#ifdef (ldTex73) #ifndef (MJHTex73) #declare MJHTex73 = ldTex73; #end #end
#ifdef (ldTex73) #ifndef (MJHTex73Slope) #declare MJHTex73Slope = ldTex73; #end #end
#ifdef (ldMat73) #ifndef (MJHMat73) #declare MJHMat73 = ldMat73; #end #end
#ifdef (ldMat73) #ifndef (MJHMat73Slope) #declare MJHMat73Slope = ldMat73; #end #end

// row 66 - Medium_Green
#ifdef (ldTex74) #ifndef (MJHTex74) #declare MJHTex74 = ldTex74; #end #end
#ifdef (ldTex74) #ifndef (MJHTex74Slope) #declare MJHTex74Slope = ldTex74; #end #end
#ifdef (ldMat74) #ifndef (MJHMat74) #declare MJHMat74 = ldMat74; #end #end
#ifdef (ldMat74) #ifndef (MJHMat74Slope) #declare MJHMat74Slope = ldMat74; #end #end

// row 67 - Speckle_Black_Copper
#ifdef (ldTex75) #ifndef (MJHTex75) #declare MJHTex75 = ldTex75; #end #end
#ifdef (ldTex75) #ifndef (MJHTex75Slope) #declare MJHTex75Slope = ldTex75; #end #end
#ifdef (ldMat75) #ifndef (MJHMat75) #declare MJHMat75 = ldMat75; #end #end
#ifdef (ldMat75) #ifndef (MJHMat75Slope) #declare MJHMat75Slope = ldMat75; #end #end

// row 68 - Speckle_Dark_Bluish_Grey_Silver
#ifdef (ldTex76) #ifndef (MJHTex76) #declare MJHTex76 = ldTex76; #end #end
#ifdef (ldTex76) #ifndef (MJHTex76Slope) #declare MJHTex76Slope = ldTex76; #end #end
#ifdef (ldMat76) #ifndef (MJHMat76) #declare MJHMat76 = ldMat76; #end #end
#ifdef (ldMat76) #ifndef (MJHMat76Slope) #declare MJHMat76Slope = ldMat76; #end #end

// row 69 - Light_Pink
#ifdef (ldTex77) #ifndef (MJHTex77) #declare MJHTex77 = ldTex77; #end #end
#ifdef (ldTex77) #ifndef (MJHTex77Slope) #declare MJHTex77Slope = ldTex77; #end #end
#ifdef (ldMat77) #ifndef (MJHMat77) #declare MJHMat77 = ldMat77; #end #end
#ifdef (ldMat77) #ifndef (MJHMat77Slope) #declare MJHMat77Slope = ldMat77; #end #end

// row 70 - Light_Flesh
#ifdef (ldTex78) #ifndef (MJHTex78) #declare MJHTex78 = ldTex78; #end #end
#ifdef (ldTex78) #ifndef (MJHTex78Slope) #declare MJHTex78Slope = ldTex78; #end #end
#ifdef (ldMat78) #ifndef (MJHMat78) #declare MJHMat78 = ldMat78; #end #end
#ifdef (ldMat78) #ifndef (MJHMat78Slope) #declare MJHMat78Slope = ldMat78; #end #end

// row 71 - Milky_White
#ifdef (ldTex79) #ifndef (MJHTex79) #declare MJHTex79 = ldTex79; #end #end
#ifdef (ldTex79) #ifndef (MJHTex79Slope) #declare MJHTex79Slope = ldTex79; #end #end
#ifdef (ldMat79) #ifndef (MJHMat79) #declare MJHMat79 = ldMat79; #end #end
#ifdef (ldMat79) #ifndef (MJHMat79Slope) #declare MJHMat79Slope = ldMat79; #end #end

// row 72 - Metallic_Silver
#ifdef (ldTex80) #ifndef (MJHTex80) #declare MJHTex80 = ldTex80; #end #end
#ifdef (ldTex80) #ifndef (MJHTex80Slope) #declare MJHTex80Slope = ldTex80; #end #end
#ifdef (ldMat80) #ifndef (MJHMat80) #declare MJHMat80 = ldMat80; #end #end
#ifdef (ldMat80) #ifndef (MJHMat80Slope) #declare MJHMat80Slope = ldMat80; #end #end

// row 73 - Metallic_Green
#ifdef (ldTex81) #ifndef (MJHTex81) #declare MJHTex81 = ldTex81; #end #end
#ifdef (ldTex81) #ifndef (MJHTex81Slope) #declare MJHTex81Slope = ldTex81; #end #end
#ifdef (ldMat81) #ifndef (MJHMat81) #declare MJHMat81 = ldMat81; #end #end
#ifdef (ldMat81) #ifndef (MJHMat81Slope) #declare MJHMat81Slope = ldMat81; #end #end

// row 74 - Metallic_Gold
#ifdef (ldTex82) #ifndef (MJHTex82) #declare MJHTex82 = ldTex82; #end #end
#ifdef (ldTex82) #ifndef (MJHTex82Slope) #declare MJHTex82Slope = ldTex82; #end #end
#ifdef (ldMat82) #ifndef (MJHMat82) #declare MJHMat82 = ldMat82; #end #end
#ifdef (ldMat82) #ifndef (MJHMat82Slope) #declare MJHMat82Slope = ldMat82; #end #end

// row 75 - Metallic_Black
#ifdef (ldTex83) #ifndef (MJHTex83) #declare MJHTex83 = ldTex83; #end #end
#ifdef (ldTex83) #ifndef (MJHTex83Slope) #declare MJHTex83Slope = ldTex83; #end #end
#ifdef (ldMat83) #ifndef (MJHMat83) #declare MJHMat83 = ldMat83; #end #end
#ifdef (ldMat83) #ifndef (MJHMat83Slope) #declare MJHMat83Slope = ldMat83; #end #end

// row 76 - Medium_Dark_Flesh
#ifdef (ldTex84) #ifndef (MJHTex84) #declare MJHTex84 = ldTex84; #end #end
#ifdef (ldTex84) #ifndef (MJHTex84Slope) #declare MJHTex84Slope = ldTex84; #end #end
#ifdef (ldMat84) #ifndef (MJHMat84) #declare MJHMat84 = ldMat84; #end #end
#ifdef (ldMat84) #ifndef (MJHMat84Slope) #declare MJHMat84Slope = ldMat84; #end #end

// row 77 - Medium_Lilac
#ifdef (ldTex85) #ifndef (MJHTex85) #declare MJHTex85 = ldTex85; #end #end
#ifdef (ldTex85) #ifndef (MJHTex85Slope) #declare MJHTex85Slope = ldTex85; #end #end
#ifdef (ldMat85) #ifndef (MJHMat85) #declare MJHMat85 = ldMat85; #end #end
#ifdef (ldMat85) #ifndef (MJHMat85Slope) #declare MJHMat85Slope = ldMat85; #end #end

// row 78 - Dark_Flesh
#ifdef (ldTex86) #ifndef (MJHTex86) #declare MJHTex86 = ldTex86; #end #end
#ifdef (ldTex86) #ifndef (MJHTex86Slope) #declare MJHTex86Slope = ldTex86; #end #end
#ifdef (ldMat86) #ifndef (MJHMat86) #declare MJHMat86 = ldMat86; #end #end
#ifdef (ldMat86) #ifndef (MJHMat86Slope) #declare MJHMat86Slope = ldMat86; #end #end

// row 79 - Metallic_Dark_Grey
#ifdef (ldTex87) #ifndef (MJHTex87) #declare MJHTex87 = ldTex87; #end #end
#ifdef (ldTex87) #ifndef (MJHTex87Slope) #declare MJHTex87Slope = ldTex87; #end #end
#ifdef (ldMat87) #ifndef (MJHMat87) #declare MJHMat87 = ldMat87; #end #end
#ifdef (ldMat87) #ifndef (MJHMat87Slope) #declare MJHMat87Slope = ldMat87; #end #end

// row 80 - Blue_Violet
#ifdef (ldTex89) #ifndef (MJHTex89) #declare MJHTex89 = ldTex89; #end #end
#ifdef (ldTex89) #ifndef (MJHTex89Slope) #declare MJHTex89Slope = ldTex89; #end #end
#ifdef (ldMat89) #ifndef (MJHMat89) #declare MJHMat89 = ldMat89; #end #end
#ifdef (ldMat89) #ifndef (MJHMat89Slope) #declare MJHMat89Slope = ldMat89; #end #end

// row 81 - Flesh
#ifdef (ldTex92) #ifndef (MJHTex92) #declare MJHTex92 = ldTex92; #end #end
#ifdef (ldTex92) #ifndef (MJHTex92Slope) #declare MJHTex92Slope = ldTex92; #end #end
#ifdef (ldMat92) #ifndef (MJHMat92) #declare MJHMat92 = ldMat92; #end #end
#ifdef (ldMat92) #ifndef (MJHMat92Slope) #declare MJHMat92Slope = ldMat92; #end #end

// row 82 - Light_Salmon
#ifdef (ldTex100) #ifndef (MJHTex100) #declare MJHTex100 = ldTex100; #end #end
#ifdef (ldTex100) #ifndef (MJHTex100Slope) #declare MJHTex100Slope = ldTex100; #end #end
#ifdef (ldMat100) #ifndef (MJHMat100) #declare MJHMat100 = ldMat100; #end #end
#ifdef (ldMat100) #ifndef (MJHMat100Slope) #declare MJHMat100Slope = ldMat100; #end #end

// row 83 - Violet
#ifdef (ldTex110) #ifndef (MJHTex110) #declare MJHTex110 = ldTex110; #end #end
#ifdef (ldTex110) #ifndef (MJHTex110Slope) #declare MJHTex110Slope = ldTex110; #end #end
#ifdef (ldMat110) #ifndef (MJHMat110) #declare MJHMat110 = ldMat110; #end #end
#ifdef (ldMat110) #ifndef (MJHMat110Slope) #declare MJHMat110Slope = ldMat110; #end #end

// row 84 - Medium_Violet
#ifdef (ldTex112) #ifndef (MJHTex112) #declare MJHTex112 = ldTex112; #end #end
#ifdef (ldTex112) #ifndef (MJHTex112Slope) #declare MJHTex112Slope = ldTex112; #end #end
#ifdef (ldMat112) #ifndef (MJHMat112) #declare MJHMat112 = ldMat112; #end #end
#ifdef (ldMat112) #ifndef (MJHMat112Slope) #declare MJHMat112Slope = ldMat112; #end #end

// row 85 - Glitter_Trans_Dark_Pink
#ifdef (ldTex114) #ifndef (MJHTex114) #declare MJHTex114 = ldTex114; #end #end
#ifdef (ldTex114) #ifndef (MJHTex114Slope) #declare MJHTex114Slope = ldTex114; #end #end
#ifdef (ldMat114) #ifndef (MJHMat114) #declare MJHMat114 = ldMat114; #end #end
#ifdef (ldMat114) #ifndef (MJHMat114Slope) #declare MJHMat114Slope = ldMat114; #end #end

// row 86 - Medium_Lime
#ifdef (ldTex115) #ifndef (MJHTex115) #declare MJHTex115 = ldTex115; #end #end
#ifdef (ldTex115) #ifndef (MJHTex115Slope) #declare MJHTex115Slope = ldTex115; #end #end
#ifdef (ldMat115) #ifndef (MJHMat115) #declare MJHMat115 = ldMat115; #end #end
#ifdef (ldMat115) #ifndef (MJHMat115Slope) #declare MJHMat115Slope = ldMat115; #end #end

// row 87 - Glitter_Trans_Clear
#ifdef (ldTex117) #ifndef (MJHTex117) #declare MJHTex117 = ldTex117; #end #end
#ifdef (ldTex117) #ifndef (MJHTex117Slope) #declare MJHTex117Slope = ldTex117; #end #end
#ifdef (ldMat117) #ifndef (MJHMat117) #declare MJHMat117 = ldMat117; #end #end
#ifdef (ldMat117) #ifndef (MJHMat117Slope) #declare MJHMat117Slope = ldMat117; #end #end

// row 88 - Aqua
#ifdef (ldTex118) #ifndef (MJHTex118) #declare MJHTex118 = ldTex118; #end #end
#ifdef (ldTex118) #ifndef (MJHTex118Slope) #declare MJHTex118Slope = ldTex118; #end #end
#ifdef (ldMat118) #ifndef (MJHMat118) #declare MJHMat118 = ldMat118; #end #end
#ifdef (ldMat118) #ifndef (MJHMat118Slope) #declare MJHMat118Slope = ldMat118; #end #end

// row 89 - Light_Lime
#ifdef (ldTex120) #ifndef (MJHTex120) #declare MJHTex120 = ldTex120; #end #end
#ifdef (ldTex120) #ifndef (MJHTex120Slope) #declare MJHTex120Slope = ldTex120; #end #end
#ifdef (ldMat120) #ifndef (MJHMat120) #declare MJHMat120 = ldMat120; #end #end
#ifdef (ldMat120) #ifndef (MJHMat120Slope) #declare MJHMat120Slope = ldMat120; #end #end

// row 90 - Light_Orange
#ifdef (ldTex125) #ifndef (MJHTex125) #declare MJHTex125 = ldTex125; #end #end
#ifdef (ldTex125) #ifndef (MJHTex125Slope) #declare MJHTex125Slope = ldTex125; #end #end
#ifdef (ldMat125) #ifndef (MJHMat125) #declare MJHMat125 = ldMat125; #end #end
#ifdef (ldMat125) #ifndef (MJHMat125Slope) #declare MJHMat125Slope = ldMat125; #end #end

// row 91 - Dark_Nougat
#ifdef (ldTex128) #ifndef (MJHTex128) #declare MJHTex128 = ldTex128; #end #end
#ifdef (ldTex128) #ifndef (MJHTex128Slope) #declare MJHTex128Slope = ldTex128; #end #end
#ifdef (ldMat128) #ifndef (MJHMat128) #declare MJHMat128 = ldMat128; #end #end
#ifdef (ldMat128) #ifndef (MJHMat128Slope) #declare MJHMat128Slope = ldMat128; #end #end

// row 92 - Glitter_Trans_Purple
#ifdef (ldTex129) #ifndef (MJHTex129) #declare MJHTex129 = ldTex129; #end #end
#ifdef (ldTex129) #ifndef (MJHTex129Slope) #declare MJHTex129Slope = ldTex129; #end #end
#ifdef (ldMat129) #ifndef (MJHMat129) #declare MJHMat129 = ldMat129; #end #end
#ifdef (ldMat129) #ifndef (MJHMat129Slope) #declare MJHMat129Slope = ldMat129; #end #end

// row 93 - Speckle_Black_Silver
#ifdef (ldTex132) #ifndef (MJHTex132) #declare MJHTex132 = ldTex132; #end #end
#ifdef (ldTex132) #ifndef (MJHTex132Slope) #declare MJHTex132Slope = ldTex132; #end #end
#ifdef (ldMat132) #ifndef (MJHMat132) #declare MJHMat132 = ldMat132; #end #end
#ifdef (ldMat132) #ifndef (MJHMat132Slope) #declare MJHMat132Slope = ldMat132; #end #end

// row 94 - Speckle_Black_Gold
#ifdef (ldTex133) #ifndef (MJHTex133) #declare MJHTex133 = ldTex133; #end #end
#ifdef (ldTex133) #ifndef (MJHTex133Slope) #declare MJHTex133Slope = ldTex133; #end #end
#ifdef (ldMat133) #ifndef (MJHMat133) #declare MJHMat133 = ldMat133; #end #end
#ifdef (ldMat133) #ifndef (MJHMat133Slope) #declare MJHMat133Slope = ldMat133; #end #end

// row 95 - Copper
#ifdef (ldTex134) #ifndef (MJHTex134) #declare MJHTex134 = ldTex134; #end #end
#ifdef (ldTex134) #ifndef (MJHTex134Slope) #declare MJHTex134Slope = ldTex134; #end #end
#ifdef (ldMat134) #ifndef (MJHMat134) #declare MJHMat134 = ldMat134; #end #end
#ifdef (ldMat134) #ifndef (MJHMat134Slope) #declare MJHMat134Slope = ldMat134; #end #end

// row 96 - Pearl_Light_Grey
#ifdef (ldTex135) #ifndef (MJHTex135) #declare MJHTex135 = ldTex135; #end #end
#ifdef (ldTex135) #ifndef (MJHTex135Slope) #declare MJHTex135Slope = ldTex135; #end #end
#ifdef (ldMat135) #ifndef (MJHMat135) #declare MJHMat135 = ldMat135; #end #end
#ifdef (ldMat135) #ifndef (MJHMat135Slope) #declare MJHMat135Slope = ldMat135; #end #end

// row 97 - Metal_Blue
#ifdef (ldTex137) #ifndef (MJHTex137) #declare MJHTex137 = ldTex137; #end #end
#ifdef (ldTex137) #ifndef (MJHTex137Slope) #declare MJHTex137Slope = ldTex137; #end #end
#ifdef (ldMat137) #ifndef (MJHMat137) #declare MJHMat137 = ldMat137; #end #end
#ifdef (ldMat137) #ifndef (MJHMat137Slope) #declare MJHMat137Slope = ldMat137; #end #end

// row 98 - Pearl_Light_Gold
#ifdef (ldTex142) #ifndef (MJHTex142) #declare MJHTex142 = ldTex142; #end #end
#ifdef (ldTex142) #ifndef (MJHTex142Slope) #declare MJHTex142Slope = ldTex142; #end #end
#ifdef (ldMat142) #ifndef (MJHMat142) #declare MJHMat142 = ldMat142; #end #end
#ifdef (ldMat142) #ifndef (MJHMat142Slope) #declare MJHMat142Slope = ldMat142; #end #end

// row 99 - Pearl_Dark_Grey
#ifdef (ldTex148) #ifndef (MJHTex148) #declare MJHTex148 = ldTex148; #end #end
#ifdef (ldTex148) #ifndef (MJHTex148Slope) #declare MJHTex148Slope = ldTex148; #end #end
#ifdef (ldMat148) #ifndef (MJHMat148) #declare MJHMat148 = ldMat148; #end #end
#ifdef (ldMat148) #ifndef (MJHMat148Slope) #declare MJHMat148Slope = ldMat148; #end #end

// row 100 - Pearl_Very_Light_Grey
#ifdef (ldTex150) #ifndef (MJHTex150) #declare MJHTex150 = ldTex150; #end #end
#ifdef (ldTex150) #ifndef (MJHTex150Slope) #declare MJHTex150Slope = ldTex150; #end #end
#ifdef (ldMat150) #ifndef (MJHMat150) #declare MJHMat150 = ldMat150; #end #end
#ifdef (ldMat150) #ifndef (MJHMat150Slope) #declare MJHMat150Slope = ldMat150; #end #end

// row 101 - Very_Light_Bluish_Grey
#ifdef (ldTex151) #ifndef (MJHTex151) #declare MJHTex151 = ldTex151; #end #end
#ifdef (ldTex151) #ifndef (MJHTex151Slope) #declare MJHTex151Slope = ldTex151; #end #end
#ifdef (ldMat151) #ifndef (MJHMat151) #declare MJHMat151 = ldMat151; #end #end
#ifdef (ldMat151) #ifndef (MJHMat151Slope) #declare MJHMat151Slope = ldMat151; #end #end

// row 102 - Flat_Dark_Gold
#ifdef (ldTex178) #ifndef (MJHTex178) #declare MJHTex178 = ldTex178; #end #end
#ifdef (ldTex178) #ifndef (MJHTex178Slope) #declare MJHTex178Slope = ldTex178; #end #end
#ifdef (ldMat178) #ifndef (MJHMat178) #declare MJHMat178 = ldMat178; #end #end
#ifdef (ldMat178) #ifndef (MJHMat178Slope) #declare MJHMat178Slope = ldMat178; #end #end

// row 103 - Flat_Silver
#ifdef (ldTex179) #ifndef (MJHTex179) #declare MJHTex179 = ldTex179; #end #end
#ifdef (ldTex179) #ifndef (MJHTex179Slope) #declare MJHTex179Slope = ldTex179; #end #end
#ifdef (ldMat179) #ifndef (MJHMat179) #declare MJHMat179 = ldMat179; #end #end
#ifdef (ldMat179) #ifndef (MJHMat179Slope) #declare MJHMat179Slope = ldMat179; #end #end

// row 104 - Pearl_White
#ifdef (ldTex183) #ifndef (MJHTex183) #declare MJHTex183 = ldTex183; #end #end
#ifdef (ldTex183) #ifndef (MJHTex183Slope) #declare MJHTex183Slope = ldTex183; #end #end
#ifdef (ldMat183) #ifndef (MJHMat183) #declare MJHMat183 = ldMat183; #end #end
#ifdef (ldMat183) #ifndef (MJHMat183Slope) #declare MJHMat183Slope = ldMat183; #end #end

// row 105 - Metallic_Bright_Red
#ifdef (ldTex184) #ifndef (MJHTex184) #declare MJHTex184 = ldTex184; #end #end
#ifdef (ldTex184) #ifndef (MJHTex184Slope) #declare MJHTex184Slope = ldTex184; #end #end
#ifdef (ldMat184) #ifndef (MJHMat184) #declare MJHMat184 = ldMat184; #end #end
#ifdef (ldMat184) #ifndef (MJHMat184Slope) #declare MJHMat184Slope = ldMat184; #end #end

// row 106 - Metallic_Dark_Green
#ifdef (ldTex186) #ifndef (MJHTex186) #declare MJHTex186 = ldTex186; #end #end
#ifdef (ldTex186) #ifndef (MJHTex186Slope) #declare MJHTex186Slope = ldTex186; #end #end
#ifdef (ldMat186) #ifndef (MJHMat186) #declare MJHMat186 = ldMat186; #end #end
#ifdef (ldMat186) #ifndef (MJHMat186Slope) #declare MJHMat186Slope = ldMat186; #end #end

// row 107 - Reddish_Gold
#ifdef (ldTex189) #ifndef (MJHTex189) #declare MJHTex189 = ldTex189; #end #end
#ifdef (ldTex189) #ifndef (MJHTex189Slope) #declare MJHTex189Slope = ldTex189; #end #end
#ifdef (ldMat189) #ifndef (MJHMat189) #declare MJHMat189 = ldMat189; #end #end
#ifdef (ldMat189) #ifndef (MJHMat189Slope) #declare MJHMat189Slope = ldMat189; #end #end

// row 108 - Bright_Light_Orange
#ifdef (ldTex191) #ifndef (MJHTex191) #declare MJHTex191 = ldTex191; #end #end
#ifdef (ldTex191) #ifndef (MJHTex191Slope) #declare MJHTex191Slope = ldTex191; #end #end
#ifdef (ldMat191) #ifndef (MJHMat191) #declare MJHMat191 = ldMat191; #end #end
#ifdef (ldMat191) #ifndef (MJHMat191Slope) #declare MJHMat191Slope = ldMat191; #end #end

// row 109 - Bright_Light_Blue
#ifdef (ldTex212) #ifndef (MJHTex212) #declare MJHTex212 = ldTex212; #end #end
#ifdef (ldTex212) #ifndef (MJHTex212Slope) #declare MJHTex212Slope = ldTex212; #end #end
#ifdef (ldMat212) #ifndef (MJHMat212) #declare MJHMat212 = ldMat212; #end #end
#ifdef (ldMat212) #ifndef (MJHMat212Slope) #declare MJHMat212Slope = ldMat212; #end #end

// row 110 - Rust
#ifdef (ldTex216) #ifndef (MJHTex216) #declare MJHTex216 = ldTex216; #end #end
#ifdef (ldTex216) #ifndef (MJHTex216Slope) #declare MJHTex216Slope = ldTex216; #end #end
#ifdef (ldMat216) #ifndef (MJHMat216) #declare MJHMat216 = ldMat216; #end #end
#ifdef (ldMat216) #ifndef (MJHMat216Slope) #declare MJHMat216Slope = ldMat216; #end #end

// row 111 - Reddish_Lilac
#ifdef (ldTex218) #ifndef (MJHTex218) #declare MJHTex218 = ldTex218; #end #end
#ifdef (ldTex218) #ifndef (MJHTex218Slope) #declare MJHTex218Slope = ldTex218; #end #end
#ifdef (ldMat218) #ifndef (MJHMat218) #declare MJHMat218 = ldMat218; #end #end
#ifdef (ldMat218) #ifndef (MJHMat218Slope) #declare MJHMat218Slope = ldMat218; #end #end

// row 112 - Lilac
#ifdef (ldTex219) #ifndef (MJHTex219) #declare MJHTex219 = ldTex219; #end #end
#ifdef (ldTex219) #ifndef (MJHTex219Slope) #declare MJHTex219Slope = ldTex219; #end #end
#ifdef (ldMat219) #ifndef (MJHMat219) #declare MJHMat219 = ldMat219; #end #end
#ifdef (ldMat219) #ifndef (MJHMat219Slope) #declare MJHMat219Slope = ldMat219; #end #end

// row 113 - Bright_Light_Yellow
#ifdef (ldTex226) #ifndef (MJHTex226) #declare MJHTex226 = ldTex226; #end #end
#ifdef (ldTex226) #ifndef (MJHTex226Slope) #declare MJHTex226Slope = ldTex226; #end #end
#ifdef (ldMat226) #ifndef (MJHMat226) #declare MJHMat226 = ldMat226; #end #end
#ifdef (ldMat226) #ifndef (MJHMat226Slope) #declare MJHMat226Slope = ldMat226; #end #end

// row 114 - Trans_Bright_Light_Orange
#ifdef (ldTex231) #ifndef (MJHTex231) #declare MJHTex231 = ldTex231; #end #end
#ifdef (ldTex231) #ifndef (MJHTex231Slope) #declare MJHTex231Slope = ldTex231; #end #end
#ifdef (ldMat231) #ifndef (MJHMat231) #declare MJHMat231 = ldMat231; #end #end
#ifdef (ldMat231) #ifndef (MJHMat231Slope) #declare MJHMat231Slope = ldMat231; #end #end

// row 115 - Sky_Blue
#ifdef (ldTex232) #ifndef (MJHTex232) #declare MJHTex232 = ldTex232; #end #end
#ifdef (ldTex232) #ifndef (MJHTex232Slope) #declare MJHTex232Slope = ldTex232; #end #end
#ifdef (ldMat232) #ifndef (MJHMat232) #declare MJHMat232 = ldMat232; #end #end
#ifdef (ldMat232) #ifndef (MJHMat232Slope) #declare MJHMat232Slope = ldMat232; #end #end

// row 116 - Trans_Fire_Yellow
#ifdef (ldTex234) #ifndef (MJHTex234) #declare MJHTex234 = ldTex234; #end #end
#ifdef (ldTex234) #ifndef (MJHTex234Slope) #declare MJHTex234Slope = ldTex234; #end #end
#ifdef (ldMat234) #ifndef (MJHMat234) #declare MJHMat234 = ldMat234; #end #end
#ifdef (ldMat234) #ifndef (MJHMat234Slope) #declare MJHMat234Slope = ldMat234; #end #end

// row 117 - Rubber_Black
#ifdef (ldTex256) #ifndef (MJHTex256) #declare MJHTex256 = ldTex256; #end #end
#ifdef (ldTex256) #ifndef (MJHTex256Slope) #declare MJHTex256Slope = ldTex256; #end #end
#ifdef (ldMat256) #ifndef (MJHMat256) #declare MJHMat256 = ldMat256; #end #end
#ifdef (ldMat256) #ifndef (MJHMat256Slope) #declare MJHMat256Slope = ldMat256; #end #end

// row 118 - Dark_Blue
#ifdef (ldTex272) #ifndef (MJHTex272) #declare MJHTex272 = ldTex272; #end #end
#ifdef (ldTex272) #ifndef (MJHTex272Slope) #declare MJHTex272Slope = ldTex272; #end #end
#ifdef (ldMat272) #ifndef (MJHMat272) #declare MJHMat272 = ldMat272; #end #end
#ifdef (ldMat272) #ifndef (MJHMat272Slope) #declare MJHMat272Slope = ldMat272; #end #end

// row 119 - Rubber_Blue
#ifdef (ldTex273) #ifndef (MJHTex273) #declare MJHTex273 = ldTex273; #end #end
#ifdef (ldTex273) #ifndef (MJHTex273Slope) #declare MJHTex273Slope = ldTex273; #end #end
#ifdef (ldMat273) #ifndef (MJHMat273) #declare MJHMat273 = ldMat273; #end #end
#ifdef (ldMat273) #ifndef (MJHMat273Slope) #declare MJHMat273Slope = ldMat273; #end #end

// row 120 - Trans_Reddish_Lilac
#ifdef (ldTex284) #ifndef (MJHTex284) #declare MJHTex284 = ldTex284; #end #end
#ifdef (ldTex284) #ifndef (MJHTex284Slope) #declare MJHTex284Slope = ldTex284; #end #end
#ifdef (ldMat284) #ifndef (MJHMat284) #declare MJHMat284 = ldMat284; #end #end
#ifdef (ldMat284) #ifndef (MJHMat284Slope) #declare MJHMat284Slope = ldMat284; #end #end

// row 121 - Trans_Light_Green
#ifdef (ldTex285) #ifndef (MJHTex285) #declare MJHTex285 = ldTex285; #end #end
#ifdef (ldTex285) #ifndef (MJHTex285Slope) #declare MJHTex285Slope = ldTex285; #end #end
#ifdef (ldMat285) #ifndef (MJHMat285) #declare MJHMat285 = ldMat285; #end #end
#ifdef (ldMat285) #ifndef (MJHMat285Slope) #declare MJHMat285Slope = ldMat285; #end #end

// row 122 - Dark_Green
#ifdef (ldTex288) #ifndef (MJHTex288) #declare MJHTex288 = ldTex288; #end #end
#ifdef (ldTex288) #ifndef (MJHTex288Slope) #declare MJHTex288Slope = ldTex288; #end #end
#ifdef (ldMat288) #ifndef (MJHMat288) #declare MJHMat288 = ldMat288; #end #end
#ifdef (ldMat288) #ifndef (MJHMat288Slope) #declare MJHMat288Slope = ldMat288; #end #end

// row 123 - Trans_Light_Blue_Violet
#ifdef (ldTex293) #ifndef (MJHTex293) #declare MJHTex293 = ldTex293; #end #end
#ifdef (ldTex293) #ifndef (MJHTex293Slope) #declare MJHTex293Slope = ldTex293; #end #end
#ifdef (ldMat293) #ifndef (MJHMat293) #declare MJHMat293 = ldMat293; #end #end
#ifdef (ldMat293) #ifndef (MJHMat293Slope) #declare MJHMat293Slope = ldMat293; #end #end

// row 124 - Glow_In_Dark_Trans
#ifdef (ldTex294) #ifndef (MJHTex294) #declare MJHTex294 = ldTex294; #end #end
#ifdef (ldTex294) #ifndef (MJHTex294Slope) #declare MJHTex294Slope = ldTex294; #end #end
#ifdef (ldMat294) #ifndef (MJHMat294) #declare MJHMat294 = ldMat294; #end #end
#ifdef (ldMat294) #ifndef (MJHMat294Slope) #declare MJHMat294Slope = ldMat294; #end #end

// row 125 - Flamingo_Pink
#ifdef (ldTex295) #ifndef (MJHTex295) #declare MJHTex295 = ldTex295; #end #end
#ifdef (ldTex295) #ifndef (MJHTex295Slope) #declare MJHTex295Slope = ldTex295; #end #end
#ifdef (ldMat295) #ifndef (MJHMat295) #declare MJHMat295 = ldMat295; #end #end
#ifdef (ldMat295) #ifndef (MJHMat295Slope) #declare MJHMat295Slope = ldMat295; #end #end

// row 126 - Pearl_Gold
#ifdef (ldTex297) #ifndef (MJHTex297) #declare MJHTex297 = ldTex297; #end #end
#ifdef (ldTex297) #ifndef (MJHTex297Slope) #declare MJHTex297Slope = ldTex297; #end #end
#ifdef (ldMat297) #ifndef (MJHMat297) #declare MJHMat297 = ldMat297; #end #end
#ifdef (ldMat297) #ifndef (MJHMat297Slope) #declare MJHMat297Slope = ldMat297; #end #end

// row 127 - Metallic_Copper
#ifdef (ldTex300) #ifndef (MJHTex300) #declare MJHTex300 = ldTex300; #end #end
#ifdef (ldTex300) #ifndef (MJHTex300Slope) #declare MJHTex300Slope = ldTex300; #end #end
#ifdef (ldMat300) #ifndef (MJHMat300) #declare MJHMat300 = ldMat300; #end #end
#ifdef (ldMat300) #ifndef (MJHMat300Slope) #declare MJHMat300Slope = ldMat300; #end #end

// row 128 - Glitter_Trans_Light_Blue
#ifdef (ldTex302) #ifndef (MJHTex302) #declare MJHTex302 = ldTex302; #end #end
#ifdef (ldTex302) #ifndef (MJHTex302Slope) #declare MJHTex302Slope = ldTex302; #end #end
#ifdef (ldMat302) #ifndef (MJHMat302) #declare MJHMat302 = ldMat302; #end #end
#ifdef (ldMat302) #ifndef (MJHMat302Slope) #declare MJHMat302Slope = ldMat302; #end #end

// row 129 - Dark_Brown
#ifdef (ldTex308) #ifndef (MJHTex308) #declare MJHTex308 = ldTex308; #end #end
#ifdef (ldTex308) #ifndef (MJHTex308Slope) #declare MJHTex308Slope = ldTex308; #end #end
#ifdef (ldMat308) #ifndef (MJHMat308) #declare MJHMat308 = ldMat308; #end #end
#ifdef (ldMat308) #ifndef (MJHMat308Slope) #declare MJHMat308Slope = ldMat308; #end #end

// row 130 - Maersk_Blue
#ifdef (ldTex313) #ifndef (MJHTex313) #declare MJHTex313 = ldTex313; #end #end
#ifdef (ldTex313) #ifndef (MJHTex313Slope) #declare MJHTex313Slope = ldTex313; #end #end
#ifdef (ldMat313) #ifndef (MJHMat313) #declare MJHMat313 = ldMat313; #end #end
#ifdef (ldMat313) #ifndef (MJHMat313Slope) #declare MJHMat313Slope = ldMat313; #end #end

// row 131 - Dark_Red
#ifdef (ldTex320) #ifndef (MJHTex320) #declare MJHTex320 = ldTex320; #end #end
#ifdef (ldTex320) #ifndef (MJHTex320Slope) #declare MJHTex320Slope = ldTex320; #end #end
#ifdef (ldMat320) #ifndef (MJHMat320) #declare MJHMat320 = ldMat320; #end #end
#ifdef (ldMat320) #ifndef (MJHMat320Slope) #declare MJHMat320Slope = ldMat320; #end #end

// row 132 - Dark_Azure
#ifdef (ldTex321) #ifndef (MJHTex321) #declare MJHTex321 = ldTex321; #end #end
#ifdef (ldTex321) #ifndef (MJHTex321Slope) #declare MJHTex321Slope = ldTex321; #end #end
#ifdef (ldMat321) #ifndef (MJHMat321) #declare MJHMat321 = ldMat321; #end #end
#ifdef (ldMat321) #ifndef (MJHMat321Slope) #declare MJHMat321Slope = ldMat321; #end #end

// row 133 - Medium_Azure
#ifdef (ldTex322) #ifndef (MJHTex322) #declare MJHTex322 = ldTex322; #end #end
#ifdef (ldTex322) #ifndef (MJHTex322Slope) #declare MJHTex322Slope = ldTex322; #end #end
#ifdef (ldMat322) #ifndef (MJHMat322) #declare MJHMat322 = ldMat322; #end #end
#ifdef (ldMat322) #ifndef (MJHMat322Slope) #declare MJHMat322Slope = ldMat322; #end #end

// row 134 - Light_Aqua
#ifdef (ldTex323) #ifndef (MJHTex323) #declare MJHTex323 = ldTex323; #end #end
#ifdef (ldTex323) #ifndef (MJHTex323Slope) #declare MJHTex323Slope = ldTex323; #end #end
#ifdef (ldMat323) #ifndef (MJHMat323) #declare MJHMat323 = ldMat323; #end #end
#ifdef (ldMat323) #ifndef (MJHMat323Slope) #declare MJHMat323Slope = ldMat323; #end #end

// row 135 - Rubber_Red
#ifdef (ldTex324) #ifndef (MJHTex324) #declare MJHTex324 = ldTex324; #end #end
#ifdef (ldTex324) #ifndef (MJHTex324Slope) #declare MJHTex324Slope = ldTex324; #end #end
#ifdef (ldMat324) #ifndef (MJHMat324) #declare MJHMat324 = ldMat324; #end #end
#ifdef (ldMat324) #ifndef (MJHMat324Slope) #declare MJHMat324Slope = ldMat324; #end #end

// row 136 - Yellowish_Green
#ifdef (ldTex326) #ifndef (MJHTex326) #declare MJHTex326 = ldTex326; #end #end
#ifdef (ldTex326) #ifndef (MJHTex326Slope) #declare MJHTex326Slope = ldTex326; #end #end
#ifdef (ldMat326) #ifndef (MJHMat326) #declare MJHMat326 = ldMat326; #end #end
#ifdef (ldMat326) #ifndef (MJHMat326Slope) #declare MJHMat326Slope = ldMat326; #end #end

// row 137 - Glow_In_Dark_White
#ifdef (ldTex329) #ifndef (MJHTex329) #declare MJHTex329 = ldTex329; #end #end
#ifdef (ldTex329) #ifndef (MJHTex329Slope) #declare MJHTex329Slope = ldTex329; #end #end
#ifdef (ldMat329) #ifndef (MJHMat329) #declare MJHMat329 = ldMat329; #end #end
#ifdef (ldMat329) #ifndef (MJHMat329Slope) #declare MJHMat329Slope = ldMat329; #end #end

// row 138 - Olive_Green
#ifdef (ldTex330) #ifndef (MJHTex330) #declare MJHTex330 = ldTex330; #end #end
#ifdef (ldTex330) #ifndef (MJHTex330Slope) #declare MJHTex330Slope = ldTex330; #end #end
#ifdef (ldMat330) #ifndef (MJHMat330) #declare MJHMat330 = ldMat330; #end #end
#ifdef (ldMat330) #ifndef (MJHMat330Slope) #declare MJHMat330Slope = ldMat330; #end #end

// row 139 - Chrome_Gold
#ifdef (ldTex334) #ifndef (MJHTex334) #declare MJHTex334 = ldTex334; #end #end
#ifdef (ldTex334) #ifndef (MJHTex334Slope) #declare MJHTex334Slope = ldTex334; #end #end
#ifdef (ldMat334) #ifndef (MJHMat334) #declare MJHMat334 = ldMat334; #end #end
#ifdef (ldMat334) #ifndef (MJHMat334Slope) #declare MJHMat334Slope = ldMat334; #end #end

// row 140 - Sand_Red
#ifdef (ldTex335) #ifndef (MJHTex335) #declare MJHTex335 = ldTex335; #end #end
#ifdef (ldTex335) #ifndef (MJHTex335Slope) #declare MJHTex335Slope = ldTex335; #end #end
#ifdef (ldMat335) #ifndef (MJHMat335) #declare MJHMat335 = ldMat335; #end #end
#ifdef (ldMat335) #ifndef (MJHMat335Slope) #declare MJHMat335Slope = ldMat335; #end #end

// row 141 - Glitter_Trans_Neon_Green
#ifdef (ldTex339) #ifndef (MJHTex339) #declare MJHTex339 = ldTex339; #end #end
#ifdef (ldTex339) #ifndef (MJHTex339Slope) #declare MJHTex339Slope = ldTex339; #end #end
#ifdef (ldMat339) #ifndef (MJHMat339) #declare MJHMat339 = ldMat339; #end #end
#ifdef (ldMat339) #ifndef (MJHMat339Slope) #declare MJHMat339Slope = ldMat339; #end #end

// row 142 - Rubber_Orange
#ifdef (ldTex350) #ifndef (MJHTex350) #declare MJHTex350 = ldTex350; #end #end
#ifdef (ldTex350) #ifndef (MJHTex350Slope) #declare MJHTex350Slope = ldTex350; #end #end
#ifdef (ldMat350) #ifndef (MJHMat350) #declare MJHMat350 = ldMat350; #end #end
#ifdef (ldMat350) #ifndef (MJHMat350Slope) #declare MJHMat350Slope = ldMat350; #end #end

// row 143 - Medium_Dark_Pink
#ifdef (ldTex351) #ifndef (MJHTex351) #declare MJHTex351 = ldTex351; #end #end
#ifdef (ldTex351) #ifndef (MJHTex351Slope) #declare MJHTex351Slope = ldTex351; #end #end
#ifdef (ldMat351) #ifndef (MJHMat351) #declare MJHMat351 = ldMat351; #end #end
#ifdef (ldMat351) #ifndef (MJHMat351Slope) #declare MJHMat351Slope = ldMat351; #end #end

// row 145 - Earth_Orange
#ifdef (ldTex366) #ifndef (MJHTex366) #declare MJHTex366 = ldTex366; #end #end
#ifdef (ldTex366) #ifndef (MJHTex366Slope) #declare MJHTex366Slope = ldTex366; #end #end
#ifdef (ldMat366) #ifndef (MJHMat366) #declare MJHMat366 = ldMat366; #end #end
#ifdef (ldMat366) #ifndef (MJHMat366Slope) #declare MJHMat366Slope = ldMat366; #end #end

// row 146 - Sand_Purple
#ifdef (ldTex373) #ifndef (MJHTex373) #declare MJHTex373 = ldTex373; #end #end
#ifdef (ldTex373) #ifndef (MJHTex373Slope) #declare MJHTex373Slope = ldTex373; #end #end
#ifdef (ldMat373) #ifndef (MJHMat373) #declare MJHMat373 = ldMat373; #end #end
#ifdef (ldMat373) #ifndef (MJHMat373Slope) #declare MJHMat373Slope = ldMat373; #end #end

// row 147 - Rubber_Light_Grey
#ifdef (ldTex375) #ifndef (MJHTex375) #declare MJHTex375 = ldTex375; #end #end
#ifdef (ldTex375) #ifndef (MJHTex375Slope) #declare MJHTex375Slope = ldTex375; #end #end
#ifdef (ldMat375) #ifndef (MJHMat375) #declare MJHMat375 = ldMat375; #end #end
#ifdef (ldMat375) #ifndef (MJHMat375Slope) #declare MJHMat375Slope = ldMat375; #end #end

// row 148 - Sand_Green
#ifdef (ldTex378) #ifndef (MJHTex378) #declare MJHTex378 = ldTex378; #end #end
#ifdef (ldTex378) #ifndef (MJHTex378Slope) #declare MJHTex378Slope = ldTex378; #end #end
#ifdef (ldMat378) #ifndef (MJHMat378) #declare MJHMat378 = ldMat378; #end #end
#ifdef (ldMat378) #ifndef (MJHMat378Slope) #declare MJHMat378Slope = ldMat378; #end #end

// row 149 - Sand_Blue
#ifdef (ldTex379) #ifndef (MJHTex379) #declare MJHTex379 = ldTex379; #end #end
#ifdef (ldTex379) #ifndef (MJHTex379Slope) #declare MJHTex379Slope = ldTex379; #end #end
#ifdef (ldMat379) #ifndef (MJHMat379) #declare MJHMat379 = ldMat379; #end #end
#ifdef (ldMat379) #ifndef (MJHMat379Slope) #declare MJHMat379Slope = ldMat379; #end #end

// row 150 - Chrome_Silver
#ifdef (ldTex383) #ifndef (MJHTex383) #declare MJHTex383 = ldTex383; #end #end
#ifdef (ldTex383) #ifndef (MJHTex383Slope) #declare MJHTex383Slope = ldTex383; #end #end
#ifdef (ldMat383) #ifndef (MJHMat383) #declare MJHMat383 = ldMat383; #end #end
#ifdef (ldMat383) #ifndef (MJHMat383Slope) #declare MJHMat383Slope = ldMat383; #end #end

// row 151 - Rubber_Dark_Blue
#ifdef (ldTex406) #ifndef (MJHTex406) #declare MJHTex406 = ldTex406; #end #end
#ifdef (ldTex406) #ifndef (MJHTex406Slope) #declare MJHTex406Slope = ldTex406; #end #end
#ifdef (ldMat406) #ifndef (MJHMat406) #declare MJHMat406 = ldMat406; #end #end
#ifdef (ldMat406) #ifndef (MJHMat406Slope) #declare MJHMat406Slope = ldMat406; #end #end

// row 152 - Rubber_Purple
#ifdef (ldTex449) #ifndef (MJHTex449) #declare MJHTex449 = ldTex449; #end #end
#ifdef (ldTex449) #ifndef (MJHTex449Slope) #declare MJHTex449Slope = ldTex449; #end #end
#ifdef (ldMat449) #ifndef (MJHMat449) #declare MJHMat449 = ldMat449; #end #end
#ifdef (ldMat449) #ifndef (MJHMat449Slope) #declare MJHMat449Slope = ldMat449; #end #end

// row 153 - Fabuland_Brown
#ifdef (ldTex450) #ifndef (MJHTex450) #declare MJHTex450 = ldTex450; #end #end
#ifdef (ldTex450) #ifndef (MJHTex450Slope) #declare MJHTex450Slope = ldTex450; #end #end
#ifdef (ldMat450) #ifndef (MJHMat450) #declare MJHMat450 = ldMat450; #end #end
#ifdef (ldMat450) #ifndef (MJHMat450Slope) #declare MJHMat450Slope = ldMat450; #end #end

// row 154 - Medium_Orange
#ifdef (ldTex462) #ifndef (MJHTex462) #declare MJHTex462 = ldTex462; #end #end
#ifdef (ldTex462) #ifndef (MJHTex462Slope) #declare MJHTex462Slope = ldTex462; #end #end
#ifdef (ldMat462) #ifndef (MJHMat462) #declare MJHMat462 = ldMat462; #end #end
#ifdef (ldMat462) #ifndef (MJHMat462Slope) #declare MJHMat462Slope = ldMat462; #end #end

// row 155 - Dark_Orange
#ifdef (ldTex484) #ifndef (MJHTex484) #declare MJHTex484 = ldTex484; #end #end
#ifdef (ldTex484) #ifndef (MJHTex484Slope) #declare MJHTex484Slope = ldTex484; #end #end
#ifdef (ldMat484) #ifndef (MJHMat484) #declare MJHMat484 = ldMat484; #end #end
#ifdef (ldMat484) #ifndef (MJHMat484Slope) #declare MJHMat484Slope = ldMat484; #end #end

// row 156 - Rubber_Lime
#ifdef (ldTex490) #ifndef (MJHTex490) #declare MJHTex490 = ldTex490; #end #end
#ifdef (ldTex490) #ifndef (MJHTex490Slope) #declare MJHTex490Slope = ldTex490; #end #end
#ifdef (ldMat490) #ifndef (MJHMat490) #declare MJHMat490 = ldMat490; #end #end
#ifdef (ldMat490) #ifndef (MJHMat490Slope) #declare MJHMat490Slope = ldMat490; #end #end

// row 157 - Magnet
#ifdef (ldTex493) #ifndef (MJHTex493) #declare MJHTex493 = ldTex493; #end #end
#ifdef (ldTex493) #ifndef (MJHTex493Slope) #declare MJHTex493Slope = ldTex493; #end #end
#ifdef (ldMat493) #ifndef (MJHMat493) #declare MJHMat493 = ldMat493; #end #end
#ifdef (ldMat493) #ifndef (MJHMat493Slope) #declare MJHMat493Slope = ldMat493; #end #end

// row 158 - Electric_Contact_Alloy
#ifdef (ldTex494) #ifndef (MJHTex494) #declare MJHTex494 = ldTex494; #end #end
#ifdef (ldTex494) #ifndef (MJHTex494Slope) #declare MJHTex494Slope = ldTex494; #end #end
#ifdef (ldMat494) #ifndef (MJHMat494) #declare MJHMat494 = ldMat494; #end #end
#ifdef (ldMat494) #ifndef (MJHMat494Slope) #declare MJHMat494Slope = ldMat494; #end #end

// row 159 - Electric_Contact_Copper
#ifdef (ldTex495) #ifndef (MJHTex495) #declare MJHTex495 = ldTex495; #end #end
#ifdef (ldTex495) #ifndef (MJHTex495Slope) #declare MJHTex495Slope = ldTex495; #end #end
#ifdef (ldMat495) #ifndef (MJHMat495) #declare MJHMat495 = ldMat495; #end #end
#ifdef (ldMat495) #ifndef (MJHMat495Slope) #declare MJHMat495Slope = ldMat495; #end #end

// row 160 - Rubber_Light_Bluish_Grey
#ifdef (ldTex496) #ifndef (MJHTex496) #declare MJHTex496 = ldTex496; #end #end
#ifdef (ldTex496) #ifndef (MJHTex496Slope) #declare MJHTex496Slope = ldTex496; #end #end
#ifdef (ldMat496) #ifndef (MJHMat496) #declare MJHMat496 = ldMat496; #end #end
#ifdef (ldMat496) #ifndef (MJHMat496Slope) #declare MJHMat496Slope = ldMat496; #end #end

// row 161 - Very_Light_Grey
#ifdef (ldTex503) #ifndef (MJHTex503) #declare MJHTex503 = ldTex503; #end #end
#ifdef (ldTex503) #ifndef (MJHTex503Slope) #declare MJHTex503Slope = ldTex503; #end #end
#ifdef (ldMat503) #ifndef (MJHMat503) #declare MJHMat503 = ldMat503; #end #end
#ifdef (ldMat503) #ifndef (MJHMat503Slope) #declare MJHMat503Slope = ldMat503; #end #end

// row 162 - Rubber_Flat_Silver
#ifdef (ldTex504) #ifndef (MJHTex504) #declare MJHTex504 = ldTex504; #end #end
#ifdef (ldTex504) #ifndef (MJHTex504Slope) #declare MJHTex504Slope = ldTex504; #end #end
#ifdef (ldMat504) #ifndef (MJHMat504) #declare MJHMat504 = ldMat504; #end #end
#ifdef (ldMat504) #ifndef (MJHMat504Slope) #declare MJHMat504Slope = ldMat504; #end #end

// row 166 - Rubber_White
#ifdef (ldTex511) #ifndef (MJHTex511) #declare MJHTex511 = ldTex511; #end #end
#ifdef (ldTex511) #ifndef (MJHTex511Slope) #declare MJHTex511Slope = ldTex511; #end #end
#ifdef (ldMat511) #ifndef (MJHMat511) #declare MJHMat511 = ldMat511; #end #end
#ifdef (ldMat511) #ifndef (MJHMat511Slope) #declare MJHMat511Slope = ldMat511; #end #end
