cd "D:\GitHub\Datsville\datsville_master"
del "snotroad_doubleblankcross_00.ldr"
ren "snotroad_doubleblankcross_10.ldr" "snotroad_doubleblank_20.ldr"
ren "snotroad_doubleblankcross_10_stop.ldr" "snotroad_doubleblank_30.ldr"
ren "snotroad_doubleblankcross_11.ldr" "snotroad_doubleblank_22.ldr"
del "snotroad_doubleonewaycross_00.ldr"
ren "snotroad_doubleonewaycross_10.ldr" "snotroad_doubleoneway_20.ldr"
ren "snotroad_doubleonewaycross_10_stop.ldr" "snotroad_doubleoneway_30.ldr"
ren "snotroad_doubleonewaycross_11.ldr" "snotroad_doubleoneway_22.ldr"
ren "snotroad_doubleonewaycross_11_stop.ldr" "snotroad_doubleoneway_33.ldr"
del "snotroad_doublestripecross_00.ldr"
ren "snotroad_doublestripecross_10.ldr" "snotroad_doublestripe_20.ldr"
ren "snotroad_doublestripecross_10_leftonly.ldr" "snotroad_doublestripe_20_leftonly.ldr"
ren "snotroad_doublestripecross_10_rightaheadonly.ldr" "snotroad_doublestripe_20_rightaheadonly.ldr"
ren "snotroad_doublestripecross_10_rightonly.ldr" "snotroad_doublestripe_20_rightonly.ldr"
ren "snotroad_doublestripecross_11.ldr" "snotroad_doublestripe_22.ldr"
ren "snotroad_doublestripecross_11_leftaheadonly.ldr" "snotroad_doublestripe_22_leftaheadonly.ldr"
ren "snotroad_doublestripecross_11_leftonly.ldr" "snotroad_doublestripe_22_leftonly.ldr"
ren "snotroad_doublestripecrossstop_10.ldr" "snotroad_doublestripe_30.ldr"
ren "snotroad_doublestripecrossstop_10_leftonly.ldr" "snotroad_doublestripe_30_leftonly.ldr"
ren "snotroad_doublestripecrossstop_11.ldr" "snotroad_doublestripe_33.ldr"
ren "snotroad_doublestripecrossstop_11_leftaheadonly.ldr" "snotroad_doublestripe_33_leftaheadonly.ldr"
ren "snotroad_doublestripecrossstop_11_leftonly.ldr" "snotroad_doublestripe_33_leftonly.ldr"
del "snotroad_halfstripecross_00.ldr"
ren "snotroad_halfstripecross_10.ldr" "snotroad_halfstripe_20.ldr"
ren "snotroad_quadblankcross_0000.ldr" "snotroad_quadblank_0000.ldr"
ren "snotroad_quadblankcross_1000.ldr" "snotroad_quadblank_2000.ldr"
ren "snotroad_quadblankcross_1010.ldr" "snotroad_quadblank_2020.ldr"
ren "snotroad_quadblankcross_1100.ldr" "snotroad_quadblank_2200.ldr"
ren "snotroad_quadblankcross_1110.ldr" "snotroad_quadblank_2220.ldr"
ren "snotroad_quadblankcross_1111.ldr" "snotroad_quadblank_2222.ldr"
ren "snotroad_quaddotscross_0000.ldr" "snotroad_quaddots_0000.ldr"
ren "snotroad_quaddotscross_1000.ldr" "snotroad_quaddots_2000.ldr"
ren "snotroad_quaddotscross_1010.ldr" "snotroad_quaddots_2020.ldr"
ren "snotroad_quaddotscross_1100.ldr" "snotroad_quaddots_2200.ldr"
ren "snotroad_quaddotscross_1110.ldr" "snotroad_quaddots_2220.ldr"
ren "snotroad_quaddotscross_1111.ldr" "snotroad_quaddots_2222.ldr"
ren "snotroad_quadstripecross_0000.ldr" "snotroad_quadstripe_0000.ldr"
ren "snotroad_quadstripecross_0101.ldr" "snotroad_quadstripe_0202.ldr"
ren "snotroad_quadstripecross_1000.ldr" "snotroad_quadstripe_2000.ldr"
ren "snotroad_quadstripecross_1010.ldr" "snotroad_quadstripe_2020.ldr"
ren "snotroad_quadstripecross_1100.ldr" "snotroad_quadstripe_2200.ldr"
ren "snotroad_quadstripecross_1110.ldr" "snotroad_quadstripe_2220.ldr"
ren "snotroad_quadstripecross_1111.ldr" "snotroad_quadstripe_2222.ldr"
del "snotroad_tripleblankcross_000.ldr"
ren "snotroad_tripleblankcross_001.ldr" "snotroad_tripleblank_002.ldr"
ren "snotroad_tripleblankcross_010.ldr" "snotroad_tripleblank_020.ldr"
ren "snotroad_tripleblankcross_011.ldr" "snotroad_tripleblank_022.ldr"
ren "snotroad_tripleblankcross_100.ldr" "snotroad_tripleblank_200.ldr"
ren "snotroad_tripleblankcross_101.ldr" "snotroad_tripleblank_202.ldr"
ren "snotroad_tripleblankcross_110.ldr" "snotroad_tripleblank_220.ldr"
ren "snotroad_tripleblankcross_111.ldr" "snotroad_tripleblank_222.ldr"
del "snotroad_tripledotscross_000.ldr"
ren "snotroad_tripledotscross_001.ldr" "snotroad_tripledots_002.ldr"
ren "snotroad_tripledotscross_010.ldr" "snotroad_tripledots_020.ldr"
ren "snotroad_tripledotscross_011.ldr" "snotroad_tripledots_022.ldr"
ren "snotroad_tripledotscross_100.ldr" "snotroad_tripledots_200.ldr"
ren "snotroad_tripledotscross_101.ldr" "snotroad_tripledots_202.ldr"
ren "snotroad_tripledotscross_110.ldr" "snotroad_tripledots_220.ldr"
ren "snotroad_tripledotscross_111.ldr" "snotroad_tripledots_222.ldr"
del "snotroad_tripleonewaycross_000.ldr"
ren "snotroad_tripleonewaycross_001.ldr" "snotroad_tripleoneway_002.ldr"
ren "snotroad_tripleonewaycross_010.ldr" "snotroad_tripleoneway_020.ldr"
ren "snotroad_tripleonewaycross_011.ldr" "snotroad_tripleoneway_022.ldr"
ren "snotroad_tripleonewaycross_100.ldr" "snotroad_tripleoneway_200.ldr"
ren "snotroad_tripleonewaycross_101.ldr" "snotroad_tripleoneway_202.ldr"
ren "snotroad_tripleonewaycross_110.ldr" "snotroad_tripleoneway_220.ldr"
ren "snotroad_tripleonewaycross_111.ldr" "snotroad_tripleoneway_222.ldr"
del "snotroad_triplestripecross_000.ldr"
ren "snotroad_triplestripecross_001.ldr" "snotroad_triplestripe_002.ldr"
ren "snotroad_triplestripecross_010.ldr" "snotroad_triplestripe_020.ldr"
ren "snotroad_triplestripecross_011.ldr" "snotroad_triplestripe_022.ldr"
ren "snotroad_triplestripecross_100.ldr" "snotroad_triplestripe_200.ldr"
ren "snotroad_triplestripecross_100_rightonly.ldr" "snotroad_triplestripe_200_rightonly.ldr"
ren "snotroad_triplestripecross_101.ldr" "snotroad_triplestripe_202.ldr"
ren "snotroad_triplestripecross_110.ldr" "snotroad_triplestripe_220.ldr"
ren "snotroad_triplestripecross_111.ldr" "snotroad_triplestripe_222.ldr"
pause
