// POV-Ray scripts for LDraw models and scenes
// Copyright (C) 2019  Michael Horvath
// 
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
// 
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA


// row 1 - Black
#ifdef (LDXColor0) #ifndef (MJHMat0) #declare MJHMat0 = LDXColor0; #end #end
#ifdef (LDXColor0) #ifndef (MJHMat0Slope) #declare MJHMat0Slope = LDXColor0; #end #end

// row 2 - Blue
#ifdef (LDXColor1) #ifndef (MJHMat1) #declare MJHMat1 = LDXColor1; #end #end
#ifdef (LDXColor1) #ifndef (MJHMat1Slope) #declare MJHMat1Slope = LDXColor1; #end #end

// row 3 - Green
#ifdef (LDXColor2) #ifndef (MJHMat2) #declare MJHMat2 = LDXColor2; #end #end
#ifdef (LDXColor2) #ifndef (MJHMat2Slope) #declare MJHMat2Slope = LDXColor2; #end #end

// row 4 - Dark_Turquoise
#ifdef (LDXColor3) #ifndef (MJHMat3) #declare MJHMat3 = LDXColor3; #end #end
#ifdef (LDXColor3) #ifndef (MJHMat3Slope) #declare MJHMat3Slope = LDXColor3; #end #end

// row 5 - Red
#ifdef (LDXColor4) #ifndef (MJHMat4) #declare MJHMat4 = LDXColor4; #end #end
#ifdef (LDXColor4) #ifndef (MJHMat4Slope) #declare MJHMat4Slope = LDXColor4; #end #end

// row 6 - Dark_Pink
#ifdef (LDXColor5) #ifndef (MJHMat5) #declare MJHMat5 = LDXColor5; #end #end
#ifdef (LDXColor5) #ifndef (MJHMat5Slope) #declare MJHMat5Slope = LDXColor5; #end #end

// row 7 - Brown
#ifdef (LDXColor6) #ifndef (MJHMat6) #declare MJHMat6 = LDXColor6; #end #end
#ifdef (LDXColor6) #ifndef (MJHMat6Slope) #declare MJHMat6Slope = LDXColor6; #end #end

// row 8 - Light_Grey
#ifdef (LDXColor7) #ifndef (MJHMat7) #declare MJHMat7 = LDXColor7; #end #end
#ifdef (LDXColor7) #ifndef (MJHMat7Slope) #declare MJHMat7Slope = LDXColor7; #end #end

// row 9 - Dark_Grey
#ifdef (LDXColor8) #ifndef (MJHMat8) #declare MJHMat8 = LDXColor8; #end #end
#ifdef (LDXColor8) #ifndef (MJHMat8Slope) #declare MJHMat8Slope = LDXColor8; #end #end

// row 10 - Light_Blue
#ifdef (LDXColor9) #ifndef (MJHMat9) #declare MJHMat9 = LDXColor9; #end #end
#ifdef (LDXColor9) #ifndef (MJHMat9Slope) #declare MJHMat9Slope = LDXColor9; #end #end

// row 11 - Bright_Green
#ifdef (LDXColor10) #ifndef (MJHMat10) #declare MJHMat10 = LDXColor10; #end #end
#ifdef (LDXColor10) #ifndef (MJHMat10Slope) #declare MJHMat10Slope = LDXColor10; #end #end

// row 12 - Light_Turquoise
#ifdef (LDXColor11) #ifndef (MJHMat11) #declare MJHMat11 = LDXColor11; #end #end
#ifdef (LDXColor11) #ifndef (MJHMat11Slope) #declare MJHMat11Slope = LDXColor11; #end #end

// row 13 - Salmon
#ifdef (LDXColor12) #ifndef (MJHMat12) #declare MJHMat12 = LDXColor12; #end #end
#ifdef (LDXColor12) #ifndef (MJHMat12Slope) #declare MJHMat12Slope = LDXColor12; #end #end

// row 14 - Pink
#ifdef (LDXColor13) #ifndef (MJHMat13) #declare MJHMat13 = LDXColor13; #end #end
#ifdef (LDXColor13) #ifndef (MJHMat13Slope) #declare MJHMat13Slope = LDXColor13; #end #end

// row 15 - Yellow
#ifdef (LDXColor14) #ifndef (MJHMat14) #declare MJHMat14 = LDXColor14; #end #end
#ifdef (LDXColor14) #ifndef (MJHMat14Slope) #declare MJHMat14Slope = LDXColor14; #end #end

// row 16 - White
#ifdef (LDXColor15) #ifndef (MJHMat15) #declare MJHMat15 = LDXColor15; #end #end
#ifdef (LDXColor15) #ifndef (MJHMat15Slope) #declare MJHMat15Slope = LDXColor15; #end #end

// row 17 - Main_Colour
#ifdef (LDXColor16) #ifndef (MJHMat16) #declare MJHMat16 = LDXColor16; #end #end
#ifdef (LDXColor16) #ifndef (MJHMat16Slope) #declare MJHMat16Slope = LDXColor16; #end #end

// row 18 - Light_Green
#ifdef (LDXColor17) #ifndef (MJHMat17) #declare MJHMat17 = LDXColor17; #end #end
#ifdef (LDXColor17) #ifndef (MJHMat17Slope) #declare MJHMat17Slope = LDXColor17; #end #end

// row 19 - Light_Yellow
#ifdef (LDXColor18) #ifndef (MJHMat18) #declare MJHMat18 = LDXColor18; #end #end
#ifdef (LDXColor18) #ifndef (MJHMat18Slope) #declare MJHMat18Slope = LDXColor18; #end #end

// row 20 - Tan
#ifdef (LDXColor19) #ifndef (MJHMat19) #declare MJHMat19 = LDXColor19; #end #end
#ifdef (LDXColor19) #ifndef (MJHMat19Slope) #declare MJHMat19Slope = LDXColor19; #end #end

// row 21 - Light_Violet
#ifdef (LDXColor20) #ifndef (MJHMat20) #declare MJHMat20 = LDXColor20; #end #end
#ifdef (LDXColor20) #ifndef (MJHMat20Slope) #declare MJHMat20Slope = LDXColor20; #end #end

// row 22 - Glow_In_Dark_Opaque
#ifdef (LDXColor21) #ifndef (MJHMat21) #declare MJHMat21 = LDXColor21; #end #end
#ifdef (LDXColor21) #ifndef (MJHMat21Slope) #declare MJHMat21Slope = LDXColor21; #end #end

// row 23 - Purple
#ifdef (LDXColor22) #ifndef (MJHMat22) #declare MJHMat22 = LDXColor22; #end #end
#ifdef (LDXColor22) #ifndef (MJHMat22Slope) #declare MJHMat22Slope = LDXColor22; #end #end

// row 24 - Dark_Blue_Violet
#ifdef (LDXColor23) #ifndef (MJHMat23) #declare MJHMat23 = LDXColor23; #end #end
#ifdef (LDXColor23) #ifndef (MJHMat23Slope) #declare MJHMat23Slope = LDXColor23; #end #end

// row 25 - Edge_Colour
#ifdef (LDXColor24) #ifndef (MJHMat24) #declare MJHMat24 = LDXColor24; #end #end
#ifdef (LDXColor24) #ifndef (MJHMat24Slope) #declare MJHMat24Slope = LDXColor24; #end #end

// row 26 - Orange
#ifdef (LDXColor25) #ifndef (MJHMat25) #declare MJHMat25 = LDXColor25; #end #end
#ifdef (LDXColor25) #ifndef (MJHMat25Slope) #declare MJHMat25Slope = LDXColor25; #end #end

// row 27 - Magenta
#ifdef (LDXColor26) #ifndef (MJHMat26) #declare MJHMat26 = LDXColor26; #end #end
#ifdef (LDXColor26) #ifndef (MJHMat26Slope) #declare MJHMat26Slope = LDXColor26; #end #end

// row 28 - Lime
#ifdef (LDXColor27) #ifndef (MJHMat27) #declare MJHMat27 = LDXColor27; #end #end
#ifdef (LDXColor27) #ifndef (MJHMat27Slope) #declare MJHMat27Slope = LDXColor27; #end #end

// row 29 - Dark_Tan
#ifdef (LDXColor28) #ifndef (MJHMat28) #declare MJHMat28 = LDXColor28; #end #end
#ifdef (LDXColor28) #ifndef (MJHMat28Slope) #declare MJHMat28Slope = LDXColor28; #end #end

// row 30 - Bright_Pink
#ifdef (LDXColor29) #ifndef (MJHMat29) #declare MJHMat29 = LDXColor29; #end #end
#ifdef (LDXColor29) #ifndef (MJHMat29Slope) #declare MJHMat29Slope = LDXColor29; #end #end

// row 31 - Medium_Lavender
#ifdef (LDXColor30) #ifndef (MJHMat30) #declare MJHMat30 = LDXColor30; #end #end
#ifdef (LDXColor30) #ifndef (MJHMat30Slope) #declare MJHMat30Slope = LDXColor30; #end #end

// row 32 - Lavender
#ifdef (LDXColor31) #ifndef (MJHMat31) #declare MJHMat31 = LDXColor31; #end #end
#ifdef (LDXColor31) #ifndef (MJHMat31Slope) #declare MJHMat31Slope = LDXColor31; #end #end

// row 33 - Trans_Black_IR_Lens
#ifdef (LDXColor32) #ifndef (MJHMat32) #declare MJHMat32 = LDXColor32; #end #end
#ifdef (LDXColor32) #ifndef (MJHMat32Slope) #declare MJHMat32Slope = LDXColor32; #end #end

// row 34 - Trans_Dark_Blue
#ifdef (LDXColor33) #ifndef (MJHMat33) #declare MJHMat33 = LDXColor33; #end #end
#ifdef (LDXColor33) #ifndef (MJHMat33Slope) #declare MJHMat33Slope = LDXColor33; #end #end

// row 35 - Trans_Green
#ifdef (LDXColor34) #ifndef (MJHMat34) #declare MJHMat34 = LDXColor34; #end #end
#ifdef (LDXColor34) #ifndef (MJHMat34Slope) #declare MJHMat34Slope = LDXColor34; #end #end

// row 36 - Trans_Bright_Green
#ifdef (LDXColor35) #ifndef (MJHMat35) #declare MJHMat35 = LDXColor35; #end #end
#ifdef (LDXColor35) #ifndef (MJHMat35Slope) #declare MJHMat35Slope = LDXColor35; #end #end

// row 37 - Trans_Red
#ifdef (LDXColor36) #ifndef (MJHMat36) #declare MJHMat36 = LDXColor36; #end #end
#ifdef (LDXColor36) #ifndef (MJHMat36Slope) #declare MJHMat36Slope = LDXColor36; #end #end

// row 38 - Trans_Dark_Pink
#ifdef (LDXColor37) #ifndef (MJHMat37) #declare MJHMat37 = LDXColor37; #end #end
#ifdef (LDXColor37) #ifndef (MJHMat37Slope) #declare MJHMat37Slope = LDXColor37; #end #end

// row 39 - Trans_Neon_Orange
#ifdef (LDXColor38) #ifndef (MJHMat38) #declare MJHMat38 = LDXColor38; #end #end
#ifdef (LDXColor38) #ifndef (MJHMat38Slope) #declare MJHMat38Slope = LDXColor38; #end #end

// row 40 - Trans_Very_Light_Blue
#ifdef (LDXColor39) #ifndef (MJHMat39) #declare MJHMat39 = LDXColor39; #end #end
#ifdef (LDXColor39) #ifndef (MJHMat39Slope) #declare MJHMat39Slope = LDXColor39; #end #end

// row 41 - Trans_Black
#ifdef (LDXColor40) #ifndef (MJHMat40) #declare MJHMat40 = LDXColor40; #end #end
#ifdef (LDXColor40) #ifndef (MJHMat40Slope) #declare MJHMat40Slope = LDXColor40; #end #end

// row 42 - Trans_Medium_Blue
#ifdef (LDXColor41) #ifndef (MJHMat41) #declare MJHMat41 = LDXColor41; #end #end
#ifdef (LDXColor41) #ifndef (MJHMat41Slope) #declare MJHMat41Slope = LDXColor41; #end #end

// row 43 - Trans_Neon_Green
#ifdef (LDXColor42) #ifndef (MJHMat42) #declare MJHMat42 = LDXColor42; #end #end
#ifdef (LDXColor42) #ifndef (MJHMat42Slope) #declare MJHMat42Slope = LDXColor42; #end #end

// row 44 - Trans_Light_Blue
#ifdef (LDXColor43) #ifndef (MJHMat43) #declare MJHMat43 = LDXColor43; #end #end
#ifdef (LDXColor43) #ifndef (MJHMat43Slope) #declare MJHMat43Slope = LDXColor43; #end #end

// row 45 - Trans_Bright_Reddish_Lilac
#ifdef (LDXColor44) #ifndef (MJHMat44) #declare MJHMat44 = LDXColor44; #end #end
#ifdef (LDXColor44) #ifndef (MJHMat44Slope) #declare MJHMat44Slope = LDXColor44; #end #end

// row 46 - Trans_Pink
#ifdef (LDXColor45) #ifndef (MJHMat45) #declare MJHMat45 = LDXColor45; #end #end
#ifdef (LDXColor45) #ifndef (MJHMat45Slope) #declare MJHMat45Slope = LDXColor45; #end #end

// row 47 - Trans_Yellow
#ifdef (LDXColor46) #ifndef (MJHMat46) #declare MJHMat46 = LDXColor46; #end #end
#ifdef (LDXColor46) #ifndef (MJHMat46Slope) #declare MJHMat46Slope = LDXColor46; #end #end

// row 48 - Trans_Clear
#ifdef (LDXColor47) #ifndef (MJHMat47) #declare MJHMat47 = LDXColor47; #end #end
#ifdef (LDXColor47) #ifndef (MJHMat47Slope) #declare MJHMat47Slope = LDXColor47; #end #end

// row 49 - Trans_Purple
#ifdef (LDXColor52) #ifndef (MJHMat52) #declare MJHMat52 = LDXColor52; #end #end
#ifdef (LDXColor52) #ifndef (MJHMat52Slope) #declare MJHMat52Slope = LDXColor52; #end #end

// row 50 - Trans_Neon_Yellow
#ifdef (LDXColor54) #ifndef (MJHMat54) #declare MJHMat54 = LDXColor54; #end #end
#ifdef (LDXColor54) #ifndef (MJHMat54Slope) #declare MJHMat54Slope = LDXColor54; #end #end

// row 51 - Trans_Orange
#ifdef (LDXColor57) #ifndef (MJHMat57) #declare MJHMat57 = LDXColor57; #end #end
#ifdef (LDXColor57) #ifndef (MJHMat57Slope) #declare MJHMat57Slope = LDXColor57; #end #end

// row 52 - Chrome_Antique_Brass
#ifdef (LDXColor60) #ifndef (MJHMat60) #declare MJHMat60 = LDXColor60; #end #end
#ifdef (LDXColor60) #ifndef (MJHMat60Slope) #declare MJHMat60Slope = LDXColor60; #end #end

// row 53 - Chrome_Blue
#ifdef (LDXColor61) #ifndef (MJHMat61) #declare MJHMat61 = LDXColor61; #end #end
#ifdef (LDXColor61) #ifndef (MJHMat61Slope) #declare MJHMat61Slope = LDXColor61; #end #end

// row 54 - Chrome_Green
#ifdef (LDXColor62) #ifndef (MJHMat62) #declare MJHMat62 = LDXColor62; #end #end
#ifdef (LDXColor62) #ifndef (MJHMat62Slope) #declare MJHMat62Slope = LDXColor62; #end #end

// row 55 - Chrome_Pink
#ifdef (LDXColor63) #ifndef (MJHMat63) #declare MJHMat63 = LDXColor63; #end #end
#ifdef (LDXColor63) #ifndef (MJHMat63Slope) #declare MJHMat63Slope = LDXColor63; #end #end

// row 56 - Chrome_Black
#ifdef (LDXColor64) #ifndef (MJHMat64) #declare MJHMat64 = LDXColor64; #end #end
#ifdef (LDXColor64) #ifndef (MJHMat64Slope) #declare MJHMat64Slope = LDXColor64; #end #end

// row 57 - Rubber_Yellow
#ifdef (LDXColor65) #ifndef (MJHMat65) #declare MJHMat65 = LDXColor65; #end #end
#ifdef (LDXColor65) #ifndef (MJHMat65Slope) #declare MJHMat65Slope = LDXColor65; #end #end

// row 58 - Rubber_Trans_Yellow
#ifdef (LDXColor66) #ifndef (MJHMat66) #declare MJHMat66 = LDXColor66; #end #end
#ifdef (LDXColor66) #ifndef (MJHMat66Slope) #declare MJHMat66Slope = LDXColor66; #end #end

// row 59 - Rubber_Trans_Clear
#ifdef (LDXColor67) #ifndef (MJHMat67) #declare MJHMat67 = LDXColor67; #end #end
#ifdef (LDXColor67) #ifndef (MJHMat67Slope) #declare MJHMat67Slope = LDXColor67; #end #end

// row 60 - Very_Light_Orange
#ifdef (LDXColor68) #ifndef (MJHMat68) #declare MJHMat68 = LDXColor68; #end #end
#ifdef (LDXColor68) #ifndef (MJHMat68Slope) #declare MJHMat68Slope = LDXColor68; #end #end

// row 61 - Bright_Reddish_Lilac
#ifdef (LDXColor69) #ifndef (MJHMat69) #declare MJHMat69 = LDXColor69; #end #end
#ifdef (LDXColor69) #ifndef (MJHMat69Slope) #declare MJHMat69Slope = LDXColor69; #end #end

// row 62 - Reddish_Brown
#ifdef (LDXColor70) #ifndef (MJHMat70) #declare MJHMat70 = LDXColor70; #end #end
#ifdef (LDXColor70) #ifndef (MJHMat70Slope) #declare MJHMat70Slope = LDXColor70; #end #end

// row 63 - Light_Bluish_Grey
#ifdef (LDXColor71) #ifndef (MJHMat71) #declare MJHMat71 = LDXColor71; #end #end
#ifdef (LDXColor71) #ifndef (MJHMat71Slope) #declare MJHMat71Slope = LDXColor71; #end #end

// row 64 - Dark_Bluish_Grey
#ifdef (LDXColor72) #ifndef (MJHMat72) #declare MJHMat72 = LDXColor72; #end #end
#ifdef (LDXColor72) #ifndef (MJHMat72Slope) #declare MJHMat72Slope = LDXColor72; #end #end

// row 65 - Medium_Blue
#ifdef (LDXColor73) #ifndef (MJHMat73) #declare MJHMat73 = LDXColor73; #end #end
#ifdef (LDXColor73) #ifndef (MJHMat73Slope) #declare MJHMat73Slope = LDXColor73; #end #end

// row 66 - Medium_Green
#ifdef (LDXColor74) #ifndef (MJHMat74) #declare MJHMat74 = LDXColor74; #end #end
#ifdef (LDXColor74) #ifndef (MJHMat74Slope) #declare MJHMat74Slope = LDXColor74; #end #end

// row 67 - Speckle_Black_Copper
#ifdef (LDXColor75) #ifndef (MJHMat75) #declare MJHMat75 = LDXColor75; #end #end
#ifdef (LDXColor75) #ifndef (MJHMat75Slope) #declare MJHMat75Slope = LDXColor75; #end #end

// row 68 - Speckle_Dark_Bluish_Grey_Silver
#ifdef (LDXColor76) #ifndef (MJHMat76) #declare MJHMat76 = LDXColor76; #end #end
#ifdef (LDXColor76) #ifndef (MJHMat76Slope) #declare MJHMat76Slope = LDXColor76; #end #end

// row 69 - Light_Pink
#ifdef (LDXColor77) #ifndef (MJHMat77) #declare MJHMat77 = LDXColor77; #end #end
#ifdef (LDXColor77) #ifndef (MJHMat77Slope) #declare MJHMat77Slope = LDXColor77; #end #end

// row 70 - Light_Flesh
#ifdef (LDXColor78) #ifndef (MJHMat78) #declare MJHMat78 = LDXColor78; #end #end
#ifdef (LDXColor78) #ifndef (MJHMat78Slope) #declare MJHMat78Slope = LDXColor78; #end #end

// row 71 - Milky_White
#ifdef (LDXColor79) #ifndef (MJHMat79) #declare MJHMat79 = LDXColor79; #end #end
#ifdef (LDXColor79) #ifndef (MJHMat79Slope) #declare MJHMat79Slope = LDXColor79; #end #end

// row 72 - Metallic_Silver
#ifdef (LDXColor80) #ifndef (MJHMat80) #declare MJHMat80 = LDXColor80; #end #end
#ifdef (LDXColor80) #ifndef (MJHMat80Slope) #declare MJHMat80Slope = LDXColor80; #end #end

// row 73 - Metallic_Green
#ifdef (LDXColor81) #ifndef (MJHMat81) #declare MJHMat81 = LDXColor81; #end #end
#ifdef (LDXColor81) #ifndef (MJHMat81Slope) #declare MJHMat81Slope = LDXColor81; #end #end

// row 74 - Metallic_Gold
#ifdef (LDXColor82) #ifndef (MJHMat82) #declare MJHMat82 = LDXColor82; #end #end
#ifdef (LDXColor82) #ifndef (MJHMat82Slope) #declare MJHMat82Slope = LDXColor82; #end #end

// row 75 - Metallic_Black
#ifdef (LDXColor83) #ifndef (MJHMat83) #declare MJHMat83 = LDXColor83; #end #end
#ifdef (LDXColor83) #ifndef (MJHMat83Slope) #declare MJHMat83Slope = LDXColor83; #end #end

// row 76 - Medium_Dark_Flesh
#ifdef (LDXColor84) #ifndef (MJHMat84) #declare MJHMat84 = LDXColor84; #end #end
#ifdef (LDXColor84) #ifndef (MJHMat84Slope) #declare MJHMat84Slope = LDXColor84; #end #end

// row 77 - Medium_Lilac
#ifdef (LDXColor85) #ifndef (MJHMat85) #declare MJHMat85 = LDXColor85; #end #end
#ifdef (LDXColor85) #ifndef (MJHMat85Slope) #declare MJHMat85Slope = LDXColor85; #end #end

// row 78 - Dark_Flesh
#ifdef (LDXColor86) #ifndef (MJHMat86) #declare MJHMat86 = LDXColor86; #end #end
#ifdef (LDXColor86) #ifndef (MJHMat86Slope) #declare MJHMat86Slope = LDXColor86; #end #end

// row 79 - Metallic_Dark_Grey
#ifdef (LDXColor87) #ifndef (MJHMat87) #declare MJHMat87 = LDXColor87; #end #end
#ifdef (LDXColor87) #ifndef (MJHMat87Slope) #declare MJHMat87Slope = LDXColor87; #end #end

// row 80 - Blue_Violet
#ifdef (LDXColor89) #ifndef (MJHMat89) #declare MJHMat89 = LDXColor89; #end #end
#ifdef (LDXColor89) #ifndef (MJHMat89Slope) #declare MJHMat89Slope = LDXColor89; #end #end

// row 81 - Flesh
#ifdef (LDXColor92) #ifndef (MJHMat92) #declare MJHMat92 = LDXColor92; #end #end
#ifdef (LDXColor92) #ifndef (MJHMat92Slope) #declare MJHMat92Slope = LDXColor92; #end #end

// row 82 - Light_Salmon
#ifdef (LDXColor100) #ifndef (MJHMat100) #declare MJHMat100 = LDXColor100; #end #end
#ifdef (LDXColor100) #ifndef (MJHMat100Slope) #declare MJHMat100Slope = LDXColor100; #end #end

// row 83 - Violet
#ifdef (LDXColor110) #ifndef (MJHMat110) #declare MJHMat110 = LDXColor110; #end #end
#ifdef (LDXColor110) #ifndef (MJHMat110Slope) #declare MJHMat110Slope = LDXColor110; #end #end

// row 84 - Medium_Violet
#ifdef (LDXColor112) #ifndef (MJHMat112) #declare MJHMat112 = LDXColor112; #end #end
#ifdef (LDXColor112) #ifndef (MJHMat112Slope) #declare MJHMat112Slope = LDXColor112; #end #end

// row 85 - Glitter_Trans_Dark_Pink
#ifdef (LDXColor114) #ifndef (MJHMat114) #declare MJHMat114 = LDXColor114; #end #end
#ifdef (LDXColor114) #ifndef (MJHMat114Slope) #declare MJHMat114Slope = LDXColor114; #end #end

// row 86 - Medium_Lime
#ifdef (LDXColor115) #ifndef (MJHMat115) #declare MJHMat115 = LDXColor115; #end #end
#ifdef (LDXColor115) #ifndef (MJHMat115Slope) #declare MJHMat115Slope = LDXColor115; #end #end

// row 87 - Glitter_Trans_Clear
#ifdef (LDXColor117) #ifndef (MJHMat117) #declare MJHMat117 = LDXColor117; #end #end
#ifdef (LDXColor117) #ifndef (MJHMat117Slope) #declare MJHMat117Slope = LDXColor117; #end #end

// row 88 - Aqua
#ifdef (LDXColor118) #ifndef (MJHMat118) #declare MJHMat118 = LDXColor118; #end #end
#ifdef (LDXColor118) #ifndef (MJHMat118Slope) #declare MJHMat118Slope = LDXColor118; #end #end

// row 89 - Light_Lime
#ifdef (LDXColor120) #ifndef (MJHMat120) #declare MJHMat120 = LDXColor120; #end #end
#ifdef (LDXColor120) #ifndef (MJHMat120Slope) #declare MJHMat120Slope = LDXColor120; #end #end

// row 90 - Light_Orange
#ifdef (LDXColor125) #ifndef (MJHMat125) #declare MJHMat125 = LDXColor125; #end #end
#ifdef (LDXColor125) #ifndef (MJHMat125Slope) #declare MJHMat125Slope = LDXColor125; #end #end

// row 91 - Dark_Nougat
#ifdef (LDXColor128) #ifndef (MJHMat128) #declare MJHMat128 = LDXColor128; #end #end
#ifdef (LDXColor128) #ifndef (MJHMat128Slope) #declare MJHMat128Slope = LDXColor128; #end #end

// row 92 - Glitter_Trans_Purple
#ifdef (LDXColor129) #ifndef (MJHMat129) #declare MJHMat129 = LDXColor129; #end #end
#ifdef (LDXColor129) #ifndef (MJHMat129Slope) #declare MJHMat129Slope = LDXColor129; #end #end

// row 93 - Speckle_Black_Silver
#ifdef (LDXColor132) #ifndef (MJHMat132) #declare MJHMat132 = LDXColor132; #end #end
#ifdef (LDXColor132) #ifndef (MJHMat132Slope) #declare MJHMat132Slope = LDXColor132; #end #end

// row 94 - Speckle_Black_Gold
#ifdef (LDXColor133) #ifndef (MJHMat133) #declare MJHMat133 = LDXColor133; #end #end
#ifdef (LDXColor133) #ifndef (MJHMat133Slope) #declare MJHMat133Slope = LDXColor133; #end #end

// row 95 - Copper
#ifdef (LDXColor134) #ifndef (MJHMat134) #declare MJHMat134 = LDXColor134; #end #end
#ifdef (LDXColor134) #ifndef (MJHMat134Slope) #declare MJHMat134Slope = LDXColor134; #end #end

// row 96 - Pearl_Light_Grey
#ifdef (LDXColor135) #ifndef (MJHMat135) #declare MJHMat135 = LDXColor135; #end #end
#ifdef (LDXColor135) #ifndef (MJHMat135Slope) #declare MJHMat135Slope = LDXColor135; #end #end

// row 97 - Metal_Blue
#ifdef (LDXColor137) #ifndef (MJHMat137) #declare MJHMat137 = LDXColor137; #end #end
#ifdef (LDXColor137) #ifndef (MJHMat137Slope) #declare MJHMat137Slope = LDXColor137; #end #end

// row 98 - Pearl_Light_Gold
#ifdef (LDXColor142) #ifndef (MJHMat142) #declare MJHMat142 = LDXColor142; #end #end
#ifdef (LDXColor142) #ifndef (MJHMat142Slope) #declare MJHMat142Slope = LDXColor142; #end #end

// row 99 - Pearl_Dark_Grey
#ifdef (LDXColor148) #ifndef (MJHMat148) #declare MJHMat148 = LDXColor148; #end #end
#ifdef (LDXColor148) #ifndef (MJHMat148Slope) #declare MJHMat148Slope = LDXColor148; #end #end

// row 100 - Pearl_Very_Light_Grey
#ifdef (LDXColor150) #ifndef (MJHMat150) #declare MJHMat150 = LDXColor150; #end #end
#ifdef (LDXColor150) #ifndef (MJHMat150Slope) #declare MJHMat150Slope = LDXColor150; #end #end

// row 101 - Very_Light_Bluish_Grey
#ifdef (LDXColor151) #ifndef (MJHMat151) #declare MJHMat151 = LDXColor151; #end #end
#ifdef (LDXColor151) #ifndef (MJHMat151Slope) #declare MJHMat151Slope = LDXColor151; #end #end

// row 102 - Flat_Dark_Gold
#ifdef (LDXColor178) #ifndef (MJHMat178) #declare MJHMat178 = LDXColor178; #end #end
#ifdef (LDXColor178) #ifndef (MJHMat178Slope) #declare MJHMat178Slope = LDXColor178; #end #end

// row 103 - Flat_Silver
#ifdef (LDXColor179) #ifndef (MJHMat179) #declare MJHMat179 = LDXColor179; #end #end
#ifdef (LDXColor179) #ifndef (MJHMat179Slope) #declare MJHMat179Slope = LDXColor179; #end #end

// row 104 - Pearl_White
#ifdef (LDXColor183) #ifndef (MJHMat183) #declare MJHMat183 = LDXColor183; #end #end
#ifdef (LDXColor183) #ifndef (MJHMat183Slope) #declare MJHMat183Slope = LDXColor183; #end #end

// row 105 - Metallic_Bright_Red
#ifdef (LDXColor184) #ifndef (MJHMat184) #declare MJHMat184 = LDXColor184; #end #end
#ifdef (LDXColor184) #ifndef (MJHMat184Slope) #declare MJHMat184Slope = LDXColor184; #end #end

// row 106 - Metallic_Dark_Green
#ifdef (LDXColor186) #ifndef (MJHMat186) #declare MJHMat186 = LDXColor186; #end #end
#ifdef (LDXColor186) #ifndef (MJHMat186Slope) #declare MJHMat186Slope = LDXColor186; #end #end

// row 107 - Reddish_Gold
#ifdef (LDXColor189) #ifndef (MJHMat189) #declare MJHMat189 = LDXColor189; #end #end
#ifdef (LDXColor189) #ifndef (MJHMat189Slope) #declare MJHMat189Slope = LDXColor189; #end #end

// row 108 - Bright_Light_Orange
#ifdef (LDXColor191) #ifndef (MJHMat191) #declare MJHMat191 = LDXColor191; #end #end
#ifdef (LDXColor191) #ifndef (MJHMat191Slope) #declare MJHMat191Slope = LDXColor191; #end #end

// row 109 - Bright_Light_Blue
#ifdef (LDXColor212) #ifndef (MJHMat212) #declare MJHMat212 = LDXColor212; #end #end
#ifdef (LDXColor212) #ifndef (MJHMat212Slope) #declare MJHMat212Slope = LDXColor212; #end #end

// row 110 - Rust
#ifdef (LDXColor216) #ifndef (MJHMat216) #declare MJHMat216 = LDXColor216; #end #end
#ifdef (LDXColor216) #ifndef (MJHMat216Slope) #declare MJHMat216Slope = LDXColor216; #end #end

// row 111 - Reddish_Lilac
#ifdef (LDXColor218) #ifndef (MJHMat218) #declare MJHMat218 = LDXColor218; #end #end
#ifdef (LDXColor218) #ifndef (MJHMat218Slope) #declare MJHMat218Slope = LDXColor218; #end #end

// row 112 - Lilac
#ifdef (LDXColor219) #ifndef (MJHMat219) #declare MJHMat219 = LDXColor219; #end #end
#ifdef (LDXColor219) #ifndef (MJHMat219Slope) #declare MJHMat219Slope = LDXColor219; #end #end

// row 113 - Bright_Light_Yellow
#ifdef (LDXColor226) #ifndef (MJHMat226) #declare MJHMat226 = LDXColor226; #end #end
#ifdef (LDXColor226) #ifndef (MJHMat226Slope) #declare MJHMat226Slope = LDXColor226; #end #end

// row 114 - Trans_Bright_Light_Orange
#ifdef (LDXColor231) #ifndef (MJHMat231) #declare MJHMat231 = LDXColor231; #end #end
#ifdef (LDXColor231) #ifndef (MJHMat231Slope) #declare MJHMat231Slope = LDXColor231; #end #end

// row 115 - Sky_Blue
#ifdef (LDXColor232) #ifndef (MJHMat232) #declare MJHMat232 = LDXColor232; #end #end
#ifdef (LDXColor232) #ifndef (MJHMat232Slope) #declare MJHMat232Slope = LDXColor232; #end #end

// row 116 - Trans_Fire_Yellow
#ifdef (LDXColor234) #ifndef (MJHMat234) #declare MJHMat234 = LDXColor234; #end #end
#ifdef (LDXColor234) #ifndef (MJHMat234Slope) #declare MJHMat234Slope = LDXColor234; #end #end

// row 117 - Rubber_Black
#ifdef (LDXColor256) #ifndef (MJHMat256) #declare MJHMat256 = LDXColor256; #end #end
#ifdef (LDXColor256) #ifndef (MJHMat256Slope) #declare MJHMat256Slope = LDXColor256; #end #end

// row 118 - Dark_Blue
#ifdef (LDXColor272) #ifndef (MJHMat272) #declare MJHMat272 = LDXColor272; #end #end
#ifdef (LDXColor272) #ifndef (MJHMat272Slope) #declare MJHMat272Slope = LDXColor272; #end #end

// row 119 - Rubber_Blue
#ifdef (LDXColor273) #ifndef (MJHMat273) #declare MJHMat273 = LDXColor273; #end #end
#ifdef (LDXColor273) #ifndef (MJHMat273Slope) #declare MJHMat273Slope = LDXColor273; #end #end

// row 120 - Trans_Reddish_Lilac
#ifdef (LDXColor284) #ifndef (MJHMat284) #declare MJHMat284 = LDXColor284; #end #end
#ifdef (LDXColor284) #ifndef (MJHMat284Slope) #declare MJHMat284Slope = LDXColor284; #end #end

// row 121 - Trans_Light_Green
#ifdef (LDXColor285) #ifndef (MJHMat285) #declare MJHMat285 = LDXColor285; #end #end
#ifdef (LDXColor285) #ifndef (MJHMat285Slope) #declare MJHMat285Slope = LDXColor285; #end #end

// row 122 - Dark_Green
#ifdef (LDXColor288) #ifndef (MJHMat288) #declare MJHMat288 = LDXColor288; #end #end
#ifdef (LDXColor288) #ifndef (MJHMat288Slope) #declare MJHMat288Slope = LDXColor288; #end #end

// row 123 - Trans_Light_Blue_Violet
#ifdef (LDXColor293) #ifndef (MJHMat293) #declare MJHMat293 = LDXColor293; #end #end
#ifdef (LDXColor293) #ifndef (MJHMat293Slope) #declare MJHMat293Slope = LDXColor293; #end #end

// row 124 - Glow_In_Dark_Trans
#ifdef (LDXColor294) #ifndef (MJHMat294) #declare MJHMat294 = LDXColor294; #end #end
#ifdef (LDXColor294) #ifndef (MJHMat294Slope) #declare MJHMat294Slope = LDXColor294; #end #end

// row 125 - Flamingo_Pink
#ifdef (LDXColor295) #ifndef (MJHMat295) #declare MJHMat295 = LDXColor295; #end #end
#ifdef (LDXColor295) #ifndef (MJHMat295Slope) #declare MJHMat295Slope = LDXColor295; #end #end

// row 126 - Pearl_Gold
#ifdef (LDXColor297) #ifndef (MJHMat297) #declare MJHMat297 = LDXColor297; #end #end
#ifdef (LDXColor297) #ifndef (MJHMat297Slope) #declare MJHMat297Slope = LDXColor297; #end #end

// row 127 - Metallic_Copper
#ifdef (LDXColor300) #ifndef (MJHMat300) #declare MJHMat300 = LDXColor300; #end #end
#ifdef (LDXColor300) #ifndef (MJHMat300Slope) #declare MJHMat300Slope = LDXColor300; #end #end

// row 128 - Glitter_Trans_Light_Blue
#ifdef (LDXColor302) #ifndef (MJHMat302) #declare MJHMat302 = LDXColor302; #end #end
#ifdef (LDXColor302) #ifndef (MJHMat302Slope) #declare MJHMat302Slope = LDXColor302; #end #end

// row 129 - Dark_Brown
#ifdef (LDXColor308) #ifndef (MJHMat308) #declare MJHMat308 = LDXColor308; #end #end
#ifdef (LDXColor308) #ifndef (MJHMat308Slope) #declare MJHMat308Slope = LDXColor308; #end #end

// row 130 - Maersk_Blue
#ifdef (LDXColor313) #ifndef (MJHMat313) #declare MJHMat313 = LDXColor313; #end #end
#ifdef (LDXColor313) #ifndef (MJHMat313Slope) #declare MJHMat313Slope = LDXColor313; #end #end

// row 131 - Dark_Red
#ifdef (LDXColor320) #ifndef (MJHMat320) #declare MJHMat320 = LDXColor320; #end #end
#ifdef (LDXColor320) #ifndef (MJHMat320Slope) #declare MJHMat320Slope = LDXColor320; #end #end

// row 132 - Dark_Azure
#ifdef (LDXColor321) #ifndef (MJHMat321) #declare MJHMat321 = LDXColor321; #end #end
#ifdef (LDXColor321) #ifndef (MJHMat321Slope) #declare MJHMat321Slope = LDXColor321; #end #end

// row 133 - Medium_Azure
#ifdef (LDXColor322) #ifndef (MJHMat322) #declare MJHMat322 = LDXColor322; #end #end
#ifdef (LDXColor322) #ifndef (MJHMat322Slope) #declare MJHMat322Slope = LDXColor322; #end #end

// row 134 - Light_Aqua
#ifdef (LDXColor323) #ifndef (MJHMat323) #declare MJHMat323 = LDXColor323; #end #end
#ifdef (LDXColor323) #ifndef (MJHMat323Slope) #declare MJHMat323Slope = LDXColor323; #end #end

// row 135 - Rubber_Red
#ifdef (LDXColor324) #ifndef (MJHMat324) #declare MJHMat324 = LDXColor324; #end #end
#ifdef (LDXColor324) #ifndef (MJHMat324Slope) #declare MJHMat324Slope = LDXColor324; #end #end

// row 136 - Yellowish_Green
#ifdef (LDXColor326) #ifndef (MJHMat326) #declare MJHMat326 = LDXColor326; #end #end
#ifdef (LDXColor326) #ifndef (MJHMat326Slope) #declare MJHMat326Slope = LDXColor326; #end #end

// row 137 - Glow_In_Dark_White
#ifdef (LDXColor329) #ifndef (MJHMat329) #declare MJHMat329 = LDXColor329; #end #end
#ifdef (LDXColor329) #ifndef (MJHMat329Slope) #declare MJHMat329Slope = LDXColor329; #end #end

// row 138 - Olive_Green
#ifdef (LDXColor330) #ifndef (MJHMat330) #declare MJHMat330 = LDXColor330; #end #end
#ifdef (LDXColor330) #ifndef (MJHMat330Slope) #declare MJHMat330Slope = LDXColor330; #end #end

// row 139 - Chrome_Gold
#ifdef (LDXColor334) #ifndef (MJHMat334) #declare MJHMat334 = LDXColor334; #end #end
#ifdef (LDXColor334) #ifndef (MJHMat334Slope) #declare MJHMat334Slope = LDXColor334; #end #end

// row 140 - Sand_Red
#ifdef (LDXColor335) #ifndef (MJHMat335) #declare MJHMat335 = LDXColor335; #end #end
#ifdef (LDXColor335) #ifndef (MJHMat335Slope) #declare MJHMat335Slope = LDXColor335; #end #end

// row 141 - Glitter_Trans_Neon_Green
#ifdef (LDXColor339) #ifndef (MJHMat339) #declare MJHMat339 = LDXColor339; #end #end
#ifdef (LDXColor339) #ifndef (MJHMat339Slope) #declare MJHMat339Slope = LDXColor339; #end #end

// row 142 - Rubber_Orange
#ifdef (LDXColor350) #ifndef (MJHMat350) #declare MJHMat350 = LDXColor350; #end #end
#ifdef (LDXColor350) #ifndef (MJHMat350Slope) #declare MJHMat350Slope = LDXColor350; #end #end

// row 143 - Medium_Dark_Pink
#ifdef (LDXColor351) #ifndef (MJHMat351) #declare MJHMat351 = LDXColor351; #end #end
#ifdef (LDXColor351) #ifndef (MJHMat351Slope) #declare MJHMat351Slope = LDXColor351; #end #end

// row 145 - Earth_Orange
#ifdef (LDXColor366) #ifndef (MJHMat366) #declare MJHMat366 = LDXColor366; #end #end
#ifdef (LDXColor366) #ifndef (MJHMat366Slope) #declare MJHMat366Slope = LDXColor366; #end #end

// row 146 - Sand_Purple
#ifdef (LDXColor373) #ifndef (MJHMat373) #declare MJHMat373 = LDXColor373; #end #end
#ifdef (LDXColor373) #ifndef (MJHMat373Slope) #declare MJHMat373Slope = LDXColor373; #end #end

// row 147 - Rubber_Light_Grey
#ifdef (LDXColor375) #ifndef (MJHMat375) #declare MJHMat375 = LDXColor375; #end #end
#ifdef (LDXColor375) #ifndef (MJHMat375Slope) #declare MJHMat375Slope = LDXColor375; #end #end

// row 148 - Sand_Green
#ifdef (LDXColor378) #ifndef (MJHMat378) #declare MJHMat378 = LDXColor378; #end #end
#ifdef (LDXColor378) #ifndef (MJHMat378Slope) #declare MJHMat378Slope = LDXColor378; #end #end

// row 149 - Sand_Blue
#ifdef (LDXColor379) #ifndef (MJHMat379) #declare MJHMat379 = LDXColor379; #end #end
#ifdef (LDXColor379) #ifndef (MJHMat379Slope) #declare MJHMat379Slope = LDXColor379; #end #end

// row 150 - Chrome_Silver
#ifdef (LDXColor383) #ifndef (MJHMat383) #declare MJHMat383 = LDXColor383; #end #end
#ifdef (LDXColor383) #ifndef (MJHMat383Slope) #declare MJHMat383Slope = LDXColor383; #end #end

// row 151 - Rubber_Dark_Blue
#ifdef (LDXColor406) #ifndef (MJHMat406) #declare MJHMat406 = LDXColor406; #end #end
#ifdef (LDXColor406) #ifndef (MJHMat406Slope) #declare MJHMat406Slope = LDXColor406; #end #end

// row 152 - Rubber_Purple
#ifdef (LDXColor449) #ifndef (MJHMat449) #declare MJHMat449 = LDXColor449; #end #end
#ifdef (LDXColor449) #ifndef (MJHMat449Slope) #declare MJHMat449Slope = LDXColor449; #end #end

// row 153 - Fabuland_Brown
#ifdef (LDXColor450) #ifndef (MJHMat450) #declare MJHMat450 = LDXColor450; #end #end
#ifdef (LDXColor450) #ifndef (MJHMat450Slope) #declare MJHMat450Slope = LDXColor450; #end #end

// row 154 - Medium_Orange
#ifdef (LDXColor462) #ifndef (MJHMat462) #declare MJHMat462 = LDXColor462; #end #end
#ifdef (LDXColor462) #ifndef (MJHMat462Slope) #declare MJHMat462Slope = LDXColor462; #end #end

// row 155 - Dark_Orange
#ifdef (LDXColor484) #ifndef (MJHMat484) #declare MJHMat484 = LDXColor484; #end #end
#ifdef (LDXColor484) #ifndef (MJHMat484Slope) #declare MJHMat484Slope = LDXColor484; #end #end

// row 156 - Rubber_Lime
#ifdef (LDXColor490) #ifndef (MJHMat490) #declare MJHMat490 = LDXColor490; #end #end
#ifdef (LDXColor490) #ifndef (MJHMat490Slope) #declare MJHMat490Slope = LDXColor490; #end #end

// row 157 - Magnet
#ifdef (LDXColor493) #ifndef (MJHMat493) #declare MJHMat493 = LDXColor493; #end #end
#ifdef (LDXColor493) #ifndef (MJHMat493Slope) #declare MJHMat493Slope = LDXColor493; #end #end

// row 158 - Electric_Contact_Alloy
#ifdef (LDXColor494) #ifndef (MJHMat494) #declare MJHMat494 = LDXColor494; #end #end
#ifdef (LDXColor494) #ifndef (MJHMat494Slope) #declare MJHMat494Slope = LDXColor494; #end #end

// row 159 - Electric_Contact_Copper
#ifdef (LDXColor495) #ifndef (MJHMat495) #declare MJHMat495 = LDXColor495; #end #end
#ifdef (LDXColor495) #ifndef (MJHMat495Slope) #declare MJHMat495Slope = LDXColor495; #end #end

// row 160 - Rubber_Light_Bluish_Grey
#ifdef (LDXColor496) #ifndef (MJHMat496) #declare MJHMat496 = LDXColor496; #end #end
#ifdef (LDXColor496) #ifndef (MJHMat496Slope) #declare MJHMat496Slope = LDXColor496; #end #end

// row 161 - Very_Light_Grey
#ifdef (LDXColor503) #ifndef (MJHMat503) #declare MJHMat503 = LDXColor503; #end #end
#ifdef (LDXColor503) #ifndef (MJHMat503Slope) #declare MJHMat503Slope = LDXColor503; #end #end

// row 162 - Rubber_Flat_Silver
#ifdef (LDXColor504) #ifndef (MJHMat504) #declare MJHMat504 = LDXColor504; #end #end
#ifdef (LDXColor504) #ifndef (MJHMat504Slope) #declare MJHMat504Slope = LDXColor504; #end #end

// row 166 - Rubber_White
#ifdef (LDXColor511) #ifndef (MJHMat511) #declare MJHMat511 = LDXColor511; #end #end
#ifdef (LDXColor511) #ifndef (MJHMat511Slope) #declare MJHMat511Slope = LDXColor511; #end #end
