// POV-Ray scripts for LDraw models and scenes
// Copyright (C) 2019  Michael Horvath
// 
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
// 
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA


// row 1 - Black
#declare MJHTex0 = texture {}
#declare MJHTex0Slope = texture {}
#declare MJHMat0 = material {}
#declare MJHMat0Slope = material {}

// row 2 - Blue
#declare MJHTex1 = texture {}
#declare MJHTex1Slope = texture {}
#declare MJHMat1 = material {}
#declare MJHMat1Slope = material {}

// row 3 - Green
#declare MJHTex2 = texture {}
#declare MJHTex2Slope = texture {}
#declare MJHMat2 = material {}
#declare MJHMat2Slope = material {}

// row 4 - Dark_Turquoise
#declare MJHTex3 = texture {}
#declare MJHTex3Slope = texture {}
#declare MJHMat3 = material {}
#declare MJHMat3Slope = material {}

// row 5 - Red
#declare MJHTex4 = texture {}
#declare MJHTex4Slope = texture {}
#declare MJHMat4 = material {}
#declare MJHMat4Slope = material {}

// row 6 - Dark_Pink
#declare MJHTex5 = texture {}
#declare MJHTex5Slope = texture {}
#declare MJHMat5 = material {}
#declare MJHMat5Slope = material {}

// row 7 - Brown
#declare MJHTex6 = texture {}
#declare MJHTex6Slope = texture {}
#declare MJHMat6 = material {}
#declare MJHMat6Slope = material {}

// row 8 - Light_Grey
#declare MJHTex7 = texture {}
#declare MJHTex7Slope = texture {}
#declare MJHMat7 = material {}
#declare MJHMat7Slope = material {}

// row 9 - Dark_Grey
#declare MJHTex8 = texture {}
#declare MJHTex8Slope = texture {}
#declare MJHMat8 = material {}
#declare MJHMat8Slope = material {}

// row 10 - Light_Blue
#declare MJHTex9 = texture {}
#declare MJHTex9Slope = texture {}
#declare MJHMat9 = material {}
#declare MJHMat9Slope = material {}

// row 11 - Bright_Green
#declare MJHTex10 = texture {}
#declare MJHTex10Slope = texture {}
#declare MJHMat10 = material {}
#declare MJHMat10Slope = material {}

// row 12 - Light_Turquoise
#declare MJHTex11 = texture {}
#declare MJHTex11Slope = texture {}
#declare MJHMat11 = material {}
#declare MJHMat11Slope = material {}

// row 13 - Salmon
#declare MJHTex12 = texture {}
#declare MJHTex12Slope = texture {}
#declare MJHMat12 = material {}
#declare MJHMat12Slope = material {}

// row 14 - Pink
#declare MJHTex13 = texture {}
#declare MJHTex13Slope = texture {}
#declare MJHMat13 = material {}
#declare MJHMat13Slope = material {}

// row 15 - Yellow
#declare MJHTex14 = texture {}
#declare MJHTex14Slope = texture {}
#declare MJHMat14 = material {}
#declare MJHMat14Slope = material {}

// row 16 - White
#declare MJHTex15 = texture {}
#declare MJHTex15Slope = texture {}
#declare MJHMat15 = material {}
#declare MJHMat15Slope = material {}

// row 17 - Main_Colour
#declare MJHTex16 = texture {}
#declare MJHTex16Slope = texture {}
#declare MJHMat16 = material {}
#declare MJHMat16Slope = material {}

// row 18 - Light_Green
#declare MJHTex17 = texture {}
#declare MJHTex17Slope = texture {}
#declare MJHMat17 = material {}
#declare MJHMat17Slope = material {}

// row 19 - Light_Yellow
#declare MJHTex18 = texture {}
#declare MJHTex18Slope = texture {}
#declare MJHMat18 = material {}
#declare MJHMat18Slope = material {}

// row 20 - Tan
#declare MJHTex19 = texture {}
#declare MJHTex19Slope = texture {}
#declare MJHMat19 = material {}
#declare MJHMat19Slope = material {}

// row 21 - Light_Violet
#declare MJHTex20 = texture {}
#declare MJHTex20Slope = texture {}
#declare MJHMat20 = material {}
#declare MJHMat20Slope = material {}

// row 22 - Glow_In_Dark_Opaque
#declare MJHTex21 = texture {}
#declare MJHTex21Slope = texture {}
#declare MJHMat21 = material {}
#declare MJHMat21Slope = material {}

// row 23 - Purple
#declare MJHTex22 = texture {}
#declare MJHTex22Slope = texture {}
#declare MJHMat22 = material {}
#declare MJHMat22Slope = material {}

// row 24 - Dark_Blue_Violet
#declare MJHTex23 = texture {}
#declare MJHTex23Slope = texture {}
#declare MJHMat23 = material {}
#declare MJHMat23Slope = material {}

// row 25 - Edge_Colour
#declare MJHTex24 = texture {}
#declare MJHTex24Slope = texture {}
#declare MJHMat24 = material {}
#declare MJHMat24Slope = material {}

// row 26 - Orange
#declare MJHTex25 = texture {}
#declare MJHTex25Slope = texture {}
#declare MJHMat25 = material {}
#declare MJHMat25Slope = material {}

// row 27 - Magenta
#declare MJHTex26 = texture {}
#declare MJHTex26Slope = texture {}
#declare MJHMat26 = material {}
#declare MJHMat26Slope = material {}

// row 28 - Lime
#declare MJHTex27 = texture {}
#declare MJHTex27Slope = texture {}
#declare MJHMat27 = material {}
#declare MJHMat27Slope = material {}

// row 29 - Dark_Tan
#declare MJHTex28 = texture {}
#declare MJHTex28Slope = texture {}
#declare MJHMat28 = material {}
#declare MJHMat28Slope = material {}

// row 30 - Bright_Pink
#declare MJHTex29 = texture {}
#declare MJHTex29Slope = texture {}
#declare MJHMat29 = material {}
#declare MJHMat29Slope = material {}

// row 31 - Medium_Lavender
#declare MJHTex30 = texture {}
#declare MJHTex30Slope = texture {}
#declare MJHMat30 = material {}
#declare MJHMat30Slope = material {}

// row 32 - Lavender
#declare MJHTex31 = texture {}
#declare MJHTex31Slope = texture {}
#declare MJHMat31 = material {}
#declare MJHMat31Slope = material {}

// row 33 - Trans_Black_IR_Lens
#declare MJHTex32 = texture {}
#declare MJHTex32Slope = texture {}
#declare MJHMat32 = material {}
#declare MJHMat32Slope = material {}

// row 34 - Trans_Dark_Blue
#declare MJHTex33 = texture {}
#declare MJHTex33Slope = texture {}
#declare MJHMat33 = material {}
#declare MJHMat33Slope = material {}

// row 35 - Trans_Green
#declare MJHTex34 = texture {}
#declare MJHTex34Slope = texture {}
#declare MJHMat34 = material {}
#declare MJHMat34Slope = material {}

// row 36 - Trans_Bright_Green
#declare MJHTex35 = texture {}
#declare MJHTex35Slope = texture {}
#declare MJHMat35 = material {}
#declare MJHMat35Slope = material {}

// row 37 - Trans_Red
#declare MJHTex36 = texture {}
#declare MJHTex36Slope = texture {}
#declare MJHMat36 = material {}
#declare MJHMat36Slope = material {}

// row 38 - Trans_Dark_Pink
#declare MJHTex37 = texture {}
#declare MJHTex37Slope = texture {}
#declare MJHMat37 = material {}
#declare MJHMat37Slope = material {}

// row 39 - Trans_Neon_Orange
#declare MJHTex38 = texture {}
#declare MJHTex38Slope = texture {}
#declare MJHMat38 = material {}
#declare MJHMat38Slope = material {}

// row 40 - Trans_Very_Light_Blue
#declare MJHTex39 = texture {}
#declare MJHTex39Slope = texture {}
#declare MJHMat39 = material {}
#declare MJHMat39Slope = material {}

// row 41 - Trans_Black
#declare MJHTex40 = texture {}
#declare MJHTex40Slope = texture {}
#declare MJHMat40 = material {}
#declare MJHMat40Slope = material {}

// row 42 - Trans_Medium_Blue
#declare MJHTex41 = texture {}
#declare MJHTex41Slope = texture {}
#declare MJHMat41 = material {}
#declare MJHMat41Slope = material {}

// row 43 - Trans_Neon_Green
#declare MJHTex42 = texture {}
#declare MJHTex42Slope = texture {}
#declare MJHMat42 = material {}
#declare MJHMat42Slope = material {}

// row 44 - Trans_Light_Blue
#declare MJHTex43 = texture {}
#declare MJHTex43Slope = texture {}
#declare MJHMat43 = material {}
#declare MJHMat43Slope = material {}

// row 45 - Trans_Bright_Reddish_Lilac
#declare MJHTex44 = texture {}
#declare MJHTex44Slope = texture {}
#declare MJHMat44 = material {}
#declare MJHMat44Slope = material {}

// row 46 - Trans_Pink
#declare MJHTex45 = texture {}
#declare MJHTex45Slope = texture {}
#declare MJHMat45 = material {}
#declare MJHMat45Slope = material {}

// row 47 - Trans_Yellow
#declare MJHTex46 = texture {}
#declare MJHTex46Slope = texture {}
#declare MJHMat46 = material {}
#declare MJHMat46Slope = material {}

// row 48 - Trans_Clear
#declare MJHTex47 = texture {}
#declare MJHTex47Slope = texture {}
#declare MJHMat47 = material {}
#declare MJHMat47Slope = material {}

// row 49 - Trans_Purple
#declare MJHTex52 = texture {}
#declare MJHTex52Slope = texture {}
#declare MJHMat52 = material {}
#declare MJHMat52Slope = material {}

// row 50 - Trans_Neon_Yellow
#declare MJHTex54 = texture {}
#declare MJHTex54Slope = texture {}
#declare MJHMat54 = material {}
#declare MJHMat54Slope = material {}

// row 51 - Trans_Orange
#declare MJHTex57 = texture {}
#declare MJHTex57Slope = texture {}
#declare MJHMat57 = material {}
#declare MJHMat57Slope = material {}

// row 52 - Chrome_Antique_Brass
#declare MJHTex60 = texture {}
#declare MJHTex60Slope = texture {}
#declare MJHMat60 = material {}
#declare MJHMat60Slope = material {}

// row 53 - Chrome_Blue
#declare MJHTex61 = texture {}
#declare MJHTex61Slope = texture {}
#declare MJHMat61 = material {}
#declare MJHMat61Slope = material {}

// row 54 - Chrome_Green
#declare MJHTex62 = texture {}
#declare MJHTex62Slope = texture {}
#declare MJHMat62 = material {}
#declare MJHMat62Slope = material {}

// row 55 - Chrome_Pink
#declare MJHTex63 = texture {}
#declare MJHTex63Slope = texture {}
#declare MJHMat63 = material {}
#declare MJHMat63Slope = material {}

// row 56 - Chrome_Black
#declare MJHTex64 = texture {}
#declare MJHTex64Slope = texture {}
#declare MJHMat64 = material {}
#declare MJHMat64Slope = material {}

// row 57 - Rubber_Yellow
#declare MJHTex65 = texture {}
#declare MJHTex65Slope = texture {}
#declare MJHMat65 = material {}
#declare MJHMat65Slope = material {}

// row 58 - Rubber_Trans_Yellow
#declare MJHTex66 = texture {}
#declare MJHTex66Slope = texture {}
#declare MJHMat66 = material {}
#declare MJHMat66Slope = material {}

// row 59 - Rubber_Trans_Clear
#declare MJHTex67 = texture {}
#declare MJHTex67Slope = texture {}
#declare MJHMat67 = material {}
#declare MJHMat67Slope = material {}

// row 60 - Very_Light_Orange
#declare MJHTex68 = texture {}
#declare MJHTex68Slope = texture {}
#declare MJHMat68 = material {}
#declare MJHMat68Slope = material {}

// row 61 - Bright_Reddish_Lilac
#declare MJHTex69 = texture {}
#declare MJHTex69Slope = texture {}
#declare MJHMat69 = material {}
#declare MJHMat69Slope = material {}

// row 62 - Reddish_Brown
#declare MJHTex70 = texture {}
#declare MJHTex70Slope = texture {}
#declare MJHMat70 = material {}
#declare MJHMat70Slope = material {}

// row 63 - Light_Bluish_Grey
#declare MJHTex71 = texture {}
#declare MJHTex71Slope = texture {}
#declare MJHMat71 = material {}
#declare MJHMat71Slope = material {}

// row 64 - Dark_Bluish_Grey
#declare MJHTex72 = texture {}
#declare MJHTex72Slope = texture {}
#declare MJHMat72 = material {}
#declare MJHMat72Slope = material {}

// row 65 - Medium_Blue
#declare MJHTex73 = texture {}
#declare MJHTex73Slope = texture {}
#declare MJHMat73 = material {}
#declare MJHMat73Slope = material {}

// row 66 - Medium_Green
#declare MJHTex74 = texture {}
#declare MJHTex74Slope = texture {}
#declare MJHMat74 = material {}
#declare MJHMat74Slope = material {}

// row 67 - Speckle_Black_Copper
#declare MJHTex75 = texture {}
#declare MJHTex75Slope = texture {}
#declare MJHMat75 = material {}
#declare MJHMat75Slope = material {}

// row 68 - Speckle_Dark_Bluish_Grey_Silver
#declare MJHTex76 = texture {}
#declare MJHTex76Slope = texture {}
#declare MJHMat76 = material {}
#declare MJHMat76Slope = material {}

// row 69 - Light_Pink
#declare MJHTex77 = texture {}
#declare MJHTex77Slope = texture {}
#declare MJHMat77 = material {}
#declare MJHMat77Slope = material {}

// row 70 - Light_Flesh
#declare MJHTex78 = texture {}
#declare MJHTex78Slope = texture {}
#declare MJHMat78 = material {}
#declare MJHMat78Slope = material {}

// row 71 - Milky_White
#declare MJHTex79 = texture {}
#declare MJHTex79Slope = texture {}
#declare MJHMat79 = material {}
#declare MJHMat79Slope = material {}

// row 72 - Metallic_Silver
#declare MJHTex80 = texture {}
#declare MJHTex80Slope = texture {}
#declare MJHMat80 = material {}
#declare MJHMat80Slope = material {}

// row 73 - Metallic_Green
#declare MJHTex81 = texture {}
#declare MJHTex81Slope = texture {}
#declare MJHMat81 = material {}
#declare MJHMat81Slope = material {}

// row 74 - Metallic_Gold
#declare MJHTex82 = texture {}
#declare MJHTex82Slope = texture {}
#declare MJHMat82 = material {}
#declare MJHMat82Slope = material {}

// row 75 - Metallic_Black
#declare MJHTex83 = texture {}
#declare MJHTex83Slope = texture {}
#declare MJHMat83 = material {}
#declare MJHMat83Slope = material {}

// row 76 - Medium_Dark_Flesh
#declare MJHTex84 = texture {}
#declare MJHTex84Slope = texture {}
#declare MJHMat84 = material {}
#declare MJHMat84Slope = material {}

// row 77 - Medium_Lilac
#declare MJHTex85 = texture {}
#declare MJHTex85Slope = texture {}
#declare MJHMat85 = material {}
#declare MJHMat85Slope = material {}

// row 78 - Dark_Flesh
#declare MJHTex86 = texture {}
#declare MJHTex86Slope = texture {}
#declare MJHMat86 = material {}
#declare MJHMat86Slope = material {}

// row 79 - Metallic_Dark_Grey
#declare MJHTex87 = texture {}
#declare MJHTex87Slope = texture {}
#declare MJHMat87 = material {}
#declare MJHMat87Slope = material {}

// row 80 - Blue_Violet
#declare MJHTex89 = texture {}
#declare MJHTex89Slope = texture {}
#declare MJHMat89 = material {}
#declare MJHMat89Slope = material {}

// row 81 - Flesh
#declare MJHTex92 = texture {}
#declare MJHTex92Slope = texture {}
#declare MJHMat92 = material {}
#declare MJHMat92Slope = material {}

// row 82 - Light_Salmon
#declare MJHTex100 = texture {}
#declare MJHTex100Slope = texture {}
#declare MJHMat100 = material {}
#declare MJHMat100Slope = material {}

// row 83 - Violet
#declare MJHTex110 = texture {}
#declare MJHTex110Slope = texture {}
#declare MJHMat110 = material {}
#declare MJHMat110Slope = material {}

// row 84 - Medium_Violet
#declare MJHTex112 = texture {}
#declare MJHTex112Slope = texture {}
#declare MJHMat112 = material {}
#declare MJHMat112Slope = material {}

// row 85 - Glitter_Trans_Dark_Pink
#declare MJHTex114 = texture {}
#declare MJHTex114Slope = texture {}
#declare MJHMat114 = material {}
#declare MJHMat114Slope = material {}

// row 86 - Medium_Lime
#declare MJHTex115 = texture {}
#declare MJHTex115Slope = texture {}
#declare MJHMat115 = material {}
#declare MJHMat115Slope = material {}

// row 87 - Glitter_Trans_Clear
#declare MJHTex117 = texture {}
#declare MJHTex117Slope = texture {}
#declare MJHMat117 = material {}
#declare MJHMat117Slope = material {}

// row 88 - Aqua
#declare MJHTex118 = texture {}
#declare MJHTex118Slope = texture {}
#declare MJHMat118 = material {}
#declare MJHMat118Slope = material {}

// row 89 - Light_Lime
#declare MJHTex120 = texture {}
#declare MJHTex120Slope = texture {}
#declare MJHMat120 = material {}
#declare MJHMat120Slope = material {}

// row 90 - Light_Orange
#declare MJHTex125 = texture {}
#declare MJHTex125Slope = texture {}
#declare MJHMat125 = material {}
#declare MJHMat125Slope = material {}

// row 91 - Dark_Nougat
#declare MJHTex128 = texture {}
#declare MJHTex128Slope = texture {}
#declare MJHMat128 = material {}
#declare MJHMat128Slope = material {}

// row 92 - Glitter_Trans_Purple
#declare MJHTex129 = texture {}
#declare MJHTex129Slope = texture {}
#declare MJHMat129 = material {}
#declare MJHMat129Slope = material {}

// row 93 - Speckle_Black_Silver
#declare MJHTex132 = texture {}
#declare MJHTex132Slope = texture {}
#declare MJHMat132 = material {}
#declare MJHMat132Slope = material {}

// row 94 - Speckle_Black_Gold
#declare MJHTex133 = texture {}
#declare MJHTex133Slope = texture {}
#declare MJHMat133 = material {}
#declare MJHMat133Slope = material {}

// row 95 - Copper
#declare MJHTex134 = texture {}
#declare MJHTex134Slope = texture {}
#declare MJHMat134 = material {}
#declare MJHMat134Slope = material {}

// row 96 - Pearl_Light_Grey
#declare MJHTex135 = texture {}
#declare MJHTex135Slope = texture {}
#declare MJHMat135 = material {}
#declare MJHMat135Slope = material {}

// row 97 - Metal_Blue
#declare MJHTex137 = texture {}
#declare MJHTex137Slope = texture {}
#declare MJHMat137 = material {}
#declare MJHMat137Slope = material {}

// row 98 - Pearl_Light_Gold
#declare MJHTex142 = texture {}
#declare MJHTex142Slope = texture {}
#declare MJHMat142 = material {}
#declare MJHMat142Slope = material {}

// row 99 - Pearl_Dark_Grey
#declare MJHTex148 = texture {}
#declare MJHTex148Slope = texture {}
#declare MJHMat148 = material {}
#declare MJHMat148Slope = material {}

// row 100 - Pearl_Very_Light_Grey
#declare MJHTex150 = texture {}
#declare MJHTex150Slope = texture {}
#declare MJHMat150 = material {}
#declare MJHMat150Slope = material {}

// row 101 - Very_Light_Bluish_Grey
#declare MJHTex151 = texture {}
#declare MJHTex151Slope = texture {}
#declare MJHMat151 = material {}
#declare MJHMat151Slope = material {}

// row 102 - Flat_Dark_Gold
#declare MJHTex178 = texture {}
#declare MJHTex178Slope = texture {}
#declare MJHMat178 = material {}
#declare MJHMat178Slope = material {}

// row 103 - Flat_Silver
#declare MJHTex179 = texture {}
#declare MJHTex179Slope = texture {}
#declare MJHMat179 = material {}
#declare MJHMat179Slope = material {}

// row 104 - Pearl_White
#declare MJHTex183 = texture {}
#declare MJHTex183Slope = texture {}
#declare MJHMat183 = material {}
#declare MJHMat183Slope = material {}

// row 105 - Metallic_Bright_Red
#declare MJHTex184 = texture {}
#declare MJHTex184Slope = texture {}
#declare MJHMat184 = material {}
#declare MJHMat184Slope = material {}

// row 106 - Metallic_Dark_Green
#declare MJHTex186 = texture {}
#declare MJHTex186Slope = texture {}
#declare MJHMat186 = material {}
#declare MJHMat186Slope = material {}

// row 107 - Reddish_Gold
#declare MJHTex189 = texture {}
#declare MJHTex189Slope = texture {}
#declare MJHMat189 = material {}
#declare MJHMat189Slope = material {}

// row 108 - Bright_Light_Orange
#declare MJHTex191 = texture {}
#declare MJHTex191Slope = texture {}
#declare MJHMat191 = material {}
#declare MJHMat191Slope = material {}

// row 109 - Bright_Light_Blue
#declare MJHTex212 = texture {}
#declare MJHTex212Slope = texture {}
#declare MJHMat212 = material {}
#declare MJHMat212Slope = material {}

// row 110 - Rust
#declare MJHTex216 = texture {}
#declare MJHTex216Slope = texture {}
#declare MJHMat216 = material {}
#declare MJHMat216Slope = material {}

// row 111 - Reddish_Lilac
#declare MJHTex218 = texture {}
#declare MJHTex218Slope = texture {}
#declare MJHMat218 = material {}
#declare MJHMat218Slope = material {}

// row 112 - Lilac
#declare MJHTex219 = texture {}
#declare MJHTex219Slope = texture {}
#declare MJHMat219 = material {}
#declare MJHMat219Slope = material {}

// row 113 - Bright_Light_Yellow
#declare MJHTex226 = texture {}
#declare MJHTex226Slope = texture {}
#declare MJHMat226 = material {}
#declare MJHMat226Slope = material {}

// row 114 - Trans_Bright_Light_Orange
#declare MJHTex231 = texture {}
#declare MJHTex231Slope = texture {}
#declare MJHMat231 = material {}
#declare MJHMat231Slope = material {}

// row 115 - Sky_Blue
#declare MJHTex232 = texture {}
#declare MJHTex232Slope = texture {}
#declare MJHMat232 = material {}
#declare MJHMat232Slope = material {}

// row 116 - Trans_Fire_Yellow
#declare MJHTex234 = texture {}
#declare MJHTex234Slope = texture {}
#declare MJHMat234 = material {}
#declare MJHMat234Slope = material {}

// row 117 - Rubber_Black
#declare MJHTex256 = texture {}
#declare MJHTex256Slope = texture {}
#declare MJHMat256 = material {}
#declare MJHMat256Slope = material {}

// row 118 - Dark_Blue
#declare MJHTex272 = texture {}
#declare MJHTex272Slope = texture {}
#declare MJHMat272 = material {}
#declare MJHMat272Slope = material {}

// row 119 - Rubber_Blue
#declare MJHTex273 = texture {}
#declare MJHTex273Slope = texture {}
#declare MJHMat273 = material {}
#declare MJHMat273Slope = material {}

// row 120 - Trans_Reddish_Lilac
#declare MJHTex284 = texture {}
#declare MJHTex284Slope = texture {}
#declare MJHMat284 = material {}
#declare MJHMat284Slope = material {}

// row 121 - Trans_Light_Green
#declare MJHTex285 = texture {}
#declare MJHTex285Slope = texture {}
#declare MJHMat285 = material {}
#declare MJHMat285Slope = material {}

// row 122 - Dark_Green
#declare MJHTex288 = texture {}
#declare MJHTex288Slope = texture {}
#declare MJHMat288 = material {}
#declare MJHMat288Slope = material {}

// row 123 - Trans_Light_Blue_Violet
#declare MJHTex293 = texture {}
#declare MJHTex293Slope = texture {}
#declare MJHMat293 = material {}
#declare MJHMat293Slope = material {}

// row 124 - Glow_In_Dark_Trans
#declare MJHTex294 = texture {}
#declare MJHTex294Slope = texture {}
#declare MJHMat294 = material {}
#declare MJHMat294Slope = material {}

// row 125 - Flamingo_Pink
#declare MJHTex295 = texture {}
#declare MJHTex295Slope = texture {}
#declare MJHMat295 = material {}
#declare MJHMat295Slope = material {}

// row 126 - Pearl_Gold
#declare MJHTex297 = texture {}
#declare MJHTex297Slope = texture {}
#declare MJHMat297 = material {}
#declare MJHMat297Slope = material {}

// row 127 - Metallic_Copper
#declare MJHTex300 = texture {}
#declare MJHTex300Slope = texture {}
#declare MJHMat300 = material {}
#declare MJHMat300Slope = material {}

// row 128 - Glitter_Trans_Light_Blue
#declare MJHTex302 = texture {}
#declare MJHTex302Slope = texture {}
#declare MJHMat302 = material {}
#declare MJHMat302Slope = material {}

// row 129 - Dark_Brown
#declare MJHTex308 = texture {}
#declare MJHTex308Slope = texture {}
#declare MJHMat308 = material {}
#declare MJHMat308Slope = material {}

// row 130 - Maersk_Blue
#declare MJHTex313 = texture {}
#declare MJHTex313Slope = texture {}
#declare MJHMat313 = material {}
#declare MJHMat313Slope = material {}

// row 131 - Dark_Red
#declare MJHTex320 = texture {}
#declare MJHTex320Slope = texture {}
#declare MJHMat320 = material {}
#declare MJHMat320Slope = material {}

// row 132 - Dark_Azure
#declare MJHTex321 = texture {}
#declare MJHTex321Slope = texture {}
#declare MJHMat321 = material {}
#declare MJHMat321Slope = material {}

// row 133 - Medium_Azure
#declare MJHTex322 = texture {}
#declare MJHTex322Slope = texture {}
#declare MJHMat322 = material {}
#declare MJHMat322Slope = material {}

// row 134 - Light_Aqua
#declare MJHTex323 = texture {}
#declare MJHTex323Slope = texture {}
#declare MJHMat323 = material {}
#declare MJHMat323Slope = material {}

// row 135 - Rubber_Red
#declare MJHTex324 = texture {}
#declare MJHTex324Slope = texture {}
#declare MJHMat324 = material {}
#declare MJHMat324Slope = material {}

// row 136 - Yellowish_Green
#declare MJHTex326 = texture {}
#declare MJHTex326Slope = texture {}
#declare MJHMat326 = material {}
#declare MJHMat326Slope = material {}

// row 137 - Glow_In_Dark_White
#declare MJHTex329 = texture {}
#declare MJHTex329Slope = texture {}
#declare MJHMat329 = material {}
#declare MJHMat329Slope = material {}

// row 138 - Olive_Green
#declare MJHTex330 = texture {}
#declare MJHTex330Slope = texture {}
#declare MJHMat330 = material {}
#declare MJHMat330Slope = material {}

// row 139 - Chrome_Gold
#declare MJHTex334 = texture {}
#declare MJHTex334Slope = texture {}
#declare MJHMat334 = material {}
#declare MJHMat334Slope = material {}

// row 140 - Sand_Red
#declare MJHTex335 = texture {}
#declare MJHTex335Slope = texture {}
#declare MJHMat335 = material {}
#declare MJHMat335Slope = material {}

// row 141 - Glitter_Trans_Neon_Green
#declare MJHTex339 = texture {}
#declare MJHTex339Slope = texture {}
#declare MJHMat339 = material {}
#declare MJHMat339Slope = material {}

// row 142 - Rubber_Orange
#declare MJHTex350 = texture {}
#declare MJHTex350Slope = texture {}
#declare MJHMat350 = material {}
#declare MJHMat350Slope = material {}

// row 143 - Medium_Dark_Pink
#declare MJHTex351 = texture {}
#declare MJHTex351Slope = texture {}
#declare MJHMat351 = material {}
#declare MJHMat351Slope = material {}

// row 145 - Earth_Orange
#declare MJHTex366 = texture {}
#declare MJHTex366Slope = texture {}
#declare MJHMat366 = material {}
#declare MJHMat366Slope = material {}

// row 146 - Sand_Purple
#declare MJHTex373 = texture {}
#declare MJHTex373Slope = texture {}
#declare MJHMat373 = material {}
#declare MJHMat373Slope = material {}

// row 147 - Rubber_Light_Grey
#declare MJHTex375 = texture {}
#declare MJHTex375Slope = texture {}
#declare MJHMat375 = material {}
#declare MJHMat375Slope = material {}

// row 148 - Sand_Green
#declare MJHTex378 = texture {}
#declare MJHTex378Slope = texture {}
#declare MJHMat378 = material {}
#declare MJHMat378Slope = material {}

// row 149 - Sand_Blue
#declare MJHTex379 = texture {}
#declare MJHTex379Slope = texture {}
#declare MJHMat379 = material {}
#declare MJHMat379Slope = material {}

// row 150 - Chrome_Silver
#declare MJHTex383 = texture {}
#declare MJHTex383Slope = texture {}
#declare MJHMat383 = material {}
#declare MJHMat383Slope = material {}

// row 151 - Rubber_Dark_Blue
#declare MJHTex406 = texture {}
#declare MJHTex406Slope = texture {}
#declare MJHMat406 = material {}
#declare MJHMat406Slope = material {}

// row 152 - Rubber_Purple
#declare MJHTex449 = texture {}
#declare MJHTex449Slope = texture {}
#declare MJHMat449 = material {}
#declare MJHMat449Slope = material {}

// row 153 - Fabuland_Brown
#declare MJHTex450 = texture {}
#declare MJHTex450Slope = texture {}
#declare MJHMat450 = material {}
#declare MJHMat450Slope = material {}

// row 154 - Medium_Orange
#declare MJHTex462 = texture {}
#declare MJHTex462Slope = texture {}
#declare MJHMat462 = material {}
#declare MJHMat462Slope = material {}

// row 155 - Dark_Orange
#declare MJHTex484 = texture {}
#declare MJHTex484Slope = texture {}
#declare MJHMat484 = material {}
#declare MJHMat484Slope = material {}

// row 156 - Rubber_Lime
#declare MJHTex490 = texture {}
#declare MJHTex490Slope = texture {}
#declare MJHMat490 = material {}
#declare MJHMat490Slope = material {}

// row 157 - Magnet
#declare MJHTex493 = texture {}
#declare MJHTex493Slope = texture {}
#declare MJHMat493 = material {}
#declare MJHMat493Slope = material {}

// row 158 - Electric_Contact_Alloy
#declare MJHTex494 = texture {}
#declare MJHTex494Slope = texture {}
#declare MJHMat494 = material {}
#declare MJHMat494Slope = material {}

// row 159 - Electric_Contact_Copper
#declare MJHTex495 = texture {}
#declare MJHTex495Slope = texture {}
#declare MJHMat495 = material {}
#declare MJHMat495Slope = material {}

// row 160 - Rubber_Light_Bluish_Grey
#declare MJHTex496 = texture {}
#declare MJHTex496Slope = texture {}
#declare MJHMat496 = material {}
#declare MJHMat496Slope = material {}

// row 161 - Very_Light_Grey
#declare MJHTex503 = texture {}
#declare MJHTex503Slope = texture {}
#declare MJHMat503 = material {}
#declare MJHMat503Slope = material {}

// row 162 - Rubber_Flat_Silver
#declare MJHTex504 = texture {}
#declare MJHTex504Slope = texture {}
#declare MJHMat504 = material {}
#declare MJHMat504Slope = material {}

// row 166 - Rubber_White
#declare MJHTex511 = texture {}
#declare MJHTex511Slope = texture {}
#declare MJHMat511 = material {}
#declare MJHMat511Slope = material {}
