// POV-Ray scripts for LDraw models and scenes
// Copyright (C) 2019  Michael Horvath
// 
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
// 
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA


// row 1 - Black
#ifdef (L3Texture0) #ifndef (MJHTex0) #declare MJHTex0 = L3Texture0; #end #end
#ifdef (L3Texture0_slope) #ifndef (MJHTex0Slope) #declare MJHTex0Slope = L3Texture0_slope; #end #end
#ifdef (L3Color0) #ifndef (MJHMat0) #declare MJHMat0 = L3Color0; #end #end
#ifdef (L3Color0_slope) #ifndef (MJHMat0Slope) #declare MJHMat0Slope = L3Color0_slope; #end #end

// row 2 - Blue
#ifdef (L3Texture1) #ifndef (MJHTex1) #declare MJHTex1 = L3Texture1; #end #end
#ifdef (L3Texture1_slope) #ifndef (MJHTex1Slope) #declare MJHTex1Slope = L3Texture1_slope; #end #end
#ifdef (L3Color1) #ifndef (MJHMat1) #declare MJHMat1 = L3Color1; #end #end
#ifdef (L3Color1_slope) #ifndef (MJHMat1Slope) #declare MJHMat1Slope = L3Color1_slope; #end #end

// row 3 - Green
#ifdef (L3Texture2) #ifndef (MJHTex2) #declare MJHTex2 = L3Texture2; #end #end
#ifdef (L3Texture2_slope) #ifndef (MJHTex2Slope) #declare MJHTex2Slope = L3Texture2_slope; #end #end
#ifdef (L3Color2) #ifndef (MJHMat2) #declare MJHMat2 = L3Color2; #end #end
#ifdef (L3Color2_slope) #ifndef (MJHMat2Slope) #declare MJHMat2Slope = L3Color2_slope; #end #end

// row 4 - Dark_Turquoise
#ifdef (L3Texture3) #ifndef (MJHTex3) #declare MJHTex3 = L3Texture3; #end #end
#ifdef (L3Texture3_slope) #ifndef (MJHTex3Slope) #declare MJHTex3Slope = L3Texture3_slope; #end #end
#ifdef (L3Color3) #ifndef (MJHMat3) #declare MJHMat3 = L3Color3; #end #end
#ifdef (L3Color3_slope) #ifndef (MJHMat3Slope) #declare MJHMat3Slope = L3Color3_slope; #end #end

// row 5 - Red
#ifdef (L3Texture4) #ifndef (MJHTex4) #declare MJHTex4 = L3Texture4; #end #end
#ifdef (L3Texture4_slope) #ifndef (MJHTex4Slope) #declare MJHTex4Slope = L3Texture4_slope; #end #end
#ifdef (L3Color4) #ifndef (MJHMat4) #declare MJHMat4 = L3Color4; #end #end
#ifdef (L3Color4_slope) #ifndef (MJHMat4Slope) #declare MJHMat4Slope = L3Color4_slope; #end #end

// row 6 - Dark_Pink
#ifdef (L3Texture5) #ifndef (MJHTex5) #declare MJHTex5 = L3Texture5; #end #end
#ifdef (L3Texture5_slope) #ifndef (MJHTex5Slope) #declare MJHTex5Slope = L3Texture5_slope; #end #end
#ifdef (L3Color5) #ifndef (MJHMat5) #declare MJHMat5 = L3Color5; #end #end
#ifdef (L3Color5_slope) #ifndef (MJHMat5Slope) #declare MJHMat5Slope = L3Color5_slope; #end #end

// row 7 - Brown
#ifdef (L3Texture6) #ifndef (MJHTex6) #declare MJHTex6 = L3Texture6; #end #end
#ifdef (L3Texture6_slope) #ifndef (MJHTex6Slope) #declare MJHTex6Slope = L3Texture6_slope; #end #end
#ifdef (L3Color6) #ifndef (MJHMat6) #declare MJHMat6 = L3Color6; #end #end
#ifdef (L3Color6_slope) #ifndef (MJHMat6Slope) #declare MJHMat6Slope = L3Color6_slope; #end #end

// row 8 - Light_Grey
#ifdef (L3Texture7) #ifndef (MJHTex7) #declare MJHTex7 = L3Texture7; #end #end
#ifdef (L3Texture7_slope) #ifndef (MJHTex7Slope) #declare MJHTex7Slope = L3Texture7_slope; #end #end
#ifdef (L3Color7) #ifndef (MJHMat7) #declare MJHMat7 = L3Color7; #end #end
#ifdef (L3Color7_slope) #ifndef (MJHMat7Slope) #declare MJHMat7Slope = L3Color7_slope; #end #end

// row 9 - Dark_Grey
#ifdef (L3Texture8) #ifndef (MJHTex8) #declare MJHTex8 = L3Texture8; #end #end
#ifdef (L3Texture8_slope) #ifndef (MJHTex8Slope) #declare MJHTex8Slope = L3Texture8_slope; #end #end
#ifdef (L3Color8) #ifndef (MJHMat8) #declare MJHMat8 = L3Color8; #end #end
#ifdef (L3Color8_slope) #ifndef (MJHMat8Slope) #declare MJHMat8Slope = L3Color8_slope; #end #end

// row 10 - Light_Blue
#ifdef (L3Texture9) #ifndef (MJHTex9) #declare MJHTex9 = L3Texture9; #end #end
#ifdef (L3Texture9_slope) #ifndef (MJHTex9Slope) #declare MJHTex9Slope = L3Texture9_slope; #end #end
#ifdef (L3Color9) #ifndef (MJHMat9) #declare MJHMat9 = L3Color9; #end #end
#ifdef (L3Color9_slope) #ifndef (MJHMat9Slope) #declare MJHMat9Slope = L3Color9_slope; #end #end

// row 11 - Bright_Green
#ifdef (L3Texture10) #ifndef (MJHTex10) #declare MJHTex10 = L3Texture10; #end #end
#ifdef (L3Texture10_slope) #ifndef (MJHTex10Slope) #declare MJHTex10Slope = L3Texture10_slope; #end #end
#ifdef (L3Color10) #ifndef (MJHMat10) #declare MJHMat10 = L3Color10; #end #end
#ifdef (L3Color10_slope) #ifndef (MJHMat10Slope) #declare MJHMat10Slope = L3Color10_slope; #end #end

// row 12 - Light_Turquoise
#ifdef (L3Texture11) #ifndef (MJHTex11) #declare MJHTex11 = L3Texture11; #end #end
#ifdef (L3Texture11_slope) #ifndef (MJHTex11Slope) #declare MJHTex11Slope = L3Texture11_slope; #end #end
#ifdef (L3Color11) #ifndef (MJHMat11) #declare MJHMat11 = L3Color11; #end #end
#ifdef (L3Color11_slope) #ifndef (MJHMat11Slope) #declare MJHMat11Slope = L3Color11_slope; #end #end

// row 13 - Salmon
#ifdef (L3Texture12) #ifndef (MJHTex12) #declare MJHTex12 = L3Texture12; #end #end
#ifdef (L3Texture12_slope) #ifndef (MJHTex12Slope) #declare MJHTex12Slope = L3Texture12_slope; #end #end
#ifdef (L3Color12) #ifndef (MJHMat12) #declare MJHMat12 = L3Color12; #end #end
#ifdef (L3Color12_slope) #ifndef (MJHMat12Slope) #declare MJHMat12Slope = L3Color12_slope; #end #end

// row 14 - Pink
#ifdef (L3Texture13) #ifndef (MJHTex13) #declare MJHTex13 = L3Texture13; #end #end
#ifdef (L3Texture13_slope) #ifndef (MJHTex13Slope) #declare MJHTex13Slope = L3Texture13_slope; #end #end
#ifdef (L3Color13) #ifndef (MJHMat13) #declare MJHMat13 = L3Color13; #end #end
#ifdef (L3Color13_slope) #ifndef (MJHMat13Slope) #declare MJHMat13Slope = L3Color13_slope; #end #end

// row 15 - Yellow
#ifdef (L3Texture14) #ifndef (MJHTex14) #declare MJHTex14 = L3Texture14; #end #end
#ifdef (L3Texture14_slope) #ifndef (MJHTex14Slope) #declare MJHTex14Slope = L3Texture14_slope; #end #end
#ifdef (L3Color14) #ifndef (MJHMat14) #declare MJHMat14 = L3Color14; #end #end
#ifdef (L3Color14_slope) #ifndef (MJHMat14Slope) #declare MJHMat14Slope = L3Color14_slope; #end #end

// row 16 - White
#ifdef (L3Texture15) #ifndef (MJHTex15) #declare MJHTex15 = L3Texture15; #end #end
#ifdef (L3Texture15_slope) #ifndef (MJHTex15Slope) #declare MJHTex15Slope = L3Texture15_slope; #end #end
#ifdef (L3Color15) #ifndef (MJHMat15) #declare MJHMat15 = L3Color15; #end #end
#ifdef (L3Color15_slope) #ifndef (MJHMat15Slope) #declare MJHMat15Slope = L3Color15_slope; #end #end

// row 17 - Main_Colour
#ifdef (L3Texture16) #ifndef (MJHTex16) #declare MJHTex16 = L3Texture16; #end #end
#ifdef (L3Texture16_slope) #ifndef (MJHTex16Slope) #declare MJHTex16Slope = L3Texture16_slope; #end #end
#ifdef (L3Color16) #ifndef (MJHMat16) #declare MJHMat16 = L3Color16; #end #end
#ifdef (L3Color16_slope) #ifndef (MJHMat16Slope) #declare MJHMat16Slope = L3Color16_slope; #end #end

// row 18 - Light_Green
#ifdef (L3Texture17) #ifndef (MJHTex17) #declare MJHTex17 = L3Texture17; #end #end
#ifdef (L3Texture17_slope) #ifndef (MJHTex17Slope) #declare MJHTex17Slope = L3Texture17_slope; #end #end
#ifdef (L3Color17) #ifndef (MJHMat17) #declare MJHMat17 = L3Color17; #end #end
#ifdef (L3Color17_slope) #ifndef (MJHMat17Slope) #declare MJHMat17Slope = L3Color17_slope; #end #end

// row 19 - Light_Yellow
#ifdef (L3Texture18) #ifndef (MJHTex18) #declare MJHTex18 = L3Texture18; #end #end
#ifdef (L3Texture18_slope) #ifndef (MJHTex18Slope) #declare MJHTex18Slope = L3Texture18_slope; #end #end
#ifdef (L3Color18) #ifndef (MJHMat18) #declare MJHMat18 = L3Color18; #end #end
#ifdef (L3Color18_slope) #ifndef (MJHMat18Slope) #declare MJHMat18Slope = L3Color18_slope; #end #end

// row 20 - Tan
#ifdef (L3Texture19) #ifndef (MJHTex19) #declare MJHTex19 = L3Texture19; #end #end
#ifdef (L3Texture19_slope) #ifndef (MJHTex19Slope) #declare MJHTex19Slope = L3Texture19_slope; #end #end
#ifdef (L3Color19) #ifndef (MJHMat19) #declare MJHMat19 = L3Color19; #end #end
#ifdef (L3Color19_slope) #ifndef (MJHMat19Slope) #declare MJHMat19Slope = L3Color19_slope; #end #end

// row 21 - Light_Violet
#ifdef (L3Texture20) #ifndef (MJHTex20) #declare MJHTex20 = L3Texture20; #end #end
#ifdef (L3Texture20_slope) #ifndef (MJHTex20Slope) #declare MJHTex20Slope = L3Texture20_slope; #end #end
#ifdef (L3Color20) #ifndef (MJHMat20) #declare MJHMat20 = L3Color20; #end #end
#ifdef (L3Color20_slope) #ifndef (MJHMat20Slope) #declare MJHMat20Slope = L3Color20_slope; #end #end

// row 22 - Glow_In_Dark_Opaque
#ifdef (L3Texture21) #ifndef (MJHTex21) #declare MJHTex21 = L3Texture21; #end #end
#ifdef (L3Texture21_slope) #ifndef (MJHTex21Slope) #declare MJHTex21Slope = L3Texture21_slope; #end #end
#ifdef (L3Color21) #ifndef (MJHMat21) #declare MJHMat21 = L3Color21; #end #end
#ifdef (L3Color21_slope) #ifndef (MJHMat21Slope) #declare MJHMat21Slope = L3Color21_slope; #end #end

// row 23 - Purple
#ifdef (L3Texture22) #ifndef (MJHTex22) #declare MJHTex22 = L3Texture22; #end #end
#ifdef (L3Texture22_slope) #ifndef (MJHTex22Slope) #declare MJHTex22Slope = L3Texture22_slope; #end #end
#ifdef (L3Color22) #ifndef (MJHMat22) #declare MJHMat22 = L3Color22; #end #end
#ifdef (L3Color22_slope) #ifndef (MJHMat22Slope) #declare MJHMat22Slope = L3Color22_slope; #end #end

// row 24 - Dark_Blue_Violet
#ifdef (L3Texture23) #ifndef (MJHTex23) #declare MJHTex23 = L3Texture23; #end #end
#ifdef (L3Texture23_slope) #ifndef (MJHTex23Slope) #declare MJHTex23Slope = L3Texture23_slope; #end #end
#ifdef (L3Color23) #ifndef (MJHMat23) #declare MJHMat23 = L3Color23; #end #end
#ifdef (L3Color23_slope) #ifndef (MJHMat23Slope) #declare MJHMat23Slope = L3Color23_slope; #end #end

// row 25 - Edge_Colour
#ifdef (L3Texture24) #ifndef (MJHTex24) #declare MJHTex24 = L3Texture24; #end #end
#ifdef (L3Texture24_slope) #ifndef (MJHTex24Slope) #declare MJHTex24Slope = L3Texture24_slope; #end #end
#ifdef (L3Color24) #ifndef (MJHMat24) #declare MJHMat24 = L3Color24; #end #end
#ifdef (L3Color24_slope) #ifndef (MJHMat24Slope) #declare MJHMat24Slope = L3Color24_slope; #end #end

// row 26 - Orange
#ifdef (L3Texture25) #ifndef (MJHTex25) #declare MJHTex25 = L3Texture25; #end #end
#ifdef (L3Texture25_slope) #ifndef (MJHTex25Slope) #declare MJHTex25Slope = L3Texture25_slope; #end #end
#ifdef (L3Color25) #ifndef (MJHMat25) #declare MJHMat25 = L3Color25; #end #end
#ifdef (L3Color25_slope) #ifndef (MJHMat25Slope) #declare MJHMat25Slope = L3Color25_slope; #end #end

// row 27 - Magenta
#ifdef (L3Texture26) #ifndef (MJHTex26) #declare MJHTex26 = L3Texture26; #end #end
#ifdef (L3Texture26_slope) #ifndef (MJHTex26Slope) #declare MJHTex26Slope = L3Texture26_slope; #end #end
#ifdef (L3Color26) #ifndef (MJHMat26) #declare MJHMat26 = L3Color26; #end #end
#ifdef (L3Color26_slope) #ifndef (MJHMat26Slope) #declare MJHMat26Slope = L3Color26_slope; #end #end

// row 28 - Lime
#ifdef (L3Texture27) #ifndef (MJHTex27) #declare MJHTex27 = L3Texture27; #end #end
#ifdef (L3Texture27_slope) #ifndef (MJHTex27Slope) #declare MJHTex27Slope = L3Texture27_slope; #end #end
#ifdef (L3Color27) #ifndef (MJHMat27) #declare MJHMat27 = L3Color27; #end #end
#ifdef (L3Color27_slope) #ifndef (MJHMat27Slope) #declare MJHMat27Slope = L3Color27_slope; #end #end

// row 29 - Dark_Tan
#ifdef (L3Texture28) #ifndef (MJHTex28) #declare MJHTex28 = L3Texture28; #end #end
#ifdef (L3Texture28_slope) #ifndef (MJHTex28Slope) #declare MJHTex28Slope = L3Texture28_slope; #end #end
#ifdef (L3Color28) #ifndef (MJHMat28) #declare MJHMat28 = L3Color28; #end #end
#ifdef (L3Color28_slope) #ifndef (MJHMat28Slope) #declare MJHMat28Slope = L3Color28_slope; #end #end

// row 30 - Bright_Pink
#ifdef (L3Texture29) #ifndef (MJHTex29) #declare MJHTex29 = L3Texture29; #end #end
#ifdef (L3Texture29_slope) #ifndef (MJHTex29Slope) #declare MJHTex29Slope = L3Texture29_slope; #end #end
#ifdef (L3Color29) #ifndef (MJHMat29) #declare MJHMat29 = L3Color29; #end #end
#ifdef (L3Color29_slope) #ifndef (MJHMat29Slope) #declare MJHMat29Slope = L3Color29_slope; #end #end

// row 31 - Medium_Lavender
#ifdef (L3Texture30) #ifndef (MJHTex30) #declare MJHTex30 = L3Texture30; #end #end
#ifdef (L3Texture30_slope) #ifndef (MJHTex30Slope) #declare MJHTex30Slope = L3Texture30_slope; #end #end
#ifdef (L3Color30) #ifndef (MJHMat30) #declare MJHMat30 = L3Color30; #end #end
#ifdef (L3Color30_slope) #ifndef (MJHMat30Slope) #declare MJHMat30Slope = L3Color30_slope; #end #end

// row 32 - Lavender
#ifdef (L3Texture31) #ifndef (MJHTex31) #declare MJHTex31 = L3Texture31; #end #end
#ifdef (L3Texture31_slope) #ifndef (MJHTex31Slope) #declare MJHTex31Slope = L3Texture31_slope; #end #end
#ifdef (L3Color31) #ifndef (MJHMat31) #declare MJHMat31 = L3Color31; #end #end
#ifdef (L3Color31_slope) #ifndef (MJHMat31Slope) #declare MJHMat31Slope = L3Color31_slope; #end #end

// row 33 - Trans_Black_IR_Lens
#ifdef (L3Texture32) #ifndef (MJHTex32) #declare MJHTex32 = L3Texture32; #end #end
#ifdef (L3Texture32_slope) #ifndef (MJHTex32Slope) #declare MJHTex32Slope = L3Texture32_slope; #end #end
#ifdef (L3Color32) #ifndef (MJHMat32) #declare MJHMat32 = L3Color32; #end #end
#ifdef (L3Color32_slope) #ifndef (MJHMat32Slope) #declare MJHMat32Slope = L3Color32_slope; #end #end

// row 34 - Trans_Dark_Blue
#ifdef (L3Texture33) #ifndef (MJHTex33) #declare MJHTex33 = L3Texture33; #end #end
#ifdef (L3Texture33_slope) #ifndef (MJHTex33Slope) #declare MJHTex33Slope = L3Texture33_slope; #end #end
#ifdef (L3Color33) #ifndef (MJHMat33) #declare MJHMat33 = L3Color33; #end #end
#ifdef (L3Color33_slope) #ifndef (MJHMat33Slope) #declare MJHMat33Slope = L3Color33_slope; #end #end

// row 35 - Trans_Green
#ifdef (L3Texture34) #ifndef (MJHTex34) #declare MJHTex34 = L3Texture34; #end #end
#ifdef (L3Texture34_slope) #ifndef (MJHTex34Slope) #declare MJHTex34Slope = L3Texture34_slope; #end #end
#ifdef (L3Color34) #ifndef (MJHMat34) #declare MJHMat34 = L3Color34; #end #end
#ifdef (L3Color34_slope) #ifndef (MJHMat34Slope) #declare MJHMat34Slope = L3Color34_slope; #end #end

// row 36 - Trans_Bright_Green
#ifdef (L3Texture35) #ifndef (MJHTex35) #declare MJHTex35 = L3Texture35; #end #end
#ifdef (L3Texture35_slope) #ifndef (MJHTex35Slope) #declare MJHTex35Slope = L3Texture35_slope; #end #end
#ifdef (L3Color35) #ifndef (MJHMat35) #declare MJHMat35 = L3Color35; #end #end
#ifdef (L3Color35_slope) #ifndef (MJHMat35Slope) #declare MJHMat35Slope = L3Color35_slope; #end #end

// row 37 - Trans_Red
#ifdef (L3Texture36) #ifndef (MJHTex36) #declare MJHTex36 = L3Texture36; #end #end
#ifdef (L3Texture36_slope) #ifndef (MJHTex36Slope) #declare MJHTex36Slope = L3Texture36_slope; #end #end
#ifdef (L3Color36) #ifndef (MJHMat36) #declare MJHMat36 = L3Color36; #end #end
#ifdef (L3Color36_slope) #ifndef (MJHMat36Slope) #declare MJHMat36Slope = L3Color36_slope; #end #end

// row 38 - Trans_Dark_Pink
#ifdef (L3Texture37) #ifndef (MJHTex37) #declare MJHTex37 = L3Texture37; #end #end
#ifdef (L3Texture37_slope) #ifndef (MJHTex37Slope) #declare MJHTex37Slope = L3Texture37_slope; #end #end
#ifdef (L3Color37) #ifndef (MJHMat37) #declare MJHMat37 = L3Color37; #end #end
#ifdef (L3Color37_slope) #ifndef (MJHMat37Slope) #declare MJHMat37Slope = L3Color37_slope; #end #end

// row 39 - Trans_Neon_Orange
#ifdef (L3Texture38) #ifndef (MJHTex38) #declare MJHTex38 = L3Texture38; #end #end
#ifdef (L3Texture38_slope) #ifndef (MJHTex38Slope) #declare MJHTex38Slope = L3Texture38_slope; #end #end
#ifdef (L3Color38) #ifndef (MJHMat38) #declare MJHMat38 = L3Color38; #end #end
#ifdef (L3Color38_slope) #ifndef (MJHMat38Slope) #declare MJHMat38Slope = L3Color38_slope; #end #end

// row 40 - Trans_Very_Light_Blue
#ifdef (L3Texture39) #ifndef (MJHTex39) #declare MJHTex39 = L3Texture39; #end #end
#ifdef (L3Texture39_slope) #ifndef (MJHTex39Slope) #declare MJHTex39Slope = L3Texture39_slope; #end #end
#ifdef (L3Color39) #ifndef (MJHMat39) #declare MJHMat39 = L3Color39; #end #end
#ifdef (L3Color39_slope) #ifndef (MJHMat39Slope) #declare MJHMat39Slope = L3Color39_slope; #end #end

// row 41 - Trans_Black
#ifdef (L3Texture40) #ifndef (MJHTex40) #declare MJHTex40 = L3Texture40; #end #end
#ifdef (L3Texture40_slope) #ifndef (MJHTex40Slope) #declare MJHTex40Slope = L3Texture40_slope; #end #end
#ifdef (L3Color40) #ifndef (MJHMat40) #declare MJHMat40 = L3Color40; #end #end
#ifdef (L3Color40_slope) #ifndef (MJHMat40Slope) #declare MJHMat40Slope = L3Color40_slope; #end #end

// row 42 - Trans_Medium_Blue
#ifdef (L3Texture41) #ifndef (MJHTex41) #declare MJHTex41 = L3Texture41; #end #end
#ifdef (L3Texture41_slope) #ifndef (MJHTex41Slope) #declare MJHTex41Slope = L3Texture41_slope; #end #end
#ifdef (L3Color41) #ifndef (MJHMat41) #declare MJHMat41 = L3Color41; #end #end
#ifdef (L3Color41_slope) #ifndef (MJHMat41Slope) #declare MJHMat41Slope = L3Color41_slope; #end #end

// row 43 - Trans_Neon_Green
#ifdef (L3Texture42) #ifndef (MJHTex42) #declare MJHTex42 = L3Texture42; #end #end
#ifdef (L3Texture42_slope) #ifndef (MJHTex42Slope) #declare MJHTex42Slope = L3Texture42_slope; #end #end
#ifdef (L3Color42) #ifndef (MJHMat42) #declare MJHMat42 = L3Color42; #end #end
#ifdef (L3Color42_slope) #ifndef (MJHMat42Slope) #declare MJHMat42Slope = L3Color42_slope; #end #end

// row 44 - Trans_Light_Blue
#ifdef (L3Texture43) #ifndef (MJHTex43) #declare MJHTex43 = L3Texture43; #end #end
#ifdef (L3Texture43_slope) #ifndef (MJHTex43Slope) #declare MJHTex43Slope = L3Texture43_slope; #end #end
#ifdef (L3Color43) #ifndef (MJHMat43) #declare MJHMat43 = L3Color43; #end #end
#ifdef (L3Color43_slope) #ifndef (MJHMat43Slope) #declare MJHMat43Slope = L3Color43_slope; #end #end

// row 45 - Trans_Bright_Reddish_Lilac
#ifdef (L3Texture44) #ifndef (MJHTex44) #declare MJHTex44 = L3Texture44; #end #end
#ifdef (L3Texture44_slope) #ifndef (MJHTex44Slope) #declare MJHTex44Slope = L3Texture44_slope; #end #end
#ifdef (L3Color44) #ifndef (MJHMat44) #declare MJHMat44 = L3Color44; #end #end
#ifdef (L3Color44_slope) #ifndef (MJHMat44Slope) #declare MJHMat44Slope = L3Color44_slope; #end #end

// row 46 - Trans_Pink
#ifdef (L3Texture45) #ifndef (MJHTex45) #declare MJHTex45 = L3Texture45; #end #end
#ifdef (L3Texture45_slope) #ifndef (MJHTex45Slope) #declare MJHTex45Slope = L3Texture45_slope; #end #end
#ifdef (L3Color45) #ifndef (MJHMat45) #declare MJHMat45 = L3Color45; #end #end
#ifdef (L3Color45_slope) #ifndef (MJHMat45Slope) #declare MJHMat45Slope = L3Color45_slope; #end #end

// row 47 - Trans_Yellow
#ifdef (L3Texture46) #ifndef (MJHTex46) #declare MJHTex46 = L3Texture46; #end #end
#ifdef (L3Texture46_slope) #ifndef (MJHTex46Slope) #declare MJHTex46Slope = L3Texture46_slope; #end #end
#ifdef (L3Color46) #ifndef (MJHMat46) #declare MJHMat46 = L3Color46; #end #end
#ifdef (L3Color46_slope) #ifndef (MJHMat46Slope) #declare MJHMat46Slope = L3Color46_slope; #end #end

// row 48 - Trans_Clear
#ifdef (L3Texture47) #ifndef (MJHTex47) #declare MJHTex47 = L3Texture47; #end #end
#ifdef (L3Texture47_slope) #ifndef (MJHTex47Slope) #declare MJHTex47Slope = L3Texture47_slope; #end #end
#ifdef (L3Color47) #ifndef (MJHMat47) #declare MJHMat47 = L3Color47; #end #end
#ifdef (L3Color47_slope) #ifndef (MJHMat47Slope) #declare MJHMat47Slope = L3Color47_slope; #end #end

// row 49 - Trans_Purple
#ifdef (L3Texture52) #ifndef (MJHTex52) #declare MJHTex52 = L3Texture52; #end #end
#ifdef (L3Texture52_slope) #ifndef (MJHTex52Slope) #declare MJHTex52Slope = L3Texture52_slope; #end #end
#ifdef (L3Color52) #ifndef (MJHMat52) #declare MJHMat52 = L3Color52; #end #end
#ifdef (L3Color52_slope) #ifndef (MJHMat52Slope) #declare MJHMat52Slope = L3Color52_slope; #end #end

// row 50 - Trans_Neon_Yellow
#ifdef (L3Texture54) #ifndef (MJHTex54) #declare MJHTex54 = L3Texture54; #end #end
#ifdef (L3Texture54_slope) #ifndef (MJHTex54Slope) #declare MJHTex54Slope = L3Texture54_slope; #end #end
#ifdef (L3Color54) #ifndef (MJHMat54) #declare MJHMat54 = L3Color54; #end #end
#ifdef (L3Color54_slope) #ifndef (MJHMat54Slope) #declare MJHMat54Slope = L3Color54_slope; #end #end

// row 51 - Trans_Orange
#ifdef (L3Texture57) #ifndef (MJHTex57) #declare MJHTex57 = L3Texture57; #end #end
#ifdef (L3Texture57_slope) #ifndef (MJHTex57Slope) #declare MJHTex57Slope = L3Texture57_slope; #end #end
#ifdef (L3Color57) #ifndef (MJHMat57) #declare MJHMat57 = L3Color57; #end #end
#ifdef (L3Color57_slope) #ifndef (MJHMat57Slope) #declare MJHMat57Slope = L3Color57_slope; #end #end

// row 52 - Chrome_Antique_Brass
#ifdef (L3Texture60) #ifndef (MJHTex60) #declare MJHTex60 = L3Texture60; #end #end
#ifdef (L3Texture60_slope) #ifndef (MJHTex60Slope) #declare MJHTex60Slope = L3Texture60_slope; #end #end
#ifdef (L3Color60) #ifndef (MJHMat60) #declare MJHMat60 = L3Color60; #end #end
#ifdef (L3Color60_slope) #ifndef (MJHMat60Slope) #declare MJHMat60Slope = L3Color60_slope; #end #end

// row 53 - Chrome_Blue
#ifdef (L3Texture61) #ifndef (MJHTex61) #declare MJHTex61 = L3Texture61; #end #end
#ifdef (L3Texture61_slope) #ifndef (MJHTex61Slope) #declare MJHTex61Slope = L3Texture61_slope; #end #end
#ifdef (L3Color61) #ifndef (MJHMat61) #declare MJHMat61 = L3Color61; #end #end
#ifdef (L3Color61_slope) #ifndef (MJHMat61Slope) #declare MJHMat61Slope = L3Color61_slope; #end #end

// row 54 - Chrome_Green
#ifdef (L3Texture62) #ifndef (MJHTex62) #declare MJHTex62 = L3Texture62; #end #end
#ifdef (L3Texture62_slope) #ifndef (MJHTex62Slope) #declare MJHTex62Slope = L3Texture62_slope; #end #end
#ifdef (L3Color62) #ifndef (MJHMat62) #declare MJHMat62 = L3Color62; #end #end
#ifdef (L3Color62_slope) #ifndef (MJHMat62Slope) #declare MJHMat62Slope = L3Color62_slope; #end #end

// row 55 - Chrome_Pink
#ifdef (L3Texture63) #ifndef (MJHTex63) #declare MJHTex63 = L3Texture63; #end #end
#ifdef (L3Texture63_slope) #ifndef (MJHTex63Slope) #declare MJHTex63Slope = L3Texture63_slope; #end #end
#ifdef (L3Color63) #ifndef (MJHMat63) #declare MJHMat63 = L3Color63; #end #end
#ifdef (L3Color63_slope) #ifndef (MJHMat63Slope) #declare MJHMat63Slope = L3Color63_slope; #end #end

// row 56 - Chrome_Black
#ifdef (L3Texture64) #ifndef (MJHTex64) #declare MJHTex64 = L3Texture64; #end #end
#ifdef (L3Texture64_slope) #ifndef (MJHTex64Slope) #declare MJHTex64Slope = L3Texture64_slope; #end #end
#ifdef (L3Color64) #ifndef (MJHMat64) #declare MJHMat64 = L3Color64; #end #end
#ifdef (L3Color64_slope) #ifndef (MJHMat64Slope) #declare MJHMat64Slope = L3Color64_slope; #end #end

// row 57 - Rubber_Yellow
#ifdef (L3Texture65) #ifndef (MJHTex65) #declare MJHTex65 = L3Texture65; #end #end
#ifdef (L3Texture65_slope) #ifndef (MJHTex65Slope) #declare MJHTex65Slope = L3Texture65_slope; #end #end
#ifdef (L3Color65) #ifndef (MJHMat65) #declare MJHMat65 = L3Color65; #end #end
#ifdef (L3Color65_slope) #ifndef (MJHMat65Slope) #declare MJHMat65Slope = L3Color65_slope; #end #end

// row 58 - Rubber_Trans_Yellow
#ifdef (L3Texture66) #ifndef (MJHTex66) #declare MJHTex66 = L3Texture66; #end #end
#ifdef (L3Texture66_slope) #ifndef (MJHTex66Slope) #declare MJHTex66Slope = L3Texture66_slope; #end #end
#ifdef (L3Color66) #ifndef (MJHMat66) #declare MJHMat66 = L3Color66; #end #end
#ifdef (L3Color66_slope) #ifndef (MJHMat66Slope) #declare MJHMat66Slope = L3Color66_slope; #end #end

// row 59 - Rubber_Trans_Clear
#ifdef (L3Texture67) #ifndef (MJHTex67) #declare MJHTex67 = L3Texture67; #end #end
#ifdef (L3Texture67_slope) #ifndef (MJHTex67Slope) #declare MJHTex67Slope = L3Texture67_slope; #end #end
#ifdef (L3Color67) #ifndef (MJHMat67) #declare MJHMat67 = L3Color67; #end #end
#ifdef (L3Color67_slope) #ifndef (MJHMat67Slope) #declare MJHMat67Slope = L3Color67_slope; #end #end

// row 60 - Very_Light_Orange
#ifdef (L3Texture68) #ifndef (MJHTex68) #declare MJHTex68 = L3Texture68; #end #end
#ifdef (L3Texture68_slope) #ifndef (MJHTex68Slope) #declare MJHTex68Slope = L3Texture68_slope; #end #end
#ifdef (L3Color68) #ifndef (MJHMat68) #declare MJHMat68 = L3Color68; #end #end
#ifdef (L3Color68_slope) #ifndef (MJHMat68Slope) #declare MJHMat68Slope = L3Color68_slope; #end #end

// row 61 - Bright_Reddish_Lilac
#ifdef (L3Texture69) #ifndef (MJHTex69) #declare MJHTex69 = L3Texture69; #end #end
#ifdef (L3Texture69_slope) #ifndef (MJHTex69Slope) #declare MJHTex69Slope = L3Texture69_slope; #end #end
#ifdef (L3Color69) #ifndef (MJHMat69) #declare MJHMat69 = L3Color69; #end #end
#ifdef (L3Color69_slope) #ifndef (MJHMat69Slope) #declare MJHMat69Slope = L3Color69_slope; #end #end

// row 62 - Reddish_Brown
#ifdef (L3Texture70) #ifndef (MJHTex70) #declare MJHTex70 = L3Texture70; #end #end
#ifdef (L3Texture70_slope) #ifndef (MJHTex70Slope) #declare MJHTex70Slope = L3Texture70_slope; #end #end
#ifdef (L3Color70) #ifndef (MJHMat70) #declare MJHMat70 = L3Color70; #end #end
#ifdef (L3Color70_slope) #ifndef (MJHMat70Slope) #declare MJHMat70Slope = L3Color70_slope; #end #end

// row 63 - Light_Bluish_Grey
#ifdef (L3Texture71) #ifndef (MJHTex71) #declare MJHTex71 = L3Texture71; #end #end
#ifdef (L3Texture71_slope) #ifndef (MJHTex71Slope) #declare MJHTex71Slope = L3Texture71_slope; #end #end
#ifdef (L3Color71) #ifndef (MJHMat71) #declare MJHMat71 = L3Color71; #end #end
#ifdef (L3Color71_slope) #ifndef (MJHMat71Slope) #declare MJHMat71Slope = L3Color71_slope; #end #end

// row 64 - Dark_Bluish_Grey
#ifdef (L3Texture72) #ifndef (MJHTex72) #declare MJHTex72 = L3Texture72; #end #end
#ifdef (L3Texture72_slope) #ifndef (MJHTex72Slope) #declare MJHTex72Slope = L3Texture72_slope; #end #end
#ifdef (L3Color72) #ifndef (MJHMat72) #declare MJHMat72 = L3Color72; #end #end
#ifdef (L3Color72_slope) #ifndef (MJHMat72Slope) #declare MJHMat72Slope = L3Color72_slope; #end #end

// row 65 - Medium_Blue
#ifdef (L3Texture73) #ifndef (MJHTex73) #declare MJHTex73 = L3Texture73; #end #end
#ifdef (L3Texture73_slope) #ifndef (MJHTex73Slope) #declare MJHTex73Slope = L3Texture73_slope; #end #end
#ifdef (L3Color73) #ifndef (MJHMat73) #declare MJHMat73 = L3Color73; #end #end
#ifdef (L3Color73_slope) #ifndef (MJHMat73Slope) #declare MJHMat73Slope = L3Color73_slope; #end #end

// row 66 - Medium_Green
#ifdef (L3Texture74) #ifndef (MJHTex74) #declare MJHTex74 = L3Texture74; #end #end
#ifdef (L3Texture74_slope) #ifndef (MJHTex74Slope) #declare MJHTex74Slope = L3Texture74_slope; #end #end
#ifdef (L3Color74) #ifndef (MJHMat74) #declare MJHMat74 = L3Color74; #end #end
#ifdef (L3Color74_slope) #ifndef (MJHMat74Slope) #declare MJHMat74Slope = L3Color74_slope; #end #end

// row 67 - Speckle_Black_Copper
#ifdef (L3Texture75) #ifndef (MJHTex75) #declare MJHTex75 = L3Texture75; #end #end
#ifdef (L3Texture75_slope) #ifndef (MJHTex75Slope) #declare MJHTex75Slope = L3Texture75_slope; #end #end
#ifdef (L3Color75) #ifndef (MJHMat75) #declare MJHMat75 = L3Color75; #end #end
#ifdef (L3Color75_slope) #ifndef (MJHMat75Slope) #declare MJHMat75Slope = L3Color75_slope; #end #end

// row 68 - Speckle_Dark_Bluish_Grey_Silver
#ifdef (L3Texture76) #ifndef (MJHTex76) #declare MJHTex76 = L3Texture76; #end #end
#ifdef (L3Texture76_slope) #ifndef (MJHTex76Slope) #declare MJHTex76Slope = L3Texture76_slope; #end #end
#ifdef (L3Color76) #ifndef (MJHMat76) #declare MJHMat76 = L3Color76; #end #end
#ifdef (L3Color76_slope) #ifndef (MJHMat76Slope) #declare MJHMat76Slope = L3Color76_slope; #end #end

// row 69 - Light_Pink
#ifdef (L3Texture77) #ifndef (MJHTex77) #declare MJHTex77 = L3Texture77; #end #end
#ifdef (L3Texture77_slope) #ifndef (MJHTex77Slope) #declare MJHTex77Slope = L3Texture77_slope; #end #end
#ifdef (L3Color77) #ifndef (MJHMat77) #declare MJHMat77 = L3Color77; #end #end
#ifdef (L3Color77_slope) #ifndef (MJHMat77Slope) #declare MJHMat77Slope = L3Color77_slope; #end #end

// row 70 - Light_Flesh
#ifdef (L3Texture78) #ifndef (MJHTex78) #declare MJHTex78 = L3Texture78; #end #end
#ifdef (L3Texture78_slope) #ifndef (MJHTex78Slope) #declare MJHTex78Slope = L3Texture78_slope; #end #end
#ifdef (L3Color78) #ifndef (MJHMat78) #declare MJHMat78 = L3Color78; #end #end
#ifdef (L3Color78_slope) #ifndef (MJHMat78Slope) #declare MJHMat78Slope = L3Color78_slope; #end #end

// row 71 - Milky_White
#ifdef (L3Texture79) #ifndef (MJHTex79) #declare MJHTex79 = L3Texture79; #end #end
#ifdef (L3Texture79_slope) #ifndef (MJHTex79Slope) #declare MJHTex79Slope = L3Texture79_slope; #end #end
#ifdef (L3Color79) #ifndef (MJHMat79) #declare MJHMat79 = L3Color79; #end #end
#ifdef (L3Color79_slope) #ifndef (MJHMat79Slope) #declare MJHMat79Slope = L3Color79_slope; #end #end

// row 72 - Metallic_Silver
#ifdef (L3Texture80) #ifndef (MJHTex80) #declare MJHTex80 = L3Texture80; #end #end
#ifdef (L3Texture80_slope) #ifndef (MJHTex80Slope) #declare MJHTex80Slope = L3Texture80_slope; #end #end
#ifdef (L3Color80) #ifndef (MJHMat80) #declare MJHMat80 = L3Color80; #end #end
#ifdef (L3Color80_slope) #ifndef (MJHMat80Slope) #declare MJHMat80Slope = L3Color80_slope; #end #end

// row 73 - Metallic_Green
#ifdef (L3Texture81) #ifndef (MJHTex81) #declare MJHTex81 = L3Texture81; #end #end
#ifdef (L3Texture81_slope) #ifndef (MJHTex81Slope) #declare MJHTex81Slope = L3Texture81_slope; #end #end
#ifdef (L3Color81) #ifndef (MJHMat81) #declare MJHMat81 = L3Color81; #end #end
#ifdef (L3Color81_slope) #ifndef (MJHMat81Slope) #declare MJHMat81Slope = L3Color81_slope; #end #end

// row 74 - Metallic_Gold
#ifdef (L3Texture82) #ifndef (MJHTex82) #declare MJHTex82 = L3Texture82; #end #end
#ifdef (L3Texture82_slope) #ifndef (MJHTex82Slope) #declare MJHTex82Slope = L3Texture82_slope; #end #end
#ifdef (L3Color82) #ifndef (MJHMat82) #declare MJHMat82 = L3Color82; #end #end
#ifdef (L3Color82_slope) #ifndef (MJHMat82Slope) #declare MJHMat82Slope = L3Color82_slope; #end #end

// row 75 - Metallic_Black
#ifdef (L3Texture83) #ifndef (MJHTex83) #declare MJHTex83 = L3Texture83; #end #end
#ifdef (L3Texture83_slope) #ifndef (MJHTex83Slope) #declare MJHTex83Slope = L3Texture83_slope; #end #end
#ifdef (L3Color83) #ifndef (MJHMat83) #declare MJHMat83 = L3Color83; #end #end
#ifdef (L3Color83_slope) #ifndef (MJHMat83Slope) #declare MJHMat83Slope = L3Color83_slope; #end #end

// row 76 - Medium_Dark_Flesh
#ifdef (L3Texture84) #ifndef (MJHTex84) #declare MJHTex84 = L3Texture84; #end #end
#ifdef (L3Texture84_slope) #ifndef (MJHTex84Slope) #declare MJHTex84Slope = L3Texture84_slope; #end #end
#ifdef (L3Color84) #ifndef (MJHMat84) #declare MJHMat84 = L3Color84; #end #end
#ifdef (L3Color84_slope) #ifndef (MJHMat84Slope) #declare MJHMat84Slope = L3Color84_slope; #end #end

// row 77 - Medium_Lilac
#ifdef (L3Texture85) #ifndef (MJHTex85) #declare MJHTex85 = L3Texture85; #end #end
#ifdef (L3Texture85_slope) #ifndef (MJHTex85Slope) #declare MJHTex85Slope = L3Texture85_slope; #end #end
#ifdef (L3Color85) #ifndef (MJHMat85) #declare MJHMat85 = L3Color85; #end #end
#ifdef (L3Color85_slope) #ifndef (MJHMat85Slope) #declare MJHMat85Slope = L3Color85_slope; #end #end

// row 78 - Dark_Flesh
#ifdef (L3Texture86) #ifndef (MJHTex86) #declare MJHTex86 = L3Texture86; #end #end
#ifdef (L3Texture86_slope) #ifndef (MJHTex86Slope) #declare MJHTex86Slope = L3Texture86_slope; #end #end
#ifdef (L3Color86) #ifndef (MJHMat86) #declare MJHMat86 = L3Color86; #end #end
#ifdef (L3Color86_slope) #ifndef (MJHMat86Slope) #declare MJHMat86Slope = L3Color86_slope; #end #end

// row 79 - Metallic_Dark_Grey
#ifdef (L3Texture87) #ifndef (MJHTex87) #declare MJHTex87 = L3Texture87; #end #end
#ifdef (L3Texture87_slope) #ifndef (MJHTex87Slope) #declare MJHTex87Slope = L3Texture87_slope; #end #end
#ifdef (L3Color87) #ifndef (MJHMat87) #declare MJHMat87 = L3Color87; #end #end
#ifdef (L3Color87_slope) #ifndef (MJHMat87Slope) #declare MJHMat87Slope = L3Color87_slope; #end #end

// row 80 - Blue_Violet
#ifdef (L3Texture89) #ifndef (MJHTex89) #declare MJHTex89 = L3Texture89; #end #end
#ifdef (L3Texture89_slope) #ifndef (MJHTex89Slope) #declare MJHTex89Slope = L3Texture89_slope; #end #end
#ifdef (L3Color89) #ifndef (MJHMat89) #declare MJHMat89 = L3Color89; #end #end
#ifdef (L3Color89_slope) #ifndef (MJHMat89Slope) #declare MJHMat89Slope = L3Color89_slope; #end #end

// row 81 - Flesh
#ifdef (L3Texture92) #ifndef (MJHTex92) #declare MJHTex92 = L3Texture92; #end #end
#ifdef (L3Texture92_slope) #ifndef (MJHTex92Slope) #declare MJHTex92Slope = L3Texture92_slope; #end #end
#ifdef (L3Color92) #ifndef (MJHMat92) #declare MJHMat92 = L3Color92; #end #end
#ifdef (L3Color92_slope) #ifndef (MJHMat92Slope) #declare MJHMat92Slope = L3Color92_slope; #end #end

// row 82 - Light_Salmon
#ifdef (L3Texture100) #ifndef (MJHTex100) #declare MJHTex100 = L3Texture100; #end #end
#ifdef (L3Texture100_slope) #ifndef (MJHTex100Slope) #declare MJHTex100Slope = L3Texture100_slope; #end #end
#ifdef (L3Color100) #ifndef (MJHMat100) #declare MJHMat100 = L3Color100; #end #end
#ifdef (L3Color100_slope) #ifndef (MJHMat100Slope) #declare MJHMat100Slope = L3Color100_slope; #end #end

// row 83 - Violet
#ifdef (L3Texture110) #ifndef (MJHTex110) #declare MJHTex110 = L3Texture110; #end #end
#ifdef (L3Texture110_slope) #ifndef (MJHTex110Slope) #declare MJHTex110Slope = L3Texture110_slope; #end #end
#ifdef (L3Color110) #ifndef (MJHMat110) #declare MJHMat110 = L3Color110; #end #end
#ifdef (L3Color110_slope) #ifndef (MJHMat110Slope) #declare MJHMat110Slope = L3Color110_slope; #end #end

// row 84 - Medium_Violet
#ifdef (L3Texture112) #ifndef (MJHTex112) #declare MJHTex112 = L3Texture112; #end #end
#ifdef (L3Texture112_slope) #ifndef (MJHTex112Slope) #declare MJHTex112Slope = L3Texture112_slope; #end #end
#ifdef (L3Color112) #ifndef (MJHMat112) #declare MJHMat112 = L3Color112; #end #end
#ifdef (L3Color112_slope) #ifndef (MJHMat112Slope) #declare MJHMat112Slope = L3Color112_slope; #end #end

// row 85 - Glitter_Trans_Dark_Pink
#ifdef (L3Texture114) #ifndef (MJHTex114) #declare MJHTex114 = L3Texture114; #end #end
#ifdef (L3Texture114_slope) #ifndef (MJHTex114Slope) #declare MJHTex114Slope = L3Texture114_slope; #end #end
#ifdef (L3Color114) #ifndef (MJHMat114) #declare MJHMat114 = L3Color114; #end #end
#ifdef (L3Color114_slope) #ifndef (MJHMat114Slope) #declare MJHMat114Slope = L3Color114_slope; #end #end

// row 86 - Medium_Lime
#ifdef (L3Texture115) #ifndef (MJHTex115) #declare MJHTex115 = L3Texture115; #end #end
#ifdef (L3Texture115_slope) #ifndef (MJHTex115Slope) #declare MJHTex115Slope = L3Texture115_slope; #end #end
#ifdef (L3Color115) #ifndef (MJHMat115) #declare MJHMat115 = L3Color115; #end #end
#ifdef (L3Color115_slope) #ifndef (MJHMat115Slope) #declare MJHMat115Slope = L3Color115_slope; #end #end

// row 87 - Glitter_Trans_Clear
#ifdef (L3Texture117) #ifndef (MJHTex117) #declare MJHTex117 = L3Texture117; #end #end
#ifdef (L3Texture117_slope) #ifndef (MJHTex117Slope) #declare MJHTex117Slope = L3Texture117_slope; #end #end
#ifdef (L3Color117) #ifndef (MJHMat117) #declare MJHMat117 = L3Color117; #end #end
#ifdef (L3Color117_slope) #ifndef (MJHMat117Slope) #declare MJHMat117Slope = L3Color117_slope; #end #end

// row 88 - Aqua
#ifdef (L3Texture118) #ifndef (MJHTex118) #declare MJHTex118 = L3Texture118; #end #end
#ifdef (L3Texture118_slope) #ifndef (MJHTex118Slope) #declare MJHTex118Slope = L3Texture118_slope; #end #end
#ifdef (L3Color118) #ifndef (MJHMat118) #declare MJHMat118 = L3Color118; #end #end
#ifdef (L3Color118_slope) #ifndef (MJHMat118Slope) #declare MJHMat118Slope = L3Color118_slope; #end #end

// row 89 - Light_Lime
#ifdef (L3Texture120) #ifndef (MJHTex120) #declare MJHTex120 = L3Texture120; #end #end
#ifdef (L3Texture120_slope) #ifndef (MJHTex120Slope) #declare MJHTex120Slope = L3Texture120_slope; #end #end
#ifdef (L3Color120) #ifndef (MJHMat120) #declare MJHMat120 = L3Color120; #end #end
#ifdef (L3Color120_slope) #ifndef (MJHMat120Slope) #declare MJHMat120Slope = L3Color120_slope; #end #end

// row 90 - Light_Orange
#ifdef (L3Texture125) #ifndef (MJHTex125) #declare MJHTex125 = L3Texture125; #end #end
#ifdef (L3Texture125_slope) #ifndef (MJHTex125Slope) #declare MJHTex125Slope = L3Texture125_slope; #end #end
#ifdef (L3Color125) #ifndef (MJHMat125) #declare MJHMat125 = L3Color125; #end #end
#ifdef (L3Color125_slope) #ifndef (MJHMat125Slope) #declare MJHMat125Slope = L3Color125_slope; #end #end

// row 91 - Dark_Nougat
#ifdef (L3Texture128) #ifndef (MJHTex128) #declare MJHTex128 = L3Texture128; #end #end
#ifdef (L3Texture128_slope) #ifndef (MJHTex128Slope) #declare MJHTex128Slope = L3Texture128_slope; #end #end
#ifdef (L3Color128) #ifndef (MJHMat128) #declare MJHMat128 = L3Color128; #end #end
#ifdef (L3Color128_slope) #ifndef (MJHMat128Slope) #declare MJHMat128Slope = L3Color128_slope; #end #end

// row 92 - Glitter_Trans_Purple
#ifdef (L3Texture129) #ifndef (MJHTex129) #declare MJHTex129 = L3Texture129; #end #end
#ifdef (L3Texture129_slope) #ifndef (MJHTex129Slope) #declare MJHTex129Slope = L3Texture129_slope; #end #end
#ifdef (L3Color129) #ifndef (MJHMat129) #declare MJHMat129 = L3Color129; #end #end
#ifdef (L3Color129_slope) #ifndef (MJHMat129Slope) #declare MJHMat129Slope = L3Color129_slope; #end #end

// row 93 - Speckle_Black_Silver
#ifdef (L3Texture132) #ifndef (MJHTex132) #declare MJHTex132 = L3Texture132; #end #end
#ifdef (L3Texture132_slope) #ifndef (MJHTex132Slope) #declare MJHTex132Slope = L3Texture132_slope; #end #end
#ifdef (L3Color132) #ifndef (MJHMat132) #declare MJHMat132 = L3Color132; #end #end
#ifdef (L3Color132_slope) #ifndef (MJHMat132Slope) #declare MJHMat132Slope = L3Color132_slope; #end #end

// row 94 - Speckle_Black_Gold
#ifdef (L3Texture133) #ifndef (MJHTex133) #declare MJHTex133 = L3Texture133; #end #end
#ifdef (L3Texture133_slope) #ifndef (MJHTex133Slope) #declare MJHTex133Slope = L3Texture133_slope; #end #end
#ifdef (L3Color133) #ifndef (MJHMat133) #declare MJHMat133 = L3Color133; #end #end
#ifdef (L3Color133_slope) #ifndef (MJHMat133Slope) #declare MJHMat133Slope = L3Color133_slope; #end #end

// row 95 - Copper
#ifdef (L3Texture134) #ifndef (MJHTex134) #declare MJHTex134 = L3Texture134; #end #end
#ifdef (L3Texture134_slope) #ifndef (MJHTex134Slope) #declare MJHTex134Slope = L3Texture134_slope; #end #end
#ifdef (L3Color134) #ifndef (MJHMat134) #declare MJHMat134 = L3Color134; #end #end
#ifdef (L3Color134_slope) #ifndef (MJHMat134Slope) #declare MJHMat134Slope = L3Color134_slope; #end #end

// row 96 - Pearl_Light_Grey
#ifdef (L3Texture135) #ifndef (MJHTex135) #declare MJHTex135 = L3Texture135; #end #end
#ifdef (L3Texture135_slope) #ifndef (MJHTex135Slope) #declare MJHTex135Slope = L3Texture135_slope; #end #end
#ifdef (L3Color135) #ifndef (MJHMat135) #declare MJHMat135 = L3Color135; #end #end
#ifdef (L3Color135_slope) #ifndef (MJHMat135Slope) #declare MJHMat135Slope = L3Color135_slope; #end #end

// row 97 - Metal_Blue
#ifdef (L3Texture137) #ifndef (MJHTex137) #declare MJHTex137 = L3Texture137; #end #end
#ifdef (L3Texture137_slope) #ifndef (MJHTex137Slope) #declare MJHTex137Slope = L3Texture137_slope; #end #end
#ifdef (L3Color137) #ifndef (MJHMat137) #declare MJHMat137 = L3Color137; #end #end
#ifdef (L3Color137_slope) #ifndef (MJHMat137Slope) #declare MJHMat137Slope = L3Color137_slope; #end #end

// row 98 - Pearl_Light_Gold
#ifdef (L3Texture142) #ifndef (MJHTex142) #declare MJHTex142 = L3Texture142; #end #end
#ifdef (L3Texture142_slope) #ifndef (MJHTex142Slope) #declare MJHTex142Slope = L3Texture142_slope; #end #end
#ifdef (L3Color142) #ifndef (MJHMat142) #declare MJHMat142 = L3Color142; #end #end
#ifdef (L3Color142_slope) #ifndef (MJHMat142Slope) #declare MJHMat142Slope = L3Color142_slope; #end #end

// row 99 - Pearl_Dark_Grey
#ifdef (L3Texture148) #ifndef (MJHTex148) #declare MJHTex148 = L3Texture148; #end #end
#ifdef (L3Texture148_slope) #ifndef (MJHTex148Slope) #declare MJHTex148Slope = L3Texture148_slope; #end #end
#ifdef (L3Color148) #ifndef (MJHMat148) #declare MJHMat148 = L3Color148; #end #end
#ifdef (L3Color148_slope) #ifndef (MJHMat148Slope) #declare MJHMat148Slope = L3Color148_slope; #end #end

// row 100 - Pearl_Very_Light_Grey
#ifdef (L3Texture150) #ifndef (MJHTex150) #declare MJHTex150 = L3Texture150; #end #end
#ifdef (L3Texture150_slope) #ifndef (MJHTex150Slope) #declare MJHTex150Slope = L3Texture150_slope; #end #end
#ifdef (L3Color150) #ifndef (MJHMat150) #declare MJHMat150 = L3Color150; #end #end
#ifdef (L3Color150_slope) #ifndef (MJHMat150Slope) #declare MJHMat150Slope = L3Color150_slope; #end #end

// row 101 - Very_Light_Bluish_Grey
#ifdef (L3Texture151) #ifndef (MJHTex151) #declare MJHTex151 = L3Texture151; #end #end
#ifdef (L3Texture151_slope) #ifndef (MJHTex151Slope) #declare MJHTex151Slope = L3Texture151_slope; #end #end
#ifdef (L3Color151) #ifndef (MJHMat151) #declare MJHMat151 = L3Color151; #end #end
#ifdef (L3Color151_slope) #ifndef (MJHMat151Slope) #declare MJHMat151Slope = L3Color151_slope; #end #end

// row 102 - Flat_Dark_Gold
#ifdef (L3Texture178) #ifndef (MJHTex178) #declare MJHTex178 = L3Texture178; #end #end
#ifdef (L3Texture178_slope) #ifndef (MJHTex178Slope) #declare MJHTex178Slope = L3Texture178_slope; #end #end
#ifdef (L3Color178) #ifndef (MJHMat178) #declare MJHMat178 = L3Color178; #end #end
#ifdef (L3Color178_slope) #ifndef (MJHMat178Slope) #declare MJHMat178Slope = L3Color178_slope; #end #end

// row 103 - Flat_Silver
#ifdef (L3Texture179) #ifndef (MJHTex179) #declare MJHTex179 = L3Texture179; #end #end
#ifdef (L3Texture179_slope) #ifndef (MJHTex179Slope) #declare MJHTex179Slope = L3Texture179_slope; #end #end
#ifdef (L3Color179) #ifndef (MJHMat179) #declare MJHMat179 = L3Color179; #end #end
#ifdef (L3Color179_slope) #ifndef (MJHMat179Slope) #declare MJHMat179Slope = L3Color179_slope; #end #end

// row 104 - Pearl_White
#ifdef (L3Texture183) #ifndef (MJHTex183) #declare MJHTex183 = L3Texture183; #end #end
#ifdef (L3Texture183_slope) #ifndef (MJHTex183Slope) #declare MJHTex183Slope = L3Texture183_slope; #end #end
#ifdef (L3Color183) #ifndef (MJHMat183) #declare MJHMat183 = L3Color183; #end #end
#ifdef (L3Color183_slope) #ifndef (MJHMat183Slope) #declare MJHMat183Slope = L3Color183_slope; #end #end

// row 105 - Metallic_Bright_Red
#ifdef (L3Texture184) #ifndef (MJHTex184) #declare MJHTex184 = L3Texture184; #end #end
#ifdef (L3Texture184_slope) #ifndef (MJHTex184Slope) #declare MJHTex184Slope = L3Texture184_slope; #end #end
#ifdef (L3Color184) #ifndef (MJHMat184) #declare MJHMat184 = L3Color184; #end #end
#ifdef (L3Color184_slope) #ifndef (MJHMat184Slope) #declare MJHMat184Slope = L3Color184_slope; #end #end

// row 106 - Metallic_Dark_Green
#ifdef (L3Texture186) #ifndef (MJHTex186) #declare MJHTex186 = L3Texture186; #end #end
#ifdef (L3Texture186_slope) #ifndef (MJHTex186Slope) #declare MJHTex186Slope = L3Texture186_slope; #end #end
#ifdef (L3Color186) #ifndef (MJHMat186) #declare MJHMat186 = L3Color186; #end #end
#ifdef (L3Color186_slope) #ifndef (MJHMat186Slope) #declare MJHMat186Slope = L3Color186_slope; #end #end

// row 107 - Reddish_Gold
#ifdef (L3Texture189) #ifndef (MJHTex189) #declare MJHTex189 = L3Texture189; #end #end
#ifdef (L3Texture189_slope) #ifndef (MJHTex189Slope) #declare MJHTex189Slope = L3Texture189_slope; #end #end
#ifdef (L3Color189) #ifndef (MJHMat189) #declare MJHMat189 = L3Color189; #end #end
#ifdef (L3Color189_slope) #ifndef (MJHMat189Slope) #declare MJHMat189Slope = L3Color189_slope; #end #end

// row 108 - Bright_Light_Orange
#ifdef (L3Texture191) #ifndef (MJHTex191) #declare MJHTex191 = L3Texture191; #end #end
#ifdef (L3Texture191_slope) #ifndef (MJHTex191Slope) #declare MJHTex191Slope = L3Texture191_slope; #end #end
#ifdef (L3Color191) #ifndef (MJHMat191) #declare MJHMat191 = L3Color191; #end #end
#ifdef (L3Color191_slope) #ifndef (MJHMat191Slope) #declare MJHMat191Slope = L3Color191_slope; #end #end

// row 109 - Bright_Light_Blue
#ifdef (L3Texture212) #ifndef (MJHTex212) #declare MJHTex212 = L3Texture212; #end #end
#ifdef (L3Texture212_slope) #ifndef (MJHTex212Slope) #declare MJHTex212Slope = L3Texture212_slope; #end #end
#ifdef (L3Color212) #ifndef (MJHMat212) #declare MJHMat212 = L3Color212; #end #end
#ifdef (L3Color212_slope) #ifndef (MJHMat212Slope) #declare MJHMat212Slope = L3Color212_slope; #end #end

// row 110 - Rust
#ifdef (L3Texture216) #ifndef (MJHTex216) #declare MJHTex216 = L3Texture216; #end #end
#ifdef (L3Texture216_slope) #ifndef (MJHTex216Slope) #declare MJHTex216Slope = L3Texture216_slope; #end #end
#ifdef (L3Color216) #ifndef (MJHMat216) #declare MJHMat216 = L3Color216; #end #end
#ifdef (L3Color216_slope) #ifndef (MJHMat216Slope) #declare MJHMat216Slope = L3Color216_slope; #end #end

// row 111 - Reddish_Lilac
#ifdef (L3Texture218) #ifndef (MJHTex218) #declare MJHTex218 = L3Texture218; #end #end
#ifdef (L3Texture218_slope) #ifndef (MJHTex218Slope) #declare MJHTex218Slope = L3Texture218_slope; #end #end
#ifdef (L3Color218) #ifndef (MJHMat218) #declare MJHMat218 = L3Color218; #end #end
#ifdef (L3Color218_slope) #ifndef (MJHMat218Slope) #declare MJHMat218Slope = L3Color218_slope; #end #end

// row 112 - Lilac
#ifdef (L3Texture219) #ifndef (MJHTex219) #declare MJHTex219 = L3Texture219; #end #end
#ifdef (L3Texture219_slope) #ifndef (MJHTex219Slope) #declare MJHTex219Slope = L3Texture219_slope; #end #end
#ifdef (L3Color219) #ifndef (MJHMat219) #declare MJHMat219 = L3Color219; #end #end
#ifdef (L3Color219_slope) #ifndef (MJHMat219Slope) #declare MJHMat219Slope = L3Color219_slope; #end #end

// row 113 - Bright_Light_Yellow
#ifdef (L3Texture226) #ifndef (MJHTex226) #declare MJHTex226 = L3Texture226; #end #end
#ifdef (L3Texture226_slope) #ifndef (MJHTex226Slope) #declare MJHTex226Slope = L3Texture226_slope; #end #end
#ifdef (L3Color226) #ifndef (MJHMat226) #declare MJHMat226 = L3Color226; #end #end
#ifdef (L3Color226_slope) #ifndef (MJHMat226Slope) #declare MJHMat226Slope = L3Color226_slope; #end #end

// row 114 - Trans_Bright_Light_Orange
#ifdef (L3Texture231) #ifndef (MJHTex231) #declare MJHTex231 = L3Texture231; #end #end
#ifdef (L3Texture231_slope) #ifndef (MJHTex231Slope) #declare MJHTex231Slope = L3Texture231_slope; #end #end
#ifdef (L3Color231) #ifndef (MJHMat231) #declare MJHMat231 = L3Color231; #end #end
#ifdef (L3Color231_slope) #ifndef (MJHMat231Slope) #declare MJHMat231Slope = L3Color231_slope; #end #end

// row 115 - Sky_Blue
#ifdef (L3Texture232) #ifndef (MJHTex232) #declare MJHTex232 = L3Texture232; #end #end
#ifdef (L3Texture232_slope) #ifndef (MJHTex232Slope) #declare MJHTex232Slope = L3Texture232_slope; #end #end
#ifdef (L3Color232) #ifndef (MJHMat232) #declare MJHMat232 = L3Color232; #end #end
#ifdef (L3Color232_slope) #ifndef (MJHMat232Slope) #declare MJHMat232Slope = L3Color232_slope; #end #end

// row 116 - Trans_Fire_Yellow
#ifdef (L3Texture234) #ifndef (MJHTex234) #declare MJHTex234 = L3Texture234; #end #end
#ifdef (L3Texture234_slope) #ifndef (MJHTex234Slope) #declare MJHTex234Slope = L3Texture234_slope; #end #end
#ifdef (L3Color234) #ifndef (MJHMat234) #declare MJHMat234 = L3Color234; #end #end
#ifdef (L3Color234_slope) #ifndef (MJHMat234Slope) #declare MJHMat234Slope = L3Color234_slope; #end #end

// row 117 - Rubber_Black
#ifdef (L3Texture256) #ifndef (MJHTex256) #declare MJHTex256 = L3Texture256; #end #end
#ifdef (L3Texture256_slope) #ifndef (MJHTex256Slope) #declare MJHTex256Slope = L3Texture256_slope; #end #end
#ifdef (L3Color256) #ifndef (MJHMat256) #declare MJHMat256 = L3Color256; #end #end
#ifdef (L3Color256_slope) #ifndef (MJHMat256Slope) #declare MJHMat256Slope = L3Color256_slope; #end #end

// row 118 - Dark_Blue
#ifdef (L3Texture272) #ifndef (MJHTex272) #declare MJHTex272 = L3Texture272; #end #end
#ifdef (L3Texture272_slope) #ifndef (MJHTex272Slope) #declare MJHTex272Slope = L3Texture272_slope; #end #end
#ifdef (L3Color272) #ifndef (MJHMat272) #declare MJHMat272 = L3Color272; #end #end
#ifdef (L3Color272_slope) #ifndef (MJHMat272Slope) #declare MJHMat272Slope = L3Color272_slope; #end #end

// row 119 - Rubber_Blue
#ifdef (L3Texture273) #ifndef (MJHTex273) #declare MJHTex273 = L3Texture273; #end #end
#ifdef (L3Texture273_slope) #ifndef (MJHTex273Slope) #declare MJHTex273Slope = L3Texture273_slope; #end #end
#ifdef (L3Color273) #ifndef (MJHMat273) #declare MJHMat273 = L3Color273; #end #end
#ifdef (L3Color273_slope) #ifndef (MJHMat273Slope) #declare MJHMat273Slope = L3Color273_slope; #end #end

// row 120 - Trans_Reddish_Lilac
#ifdef (L3Texture284) #ifndef (MJHTex284) #declare MJHTex284 = L3Texture284; #end #end
#ifdef (L3Texture284_slope) #ifndef (MJHTex284Slope) #declare MJHTex284Slope = L3Texture284_slope; #end #end
#ifdef (L3Color284) #ifndef (MJHMat284) #declare MJHMat284 = L3Color284; #end #end
#ifdef (L3Color284_slope) #ifndef (MJHMat284Slope) #declare MJHMat284Slope = L3Color284_slope; #end #end

// row 121 - Trans_Light_Green
#ifdef (L3Texture285) #ifndef (MJHTex285) #declare MJHTex285 = L3Texture285; #end #end
#ifdef (L3Texture285_slope) #ifndef (MJHTex285Slope) #declare MJHTex285Slope = L3Texture285_slope; #end #end
#ifdef (L3Color285) #ifndef (MJHMat285) #declare MJHMat285 = L3Color285; #end #end
#ifdef (L3Color285_slope) #ifndef (MJHMat285Slope) #declare MJHMat285Slope = L3Color285_slope; #end #end

// row 122 - Dark_Green
#ifdef (L3Texture288) #ifndef (MJHTex288) #declare MJHTex288 = L3Texture288; #end #end
#ifdef (L3Texture288_slope) #ifndef (MJHTex288Slope) #declare MJHTex288Slope = L3Texture288_slope; #end #end
#ifdef (L3Color288) #ifndef (MJHMat288) #declare MJHMat288 = L3Color288; #end #end
#ifdef (L3Color288_slope) #ifndef (MJHMat288Slope) #declare MJHMat288Slope = L3Color288_slope; #end #end

// row 123 - Trans_Light_Blue_Violet
#ifdef (L3Texture293) #ifndef (MJHTex293) #declare MJHTex293 = L3Texture293; #end #end
#ifdef (L3Texture293_slope) #ifndef (MJHTex293Slope) #declare MJHTex293Slope = L3Texture293_slope; #end #end
#ifdef (L3Color293) #ifndef (MJHMat293) #declare MJHMat293 = L3Color293; #end #end
#ifdef (L3Color293_slope) #ifndef (MJHMat293Slope) #declare MJHMat293Slope = L3Color293_slope; #end #end

// row 124 - Glow_In_Dark_Trans
#ifdef (L3Texture294) #ifndef (MJHTex294) #declare MJHTex294 = L3Texture294; #end #end
#ifdef (L3Texture294_slope) #ifndef (MJHTex294Slope) #declare MJHTex294Slope = L3Texture294_slope; #end #end
#ifdef (L3Color294) #ifndef (MJHMat294) #declare MJHMat294 = L3Color294; #end #end
#ifdef (L3Color294_slope) #ifndef (MJHMat294Slope) #declare MJHMat294Slope = L3Color294_slope; #end #end

// row 125 - Flamingo_Pink
#ifdef (L3Texture295) #ifndef (MJHTex295) #declare MJHTex295 = L3Texture295; #end #end
#ifdef (L3Texture295_slope) #ifndef (MJHTex295Slope) #declare MJHTex295Slope = L3Texture295_slope; #end #end
#ifdef (L3Color295) #ifndef (MJHMat295) #declare MJHMat295 = L3Color295; #end #end
#ifdef (L3Color295_slope) #ifndef (MJHMat295Slope) #declare MJHMat295Slope = L3Color295_slope; #end #end

// row 126 - Pearl_Gold
#ifdef (L3Texture297) #ifndef (MJHTex297) #declare MJHTex297 = L3Texture297; #end #end
#ifdef (L3Texture297_slope) #ifndef (MJHTex297Slope) #declare MJHTex297Slope = L3Texture297_slope; #end #end
#ifdef (L3Color297) #ifndef (MJHMat297) #declare MJHMat297 = L3Color297; #end #end
#ifdef (L3Color297_slope) #ifndef (MJHMat297Slope) #declare MJHMat297Slope = L3Color297_slope; #end #end

// row 127 - Metallic_Copper
#ifdef (L3Texture300) #ifndef (MJHTex300) #declare MJHTex300 = L3Texture300; #end #end
#ifdef (L3Texture300_slope) #ifndef (MJHTex300Slope) #declare MJHTex300Slope = L3Texture300_slope; #end #end
#ifdef (L3Color300) #ifndef (MJHMat300) #declare MJHMat300 = L3Color300; #end #end
#ifdef (L3Color300_slope) #ifndef (MJHMat300Slope) #declare MJHMat300Slope = L3Color300_slope; #end #end

// row 128 - Glitter_Trans_Light_Blue
#ifdef (L3Texture302) #ifndef (MJHTex302) #declare MJHTex302 = L3Texture302; #end #end
#ifdef (L3Texture302_slope) #ifndef (MJHTex302Slope) #declare MJHTex302Slope = L3Texture302_slope; #end #end
#ifdef (L3Color302) #ifndef (MJHMat302) #declare MJHMat302 = L3Color302; #end #end
#ifdef (L3Color302_slope) #ifndef (MJHMat302Slope) #declare MJHMat302Slope = L3Color302_slope; #end #end

// row 129 - Dark_Brown
#ifdef (L3Texture308) #ifndef (MJHTex308) #declare MJHTex308 = L3Texture308; #end #end
#ifdef (L3Texture308_slope) #ifndef (MJHTex308Slope) #declare MJHTex308Slope = L3Texture308_slope; #end #end
#ifdef (L3Color308) #ifndef (MJHMat308) #declare MJHMat308 = L3Color308; #end #end
#ifdef (L3Color308_slope) #ifndef (MJHMat308Slope) #declare MJHMat308Slope = L3Color308_slope; #end #end

// row 130 - Maersk_Blue
#ifdef (L3Texture313) #ifndef (MJHTex313) #declare MJHTex313 = L3Texture313; #end #end
#ifdef (L3Texture313_slope) #ifndef (MJHTex313Slope) #declare MJHTex313Slope = L3Texture313_slope; #end #end
#ifdef (L3Color313) #ifndef (MJHMat313) #declare MJHMat313 = L3Color313; #end #end
#ifdef (L3Color313_slope) #ifndef (MJHMat313Slope) #declare MJHMat313Slope = L3Color313_slope; #end #end

// row 131 - Dark_Red
#ifdef (L3Texture320) #ifndef (MJHTex320) #declare MJHTex320 = L3Texture320; #end #end
#ifdef (L3Texture320_slope) #ifndef (MJHTex320Slope) #declare MJHTex320Slope = L3Texture320_slope; #end #end
#ifdef (L3Color320) #ifndef (MJHMat320) #declare MJHMat320 = L3Color320; #end #end
#ifdef (L3Color320_slope) #ifndef (MJHMat320Slope) #declare MJHMat320Slope = L3Color320_slope; #end #end

// row 132 - Dark_Azure
#ifdef (L3Texture321) #ifndef (MJHTex321) #declare MJHTex321 = L3Texture321; #end #end
#ifdef (L3Texture321_slope) #ifndef (MJHTex321Slope) #declare MJHTex321Slope = L3Texture321_slope; #end #end
#ifdef (L3Color321) #ifndef (MJHMat321) #declare MJHMat321 = L3Color321; #end #end
#ifdef (L3Color321_slope) #ifndef (MJHMat321Slope) #declare MJHMat321Slope = L3Color321_slope; #end #end

// row 133 - Medium_Azure
#ifdef (L3Texture322) #ifndef (MJHTex322) #declare MJHTex322 = L3Texture322; #end #end
#ifdef (L3Texture322_slope) #ifndef (MJHTex322Slope) #declare MJHTex322Slope = L3Texture322_slope; #end #end
#ifdef (L3Color322) #ifndef (MJHMat322) #declare MJHMat322 = L3Color322; #end #end
#ifdef (L3Color322_slope) #ifndef (MJHMat322Slope) #declare MJHMat322Slope = L3Color322_slope; #end #end

// row 134 - Light_Aqua
#ifdef (L3Texture323) #ifndef (MJHTex323) #declare MJHTex323 = L3Texture323; #end #end
#ifdef (L3Texture323_slope) #ifndef (MJHTex323Slope) #declare MJHTex323Slope = L3Texture323_slope; #end #end
#ifdef (L3Color323) #ifndef (MJHMat323) #declare MJHMat323 = L3Color323; #end #end
#ifdef (L3Color323_slope) #ifndef (MJHMat323Slope) #declare MJHMat323Slope = L3Color323_slope; #end #end

// row 135 - Rubber_Red
#ifdef (L3Texture324) #ifndef (MJHTex324) #declare MJHTex324 = L3Texture324; #end #end
#ifdef (L3Texture324_slope) #ifndef (MJHTex324Slope) #declare MJHTex324Slope = L3Texture324_slope; #end #end
#ifdef (L3Color324) #ifndef (MJHMat324) #declare MJHMat324 = L3Color324; #end #end
#ifdef (L3Color324_slope) #ifndef (MJHMat324Slope) #declare MJHMat324Slope = L3Color324_slope; #end #end

// row 136 - Yellowish_Green
#ifdef (L3Texture326) #ifndef (MJHTex326) #declare MJHTex326 = L3Texture326; #end #end
#ifdef (L3Texture326_slope) #ifndef (MJHTex326Slope) #declare MJHTex326Slope = L3Texture326_slope; #end #end
#ifdef (L3Color326) #ifndef (MJHMat326) #declare MJHMat326 = L3Color326; #end #end
#ifdef (L3Color326_slope) #ifndef (MJHMat326Slope) #declare MJHMat326Slope = L3Color326_slope; #end #end

// row 137 - Glow_In_Dark_White
#ifdef (L3Texture329) #ifndef (MJHTex329) #declare MJHTex329 = L3Texture329; #end #end
#ifdef (L3Texture329_slope) #ifndef (MJHTex329Slope) #declare MJHTex329Slope = L3Texture329_slope; #end #end
#ifdef (L3Color329) #ifndef (MJHMat329) #declare MJHMat329 = L3Color329; #end #end
#ifdef (L3Color329_slope) #ifndef (MJHMat329Slope) #declare MJHMat329Slope = L3Color329_slope; #end #end

// row 138 - Olive_Green
#ifdef (L3Texture330) #ifndef (MJHTex330) #declare MJHTex330 = L3Texture330; #end #end
#ifdef (L3Texture330_slope) #ifndef (MJHTex330Slope) #declare MJHTex330Slope = L3Texture330_slope; #end #end
#ifdef (L3Color330) #ifndef (MJHMat330) #declare MJHMat330 = L3Color330; #end #end
#ifdef (L3Color330_slope) #ifndef (MJHMat330Slope) #declare MJHMat330Slope = L3Color330_slope; #end #end

// row 139 - Chrome_Gold
#ifdef (L3Texture334) #ifndef (MJHTex334) #declare MJHTex334 = L3Texture334; #end #end
#ifdef (L3Texture334_slope) #ifndef (MJHTex334Slope) #declare MJHTex334Slope = L3Texture334_slope; #end #end
#ifdef (L3Color334) #ifndef (MJHMat334) #declare MJHMat334 = L3Color334; #end #end
#ifdef (L3Color334_slope) #ifndef (MJHMat334Slope) #declare MJHMat334Slope = L3Color334_slope; #end #end

// row 140 - Sand_Red
#ifdef (L3Texture335) #ifndef (MJHTex335) #declare MJHTex335 = L3Texture335; #end #end
#ifdef (L3Texture335_slope) #ifndef (MJHTex335Slope) #declare MJHTex335Slope = L3Texture335_slope; #end #end
#ifdef (L3Color335) #ifndef (MJHMat335) #declare MJHMat335 = L3Color335; #end #end
#ifdef (L3Color335_slope) #ifndef (MJHMat335Slope) #declare MJHMat335Slope = L3Color335_slope; #end #end

// row 141 - Glitter_Trans_Neon_Green
#ifdef (L3Texture339) #ifndef (MJHTex339) #declare MJHTex339 = L3Texture339; #end #end
#ifdef (L3Texture339_slope) #ifndef (MJHTex339Slope) #declare MJHTex339Slope = L3Texture339_slope; #end #end
#ifdef (L3Color339) #ifndef (MJHMat339) #declare MJHMat339 = L3Color339; #end #end
#ifdef (L3Color339_slope) #ifndef (MJHMat339Slope) #declare MJHMat339Slope = L3Color339_slope; #end #end

// row 142 - Rubber_Orange
#ifdef (L3Texture350) #ifndef (MJHTex350) #declare MJHTex350 = L3Texture350; #end #end
#ifdef (L3Texture350_slope) #ifndef (MJHTex350Slope) #declare MJHTex350Slope = L3Texture350_slope; #end #end
#ifdef (L3Color350) #ifndef (MJHMat350) #declare MJHMat350 = L3Color350; #end #end
#ifdef (L3Color350_slope) #ifndef (MJHMat350Slope) #declare MJHMat350Slope = L3Color350_slope; #end #end

// row 143 - Medium_Dark_Pink
#ifdef (L3Texture351) #ifndef (MJHTex351) #declare MJHTex351 = L3Texture351; #end #end
#ifdef (L3Texture351_slope) #ifndef (MJHTex351Slope) #declare MJHTex351Slope = L3Texture351_slope; #end #end
#ifdef (L3Color351) #ifndef (MJHMat351) #declare MJHMat351 = L3Color351; #end #end
#ifdef (L3Color351_slope) #ifndef (MJHMat351Slope) #declare MJHMat351Slope = L3Color351_slope; #end #end

// row 145 - Earth_Orange
#ifdef (L3Texture366) #ifndef (MJHTex366) #declare MJHTex366 = L3Texture366; #end #end
#ifdef (L3Texture366_slope) #ifndef (MJHTex366Slope) #declare MJHTex366Slope = L3Texture366_slope; #end #end
#ifdef (L3Color366) #ifndef (MJHMat366) #declare MJHMat366 = L3Color366; #end #end
#ifdef (L3Color366_slope) #ifndef (MJHMat366Slope) #declare MJHMat366Slope = L3Color366_slope; #end #end

// row 146 - Sand_Purple
#ifdef (L3Texture373) #ifndef (MJHTex373) #declare MJHTex373 = L3Texture373; #end #end
#ifdef (L3Texture373_slope) #ifndef (MJHTex373Slope) #declare MJHTex373Slope = L3Texture373_slope; #end #end
#ifdef (L3Color373) #ifndef (MJHMat373) #declare MJHMat373 = L3Color373; #end #end
#ifdef (L3Color373_slope) #ifndef (MJHMat373Slope) #declare MJHMat373Slope = L3Color373_slope; #end #end

// row 147 - Rubber_Light_Grey
#ifdef (L3Texture375) #ifndef (MJHTex375) #declare MJHTex375 = L3Texture375; #end #end
#ifdef (L3Texture375_slope) #ifndef (MJHTex375Slope) #declare MJHTex375Slope = L3Texture375_slope; #end #end
#ifdef (L3Color375) #ifndef (MJHMat375) #declare MJHMat375 = L3Color375; #end #end
#ifdef (L3Color375_slope) #ifndef (MJHMat375Slope) #declare MJHMat375Slope = L3Color375_slope; #end #end

// row 148 - Sand_Green
#ifdef (L3Texture378) #ifndef (MJHTex378) #declare MJHTex378 = L3Texture378; #end #end
#ifdef (L3Texture378_slope) #ifndef (MJHTex378Slope) #declare MJHTex378Slope = L3Texture378_slope; #end #end
#ifdef (L3Color378) #ifndef (MJHMat378) #declare MJHMat378 = L3Color378; #end #end
#ifdef (L3Color378_slope) #ifndef (MJHMat378Slope) #declare MJHMat378Slope = L3Color378_slope; #end #end

// row 149 - Sand_Blue
#ifdef (L3Texture379) #ifndef (MJHTex379) #declare MJHTex379 = L3Texture379; #end #end
#ifdef (L3Texture379_slope) #ifndef (MJHTex379Slope) #declare MJHTex379Slope = L3Texture379_slope; #end #end
#ifdef (L3Color379) #ifndef (MJHMat379) #declare MJHMat379 = L3Color379; #end #end
#ifdef (L3Color379_slope) #ifndef (MJHMat379Slope) #declare MJHMat379Slope = L3Color379_slope; #end #end

// row 150 - Chrome_Silver
#ifdef (L3Texture383) #ifndef (MJHTex383) #declare MJHTex383 = L3Texture383; #end #end
#ifdef (L3Texture383_slope) #ifndef (MJHTex383Slope) #declare MJHTex383Slope = L3Texture383_slope; #end #end
#ifdef (L3Color383) #ifndef (MJHMat383) #declare MJHMat383 = L3Color383; #end #end
#ifdef (L3Color383_slope) #ifndef (MJHMat383Slope) #declare MJHMat383Slope = L3Color383_slope; #end #end

// row 151 - Rubber_Dark_Blue
#ifdef (L3Texture406) #ifndef (MJHTex406) #declare MJHTex406 = L3Texture406; #end #end
#ifdef (L3Texture406_slope) #ifndef (MJHTex406Slope) #declare MJHTex406Slope = L3Texture406_slope; #end #end
#ifdef (L3Color406) #ifndef (MJHMat406) #declare MJHMat406 = L3Color406; #end #end
#ifdef (L3Color406_slope) #ifndef (MJHMat406Slope) #declare MJHMat406Slope = L3Color406_slope; #end #end

// row 152 - Rubber_Purple
#ifdef (L3Texture449) #ifndef (MJHTex449) #declare MJHTex449 = L3Texture449; #end #end
#ifdef (L3Texture449_slope) #ifndef (MJHTex449Slope) #declare MJHTex449Slope = L3Texture449_slope; #end #end
#ifdef (L3Color449) #ifndef (MJHMat449) #declare MJHMat449 = L3Color449; #end #end
#ifdef (L3Color449_slope) #ifndef (MJHMat449Slope) #declare MJHMat449Slope = L3Color449_slope; #end #end

// row 153 - Fabuland_Brown
#ifdef (L3Texture450) #ifndef (MJHTex450) #declare MJHTex450 = L3Texture450; #end #end
#ifdef (L3Texture450_slope) #ifndef (MJHTex450Slope) #declare MJHTex450Slope = L3Texture450_slope; #end #end
#ifdef (L3Color450) #ifndef (MJHMat450) #declare MJHMat450 = L3Color450; #end #end
#ifdef (L3Color450_slope) #ifndef (MJHMat450Slope) #declare MJHMat450Slope = L3Color450_slope; #end #end

// row 154 - Medium_Orange
#ifdef (L3Texture462) #ifndef (MJHTex462) #declare MJHTex462 = L3Texture462; #end #end
#ifdef (L3Texture462_slope) #ifndef (MJHTex462Slope) #declare MJHTex462Slope = L3Texture462_slope; #end #end
#ifdef (L3Color462) #ifndef (MJHMat462) #declare MJHMat462 = L3Color462; #end #end
#ifdef (L3Color462_slope) #ifndef (MJHMat462Slope) #declare MJHMat462Slope = L3Color462_slope; #end #end

// row 155 - Dark_Orange
#ifdef (L3Texture484) #ifndef (MJHTex484) #declare MJHTex484 = L3Texture484; #end #end
#ifdef (L3Texture484_slope) #ifndef (MJHTex484Slope) #declare MJHTex484Slope = L3Texture484_slope; #end #end
#ifdef (L3Color484) #ifndef (MJHMat484) #declare MJHMat484 = L3Color484; #end #end
#ifdef (L3Color484_slope) #ifndef (MJHMat484Slope) #declare MJHMat484Slope = L3Color484_slope; #end #end

// row 156 - Rubber_Lime
#ifdef (L3Texture490) #ifndef (MJHTex490) #declare MJHTex490 = L3Texture490; #end #end
#ifdef (L3Texture490_slope) #ifndef (MJHTex490Slope) #declare MJHTex490Slope = L3Texture490_slope; #end #end
#ifdef (L3Color490) #ifndef (MJHMat490) #declare MJHMat490 = L3Color490; #end #end
#ifdef (L3Color490_slope) #ifndef (MJHMat490Slope) #declare MJHMat490Slope = L3Color490_slope; #end #end

// row 157 - Magnet
#ifdef (L3Texture493) #ifndef (MJHTex493) #declare MJHTex493 = L3Texture493; #end #end
#ifdef (L3Texture493_slope) #ifndef (MJHTex493Slope) #declare MJHTex493Slope = L3Texture493_slope; #end #end
#ifdef (L3Color493) #ifndef (MJHMat493) #declare MJHMat493 = L3Color493; #end #end
#ifdef (L3Color493_slope) #ifndef (MJHMat493Slope) #declare MJHMat493Slope = L3Color493_slope; #end #end

// row 158 - Electric_Contact_Alloy
#ifdef (L3Texture494) #ifndef (MJHTex494) #declare MJHTex494 = L3Texture494; #end #end
#ifdef (L3Texture494_slope) #ifndef (MJHTex494Slope) #declare MJHTex494Slope = L3Texture494_slope; #end #end
#ifdef (L3Color494) #ifndef (MJHMat494) #declare MJHMat494 = L3Color494; #end #end
#ifdef (L3Color494_slope) #ifndef (MJHMat494Slope) #declare MJHMat494Slope = L3Color494_slope; #end #end

// row 159 - Electric_Contact_Copper
#ifdef (L3Texture495) #ifndef (MJHTex495) #declare MJHTex495 = L3Texture495; #end #end
#ifdef (L3Texture495_slope) #ifndef (MJHTex495Slope) #declare MJHTex495Slope = L3Texture495_slope; #end #end
#ifdef (L3Color495) #ifndef (MJHMat495) #declare MJHMat495 = L3Color495; #end #end
#ifdef (L3Color495_slope) #ifndef (MJHMat495Slope) #declare MJHMat495Slope = L3Color495_slope; #end #end

// row 160 - Rubber_Light_Bluish_Grey
#ifdef (L3Texture496) #ifndef (MJHTex496) #declare MJHTex496 = L3Texture496; #end #end
#ifdef (L3Texture496_slope) #ifndef (MJHTex496Slope) #declare MJHTex496Slope = L3Texture496_slope; #end #end
#ifdef (L3Color496) #ifndef (MJHMat496) #declare MJHMat496 = L3Color496; #end #end
#ifdef (L3Color496_slope) #ifndef (MJHMat496Slope) #declare MJHMat496Slope = L3Color496_slope; #end #end

// row 161 - Very_Light_Grey
#ifdef (L3Texture503) #ifndef (MJHTex503) #declare MJHTex503 = L3Texture503; #end #end
#ifdef (L3Texture503_slope) #ifndef (MJHTex503Slope) #declare MJHTex503Slope = L3Texture503_slope; #end #end
#ifdef (L3Color503) #ifndef (MJHMat503) #declare MJHMat503 = L3Color503; #end #end
#ifdef (L3Color503_slope) #ifndef (MJHMat503Slope) #declare MJHMat503Slope = L3Color503_slope; #end #end

// row 162 - Rubber_Flat_Silver
#ifdef (L3Texture504) #ifndef (MJHTex504) #declare MJHTex504 = L3Texture504; #end #end
#ifdef (L3Texture504_slope) #ifndef (MJHTex504Slope) #declare MJHTex504Slope = L3Texture504_slope; #end #end
#ifdef (L3Color504) #ifndef (MJHMat504) #declare MJHMat504 = L3Color504; #end #end
#ifdef (L3Color504_slope) #ifndef (MJHMat504Slope) #declare MJHMat504Slope = L3Color504_slope; #end #end

// row 166 - Rubber_White
#ifdef (L3Texture511) #ifndef (MJHTex511) #declare MJHTex511 = L3Texture511; #end #end
#ifdef (L3Texture511_slope) #ifndef (MJHTex511Slope) #declare MJHTex511Slope = L3Texture511_slope; #end #end
#ifdef (L3Color511) #ifndef (MJHMat511) #declare MJHMat511 = L3Color511; #end #end
#ifdef (L3Color511_slope) #ifndef (MJHMat511Slope) #declare MJHMat511Slope = L3Color511_slope; #end #end
