// POV-Ray scripts for LDraw models and scenes
// Copyright (C) 2019  Michael Horvath
// 
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
// 
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA


// row 1 - Black
#ifndef (MJHTex0) #declare MJHTex0 = texture {MJHMissingTex} #end
#ifndef (MJHTex0Slope) #declare MJHTex0Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat0) #declare MJHMat0 = material {MJHMissingMat} #end
#ifndef (MJHMat0Slope) #declare MJHMat0Slope = material {MJHMissingMat} #end

// row 2 - Blue
#ifndef (MJHTex1) #declare MJHTex1 = texture {MJHMissingTex} #end
#ifndef (MJHTex1Slope) #declare MJHTex1Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat1) #declare MJHMat1 = material {MJHMissingMat} #end
#ifndef (MJHMat1Slope) #declare MJHMat1Slope = material {MJHMissingMat} #end

// row 3 - Green
#ifndef (MJHTex2) #declare MJHTex2 = texture {MJHMissingTex} #end
#ifndef (MJHTex2Slope) #declare MJHTex2Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat2) #declare MJHMat2 = material {MJHMissingMat} #end
#ifndef (MJHMat2Slope) #declare MJHMat2Slope = material {MJHMissingMat} #end

// row 4 - Dark_Turquoise
#ifndef (MJHTex3) #declare MJHTex3 = texture {MJHMissingTex} #end
#ifndef (MJHTex3Slope) #declare MJHTex3Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat3) #declare MJHMat3 = material {MJHMissingMat} #end
#ifndef (MJHMat3Slope) #declare MJHMat3Slope = material {MJHMissingMat} #end

// row 5 - Red
#ifndef (MJHTex4) #declare MJHTex4 = texture {MJHMissingTex} #end
#ifndef (MJHTex4Slope) #declare MJHTex4Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat4) #declare MJHMat4 = material {MJHMissingMat} #end
#ifndef (MJHMat4Slope) #declare MJHMat4Slope = material {MJHMissingMat} #end

// row 6 - Dark_Pink
#ifndef (MJHTex5) #declare MJHTex5 = texture {MJHMissingTex} #end
#ifndef (MJHTex5Slope) #declare MJHTex5Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat5) #declare MJHMat5 = material {MJHMissingMat} #end
#ifndef (MJHMat5Slope) #declare MJHMat5Slope = material {MJHMissingMat} #end

// row 7 - Brown
#ifndef (MJHTex6) #declare MJHTex6 = texture {MJHMissingTex} #end
#ifndef (MJHTex6Slope) #declare MJHTex6Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat6) #declare MJHMat6 = material {MJHMissingMat} #end
#ifndef (MJHMat6Slope) #declare MJHMat6Slope = material {MJHMissingMat} #end

// row 8 - Light_Grey
#ifndef (MJHTex7) #declare MJHTex7 = texture {MJHMissingTex} #end
#ifndef (MJHTex7Slope) #declare MJHTex7Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat7) #declare MJHMat7 = material {MJHMissingMat} #end
#ifndef (MJHMat7Slope) #declare MJHMat7Slope = material {MJHMissingMat} #end

// row 9 - Dark_Grey
#ifndef (MJHTex8) #declare MJHTex8 = texture {MJHMissingTex} #end
#ifndef (MJHTex8Slope) #declare MJHTex8Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat8) #declare MJHMat8 = material {MJHMissingMat} #end
#ifndef (MJHMat8Slope) #declare MJHMat8Slope = material {MJHMissingMat} #end

// row 10 - Light_Blue
#ifndef (MJHTex9) #declare MJHTex9 = texture {MJHMissingTex} #end
#ifndef (MJHTex9Slope) #declare MJHTex9Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat9) #declare MJHMat9 = material {MJHMissingMat} #end
#ifndef (MJHMat9Slope) #declare MJHMat9Slope = material {MJHMissingMat} #end

// row 11 - Bright_Green
#ifndef (MJHTex10) #declare MJHTex10 = texture {MJHMissingTex} #end
#ifndef (MJHTex10Slope) #declare MJHTex10Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat10) #declare MJHMat10 = material {MJHMissingMat} #end
#ifndef (MJHMat10Slope) #declare MJHMat10Slope = material {MJHMissingMat} #end

// row 12 - Light_Turquoise
#ifndef (MJHTex11) #declare MJHTex11 = texture {MJHMissingTex} #end
#ifndef (MJHTex11Slope) #declare MJHTex11Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat11) #declare MJHMat11 = material {MJHMissingMat} #end
#ifndef (MJHMat11Slope) #declare MJHMat11Slope = material {MJHMissingMat} #end

// row 13 - Salmon
#ifndef (MJHTex12) #declare MJHTex12 = texture {MJHMissingTex} #end
#ifndef (MJHTex12Slope) #declare MJHTex12Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat12) #declare MJHMat12 = material {MJHMissingMat} #end
#ifndef (MJHMat12Slope) #declare MJHMat12Slope = material {MJHMissingMat} #end

// row 14 - Pink
#ifndef (MJHTex13) #declare MJHTex13 = texture {MJHMissingTex} #end
#ifndef (MJHTex13Slope) #declare MJHTex13Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat13) #declare MJHMat13 = material {MJHMissingMat} #end
#ifndef (MJHMat13Slope) #declare MJHMat13Slope = material {MJHMissingMat} #end

// row 15 - Yellow
#ifndef (MJHTex14) #declare MJHTex14 = texture {MJHMissingTex} #end
#ifndef (MJHTex14Slope) #declare MJHTex14Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat14) #declare MJHMat14 = material {MJHMissingMat} #end
#ifndef (MJHMat14Slope) #declare MJHMat14Slope = material {MJHMissingMat} #end

// row 16 - White
#ifndef (MJHTex15) #declare MJHTex15 = texture {MJHMissingTex} #end
#ifndef (MJHTex15Slope) #declare MJHTex15Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat15) #declare MJHMat15 = material {MJHMissingMat} #end
#ifndef (MJHMat15Slope) #declare MJHMat15Slope = material {MJHMissingMat} #end

// row 17 - Main_Colour
#ifndef (MJHTex16) #declare MJHTex16 = texture {MJHMissingTex} #end
#ifndef (MJHTex16Slope) #declare MJHTex16Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat16) #declare MJHMat16 = material {MJHMissingMat} #end
#ifndef (MJHMat16Slope) #declare MJHMat16Slope = material {MJHMissingMat} #end

// row 18 - Light_Green
#ifndef (MJHTex17) #declare MJHTex17 = texture {MJHMissingTex} #end
#ifndef (MJHTex17Slope) #declare MJHTex17Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat17) #declare MJHMat17 = material {MJHMissingMat} #end
#ifndef (MJHMat17Slope) #declare MJHMat17Slope = material {MJHMissingMat} #end

// row 19 - Light_Yellow
#ifndef (MJHTex18) #declare MJHTex18 = texture {MJHMissingTex} #end
#ifndef (MJHTex18Slope) #declare MJHTex18Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat18) #declare MJHMat18 = material {MJHMissingMat} #end
#ifndef (MJHMat18Slope) #declare MJHMat18Slope = material {MJHMissingMat} #end

// row 20 - Tan
#ifndef (MJHTex19) #declare MJHTex19 = texture {MJHMissingTex} #end
#ifndef (MJHTex19Slope) #declare MJHTex19Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat19) #declare MJHMat19 = material {MJHMissingMat} #end
#ifndef (MJHMat19Slope) #declare MJHMat19Slope = material {MJHMissingMat} #end

// row 21 - Light_Violet
#ifndef (MJHTex20) #declare MJHTex20 = texture {MJHMissingTex} #end
#ifndef (MJHTex20Slope) #declare MJHTex20Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat20) #declare MJHMat20 = material {MJHMissingMat} #end
#ifndef (MJHMat20Slope) #declare MJHMat20Slope = material {MJHMissingMat} #end

// row 22 - Glow_In_Dark_Opaque
#ifndef (MJHTex21) #declare MJHTex21 = texture {MJHMissingTex} #end
#ifndef (MJHTex21Slope) #declare MJHTex21Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat21) #declare MJHMat21 = material {MJHMissingMat} #end
#ifndef (MJHMat21Slope) #declare MJHMat21Slope = material {MJHMissingMat} #end

// row 23 - Purple
#ifndef (MJHTex22) #declare MJHTex22 = texture {MJHMissingTex} #end
#ifndef (MJHTex22Slope) #declare MJHTex22Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat22) #declare MJHMat22 = material {MJHMissingMat} #end
#ifndef (MJHMat22Slope) #declare MJHMat22Slope = material {MJHMissingMat} #end

// row 24 - Dark_Blue_Violet
#ifndef (MJHTex23) #declare MJHTex23 = texture {MJHMissingTex} #end
#ifndef (MJHTex23Slope) #declare MJHTex23Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat23) #declare MJHMat23 = material {MJHMissingMat} #end
#ifndef (MJHMat23Slope) #declare MJHMat23Slope = material {MJHMissingMat} #end

// row 25 - Edge_Colour
#ifndef (MJHTex24) #declare MJHTex24 = texture {MJHMissingTex} #end
#ifndef (MJHTex24Slope) #declare MJHTex24Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat24) #declare MJHMat24 = material {MJHMissingMat} #end
#ifndef (MJHMat24Slope) #declare MJHMat24Slope = material {MJHMissingMat} #end

// row 26 - Orange
#ifndef (MJHTex25) #declare MJHTex25 = texture {MJHMissingTex} #end
#ifndef (MJHTex25Slope) #declare MJHTex25Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat25) #declare MJHMat25 = material {MJHMissingMat} #end
#ifndef (MJHMat25Slope) #declare MJHMat25Slope = material {MJHMissingMat} #end

// row 27 - Magenta
#ifndef (MJHTex26) #declare MJHTex26 = texture {MJHMissingTex} #end
#ifndef (MJHTex26Slope) #declare MJHTex26Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat26) #declare MJHMat26 = material {MJHMissingMat} #end
#ifndef (MJHMat26Slope) #declare MJHMat26Slope = material {MJHMissingMat} #end

// row 28 - Lime
#ifndef (MJHTex27) #declare MJHTex27 = texture {MJHMissingTex} #end
#ifndef (MJHTex27Slope) #declare MJHTex27Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat27) #declare MJHMat27 = material {MJHMissingMat} #end
#ifndef (MJHMat27Slope) #declare MJHMat27Slope = material {MJHMissingMat} #end

// row 29 - Dark_Tan
#ifndef (MJHTex28) #declare MJHTex28 = texture {MJHMissingTex} #end
#ifndef (MJHTex28Slope) #declare MJHTex28Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat28) #declare MJHMat28 = material {MJHMissingMat} #end
#ifndef (MJHMat28Slope) #declare MJHMat28Slope = material {MJHMissingMat} #end

// row 30 - Bright_Pink
#ifndef (MJHTex29) #declare MJHTex29 = texture {MJHMissingTex} #end
#ifndef (MJHTex29Slope) #declare MJHTex29Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat29) #declare MJHMat29 = material {MJHMissingMat} #end
#ifndef (MJHMat29Slope) #declare MJHMat29Slope = material {MJHMissingMat} #end

// row 31 - Medium_Lavender
#ifndef (MJHTex30) #declare MJHTex30 = texture {MJHMissingTex} #end
#ifndef (MJHTex30Slope) #declare MJHTex30Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat30) #declare MJHMat30 = material {MJHMissingMat} #end
#ifndef (MJHMat30Slope) #declare MJHMat30Slope = material {MJHMissingMat} #end

// row 32 - Lavender
#ifndef (MJHTex31) #declare MJHTex31 = texture {MJHMissingTex} #end
#ifndef (MJHTex31Slope) #declare MJHTex31Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat31) #declare MJHMat31 = material {MJHMissingMat} #end
#ifndef (MJHMat31Slope) #declare MJHMat31Slope = material {MJHMissingMat} #end

// row 33 - Trans_Black_IR_Lens
#ifndef (MJHTex32) #declare MJHTex32 = texture {MJHMissingTex} #end
#ifndef (MJHTex32Slope) #declare MJHTex32Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat32) #declare MJHMat32 = material {MJHMissingMat} #end
#ifndef (MJHMat32Slope) #declare MJHMat32Slope = material {MJHMissingMat} #end

// row 34 - Trans_Dark_Blue
#ifndef (MJHTex33) #declare MJHTex33 = texture {MJHMissingTex} #end
#ifndef (MJHTex33Slope) #declare MJHTex33Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat33) #declare MJHMat33 = material {MJHMissingMat} #end
#ifndef (MJHMat33Slope) #declare MJHMat33Slope = material {MJHMissingMat} #end

// row 35 - Trans_Green
#ifndef (MJHTex34) #declare MJHTex34 = texture {MJHMissingTex} #end
#ifndef (MJHTex34Slope) #declare MJHTex34Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat34) #declare MJHMat34 = material {MJHMissingMat} #end
#ifndef (MJHMat34Slope) #declare MJHMat34Slope = material {MJHMissingMat} #end

// row 36 - Trans_Bright_Green
#ifndef (MJHTex35) #declare MJHTex35 = texture {MJHMissingTex} #end
#ifndef (MJHTex35Slope) #declare MJHTex35Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat35) #declare MJHMat35 = material {MJHMissingMat} #end
#ifndef (MJHMat35Slope) #declare MJHMat35Slope = material {MJHMissingMat} #end

// row 37 - Trans_Red
#ifndef (MJHTex36) #declare MJHTex36 = texture {MJHMissingTex} #end
#ifndef (MJHTex36Slope) #declare MJHTex36Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat36) #declare MJHMat36 = material {MJHMissingMat} #end
#ifndef (MJHMat36Slope) #declare MJHMat36Slope = material {MJHMissingMat} #end

// row 38 - Trans_Dark_Pink
#ifndef (MJHTex37) #declare MJHTex37 = texture {MJHMissingTex} #end
#ifndef (MJHTex37Slope) #declare MJHTex37Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat37) #declare MJHMat37 = material {MJHMissingMat} #end
#ifndef (MJHMat37Slope) #declare MJHMat37Slope = material {MJHMissingMat} #end

// row 39 - Trans_Neon_Orange
#ifndef (MJHTex38) #declare MJHTex38 = texture {MJHMissingTex} #end
#ifndef (MJHTex38Slope) #declare MJHTex38Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat38) #declare MJHMat38 = material {MJHMissingMat} #end
#ifndef (MJHMat38Slope) #declare MJHMat38Slope = material {MJHMissingMat} #end

// row 40 - Trans_Very_Light_Blue
#ifndef (MJHTex39) #declare MJHTex39 = texture {MJHMissingTex} #end
#ifndef (MJHTex39Slope) #declare MJHTex39Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat39) #declare MJHMat39 = material {MJHMissingMat} #end
#ifndef (MJHMat39Slope) #declare MJHMat39Slope = material {MJHMissingMat} #end

// row 41 - Trans_Black
#ifndef (MJHTex40) #declare MJHTex40 = texture {MJHMissingTex} #end
#ifndef (MJHTex40Slope) #declare MJHTex40Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat40) #declare MJHMat40 = material {MJHMissingMat} #end
#ifndef (MJHMat40Slope) #declare MJHMat40Slope = material {MJHMissingMat} #end

// row 42 - Trans_Medium_Blue
#ifndef (MJHTex41) #declare MJHTex41 = texture {MJHMissingTex} #end
#ifndef (MJHTex41Slope) #declare MJHTex41Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat41) #declare MJHMat41 = material {MJHMissingMat} #end
#ifndef (MJHMat41Slope) #declare MJHMat41Slope = material {MJHMissingMat} #end

// row 43 - Trans_Neon_Green
#ifndef (MJHTex42) #declare MJHTex42 = texture {MJHMissingTex} #end
#ifndef (MJHTex42Slope) #declare MJHTex42Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat42) #declare MJHMat42 = material {MJHMissingMat} #end
#ifndef (MJHMat42Slope) #declare MJHMat42Slope = material {MJHMissingMat} #end

// row 44 - Trans_Light_Blue
#ifndef (MJHTex43) #declare MJHTex43 = texture {MJHMissingTex} #end
#ifndef (MJHTex43Slope) #declare MJHTex43Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat43) #declare MJHMat43 = material {MJHMissingMat} #end
#ifndef (MJHMat43Slope) #declare MJHMat43Slope = material {MJHMissingMat} #end

// row 45 - Trans_Bright_Reddish_Lilac
#ifndef (MJHTex44) #declare MJHTex44 = texture {MJHMissingTex} #end
#ifndef (MJHTex44Slope) #declare MJHTex44Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat44) #declare MJHMat44 = material {MJHMissingMat} #end
#ifndef (MJHMat44Slope) #declare MJHMat44Slope = material {MJHMissingMat} #end

// row 46 - Trans_Pink
#ifndef (MJHTex45) #declare MJHTex45 = texture {MJHMissingTex} #end
#ifndef (MJHTex45Slope) #declare MJHTex45Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat45) #declare MJHMat45 = material {MJHMissingMat} #end
#ifndef (MJHMat45Slope) #declare MJHMat45Slope = material {MJHMissingMat} #end

// row 47 - Trans_Yellow
#ifndef (MJHTex46) #declare MJHTex46 = texture {MJHMissingTex} #end
#ifndef (MJHTex46Slope) #declare MJHTex46Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat46) #declare MJHMat46 = material {MJHMissingMat} #end
#ifndef (MJHMat46Slope) #declare MJHMat46Slope = material {MJHMissingMat} #end

// row 48 - Trans_Clear
#ifndef (MJHTex47) #declare MJHTex47 = texture {MJHMissingTex} #end
#ifndef (MJHTex47Slope) #declare MJHTex47Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat47) #declare MJHMat47 = material {MJHMissingMat} #end
#ifndef (MJHMat47Slope) #declare MJHMat47Slope = material {MJHMissingMat} #end

// row 49 - Trans_Purple
#ifndef (MJHTex52) #declare MJHTex52 = texture {MJHMissingTex} #end
#ifndef (MJHTex52Slope) #declare MJHTex52Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat52) #declare MJHMat52 = material {MJHMissingMat} #end
#ifndef (MJHMat52Slope) #declare MJHMat52Slope = material {MJHMissingMat} #end

// row 50 - Trans_Neon_Yellow
#ifndef (MJHTex54) #declare MJHTex54 = texture {MJHMissingTex} #end
#ifndef (MJHTex54Slope) #declare MJHTex54Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat54) #declare MJHMat54 = material {MJHMissingMat} #end
#ifndef (MJHMat54Slope) #declare MJHMat54Slope = material {MJHMissingMat} #end

// row 51 - Trans_Orange
#ifndef (MJHTex57) #declare MJHTex57 = texture {MJHMissingTex} #end
#ifndef (MJHTex57Slope) #declare MJHTex57Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat57) #declare MJHMat57 = material {MJHMissingMat} #end
#ifndef (MJHMat57Slope) #declare MJHMat57Slope = material {MJHMissingMat} #end

// row 52 - Chrome_Antique_Brass
#ifndef (MJHTex60) #declare MJHTex60 = texture {MJHMissingTex} #end
#ifndef (MJHTex60Slope) #declare MJHTex60Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat60) #declare MJHMat60 = material {MJHMissingMat} #end
#ifndef (MJHMat60Slope) #declare MJHMat60Slope = material {MJHMissingMat} #end

// row 53 - Chrome_Blue
#ifndef (MJHTex61) #declare MJHTex61 = texture {MJHMissingTex} #end
#ifndef (MJHTex61Slope) #declare MJHTex61Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat61) #declare MJHMat61 = material {MJHMissingMat} #end
#ifndef (MJHMat61Slope) #declare MJHMat61Slope = material {MJHMissingMat} #end

// row 54 - Chrome_Green
#ifndef (MJHTex62) #declare MJHTex62 = texture {MJHMissingTex} #end
#ifndef (MJHTex62Slope) #declare MJHTex62Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat62) #declare MJHMat62 = material {MJHMissingMat} #end
#ifndef (MJHMat62Slope) #declare MJHMat62Slope = material {MJHMissingMat} #end

// row 55 - Chrome_Pink
#ifndef (MJHTex63) #declare MJHTex63 = texture {MJHMissingTex} #end
#ifndef (MJHTex63Slope) #declare MJHTex63Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat63) #declare MJHMat63 = material {MJHMissingMat} #end
#ifndef (MJHMat63Slope) #declare MJHMat63Slope = material {MJHMissingMat} #end

// row 56 - Chrome_Black
#ifndef (MJHTex64) #declare MJHTex64 = texture {MJHMissingTex} #end
#ifndef (MJHTex64Slope) #declare MJHTex64Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat64) #declare MJHMat64 = material {MJHMissingMat} #end
#ifndef (MJHMat64Slope) #declare MJHMat64Slope = material {MJHMissingMat} #end

// row 57 - Rubber_Yellow
#ifndef (MJHTex65) #declare MJHTex65 = texture {MJHMissingTex} #end
#ifndef (MJHTex65Slope) #declare MJHTex65Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat65) #declare MJHMat65 = material {MJHMissingMat} #end
#ifndef (MJHMat65Slope) #declare MJHMat65Slope = material {MJHMissingMat} #end

// row 58 - Rubber_Trans_Yellow
#ifndef (MJHTex66) #declare MJHTex66 = texture {MJHMissingTex} #end
#ifndef (MJHTex66Slope) #declare MJHTex66Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat66) #declare MJHMat66 = material {MJHMissingMat} #end
#ifndef (MJHMat66Slope) #declare MJHMat66Slope = material {MJHMissingMat} #end

// row 59 - Rubber_Trans_Clear
#ifndef (MJHTex67) #declare MJHTex67 = texture {MJHMissingTex} #end
#ifndef (MJHTex67Slope) #declare MJHTex67Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat67) #declare MJHMat67 = material {MJHMissingMat} #end
#ifndef (MJHMat67Slope) #declare MJHMat67Slope = material {MJHMissingMat} #end

// row 60 - Very_Light_Orange
#ifndef (MJHTex68) #declare MJHTex68 = texture {MJHMissingTex} #end
#ifndef (MJHTex68Slope) #declare MJHTex68Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat68) #declare MJHMat68 = material {MJHMissingMat} #end
#ifndef (MJHMat68Slope) #declare MJHMat68Slope = material {MJHMissingMat} #end

// row 61 - Bright_Reddish_Lilac
#ifndef (MJHTex69) #declare MJHTex69 = texture {MJHMissingTex} #end
#ifndef (MJHTex69Slope) #declare MJHTex69Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat69) #declare MJHMat69 = material {MJHMissingMat} #end
#ifndef (MJHMat69Slope) #declare MJHMat69Slope = material {MJHMissingMat} #end

// row 62 - Reddish_Brown
#ifndef (MJHTex70) #declare MJHTex70 = texture {MJHMissingTex} #end
#ifndef (MJHTex70Slope) #declare MJHTex70Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat70) #declare MJHMat70 = material {MJHMissingMat} #end
#ifndef (MJHMat70Slope) #declare MJHMat70Slope = material {MJHMissingMat} #end

// row 63 - Light_Bluish_Grey
#ifndef (MJHTex71) #declare MJHTex71 = texture {MJHMissingTex} #end
#ifndef (MJHTex71Slope) #declare MJHTex71Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat71) #declare MJHMat71 = material {MJHMissingMat} #end
#ifndef (MJHMat71Slope) #declare MJHMat71Slope = material {MJHMissingMat} #end

// row 64 - Dark_Bluish_Grey
#ifndef (MJHTex72) #declare MJHTex72 = texture {MJHMissingTex} #end
#ifndef (MJHTex72Slope) #declare MJHTex72Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat72) #declare MJHMat72 = material {MJHMissingMat} #end
#ifndef (MJHMat72Slope) #declare MJHMat72Slope = material {MJHMissingMat} #end

// row 65 - Medium_Blue
#ifndef (MJHTex73) #declare MJHTex73 = texture {MJHMissingTex} #end
#ifndef (MJHTex73Slope) #declare MJHTex73Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat73) #declare MJHMat73 = material {MJHMissingMat} #end
#ifndef (MJHMat73Slope) #declare MJHMat73Slope = material {MJHMissingMat} #end

// row 66 - Medium_Green
#ifndef (MJHTex74) #declare MJHTex74 = texture {MJHMissingTex} #end
#ifndef (MJHTex74Slope) #declare MJHTex74Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat74) #declare MJHMat74 = material {MJHMissingMat} #end
#ifndef (MJHMat74Slope) #declare MJHMat74Slope = material {MJHMissingMat} #end

// row 67 - Speckle_Black_Copper
#ifndef (MJHTex75) #declare MJHTex75 = texture {MJHMissingTex} #end
#ifndef (MJHTex75Slope) #declare MJHTex75Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat75) #declare MJHMat75 = material {MJHMissingMat} #end
#ifndef (MJHMat75Slope) #declare MJHMat75Slope = material {MJHMissingMat} #end

// row 68 - Speckle_Dark_Bluish_Grey_Silver
#ifndef (MJHTex76) #declare MJHTex76 = texture {MJHMissingTex} #end
#ifndef (MJHTex76Slope) #declare MJHTex76Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat76) #declare MJHMat76 = material {MJHMissingMat} #end
#ifndef (MJHMat76Slope) #declare MJHMat76Slope = material {MJHMissingMat} #end

// row 69 - Light_Pink
#ifndef (MJHTex77) #declare MJHTex77 = texture {MJHMissingTex} #end
#ifndef (MJHTex77Slope) #declare MJHTex77Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat77) #declare MJHMat77 = material {MJHMissingMat} #end
#ifndef (MJHMat77Slope) #declare MJHMat77Slope = material {MJHMissingMat} #end

// row 70 - Light_Flesh
#ifndef (MJHTex78) #declare MJHTex78 = texture {MJHMissingTex} #end
#ifndef (MJHTex78Slope) #declare MJHTex78Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat78) #declare MJHMat78 = material {MJHMissingMat} #end
#ifndef (MJHMat78Slope) #declare MJHMat78Slope = material {MJHMissingMat} #end

// row 71 - Milky_White
#ifndef (MJHTex79) #declare MJHTex79 = texture {MJHMissingTex} #end
#ifndef (MJHTex79Slope) #declare MJHTex79Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat79) #declare MJHMat79 = material {MJHMissingMat} #end
#ifndef (MJHMat79Slope) #declare MJHMat79Slope = material {MJHMissingMat} #end

// row 72 - Metallic_Silver
#ifndef (MJHTex80) #declare MJHTex80 = texture {MJHMissingTex} #end
#ifndef (MJHTex80Slope) #declare MJHTex80Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat80) #declare MJHMat80 = material {MJHMissingMat} #end
#ifndef (MJHMat80Slope) #declare MJHMat80Slope = material {MJHMissingMat} #end

// row 73 - Metallic_Green
#ifndef (MJHTex81) #declare MJHTex81 = texture {MJHMissingTex} #end
#ifndef (MJHTex81Slope) #declare MJHTex81Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat81) #declare MJHMat81 = material {MJHMissingMat} #end
#ifndef (MJHMat81Slope) #declare MJHMat81Slope = material {MJHMissingMat} #end

// row 74 - Metallic_Gold
#ifndef (MJHTex82) #declare MJHTex82 = texture {MJHMissingTex} #end
#ifndef (MJHTex82Slope) #declare MJHTex82Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat82) #declare MJHMat82 = material {MJHMissingMat} #end
#ifndef (MJHMat82Slope) #declare MJHMat82Slope = material {MJHMissingMat} #end

// row 75 - Metallic_Black
#ifndef (MJHTex83) #declare MJHTex83 = texture {MJHMissingTex} #end
#ifndef (MJHTex83Slope) #declare MJHTex83Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat83) #declare MJHMat83 = material {MJHMissingMat} #end
#ifndef (MJHMat83Slope) #declare MJHMat83Slope = material {MJHMissingMat} #end

// row 76 - Medium_Dark_Flesh
#ifndef (MJHTex84) #declare MJHTex84 = texture {MJHMissingTex} #end
#ifndef (MJHTex84Slope) #declare MJHTex84Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat84) #declare MJHMat84 = material {MJHMissingMat} #end
#ifndef (MJHMat84Slope) #declare MJHMat84Slope = material {MJHMissingMat} #end

// row 77 - Medium_Lilac
#ifndef (MJHTex85) #declare MJHTex85 = texture {MJHMissingTex} #end
#ifndef (MJHTex85Slope) #declare MJHTex85Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat85) #declare MJHMat85 = material {MJHMissingMat} #end
#ifndef (MJHMat85Slope) #declare MJHMat85Slope = material {MJHMissingMat} #end

// row 78 - Dark_Flesh
#ifndef (MJHTex86) #declare MJHTex86 = texture {MJHMissingTex} #end
#ifndef (MJHTex86Slope) #declare MJHTex86Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat86) #declare MJHMat86 = material {MJHMissingMat} #end
#ifndef (MJHMat86Slope) #declare MJHMat86Slope = material {MJHMissingMat} #end

// row 79 - Metallic_Dark_Grey
#ifndef (MJHTex87) #declare MJHTex87 = texture {MJHMissingTex} #end
#ifndef (MJHTex87Slope) #declare MJHTex87Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat87) #declare MJHMat87 = material {MJHMissingMat} #end
#ifndef (MJHMat87Slope) #declare MJHMat87Slope = material {MJHMissingMat} #end

// row 80 - Blue_Violet
#ifndef (MJHTex89) #declare MJHTex89 = texture {MJHMissingTex} #end
#ifndef (MJHTex89Slope) #declare MJHTex89Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat89) #declare MJHMat89 = material {MJHMissingMat} #end
#ifndef (MJHMat89Slope) #declare MJHMat89Slope = material {MJHMissingMat} #end

// row 81 - Flesh
#ifndef (MJHTex92) #declare MJHTex92 = texture {MJHMissingTex} #end
#ifndef (MJHTex92Slope) #declare MJHTex92Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat92) #declare MJHMat92 = material {MJHMissingMat} #end
#ifndef (MJHMat92Slope) #declare MJHMat92Slope = material {MJHMissingMat} #end

// row 82 - Light_Salmon
#ifndef (MJHTex100) #declare MJHTex100 = texture {MJHMissingTex} #end
#ifndef (MJHTex100Slope) #declare MJHTex100Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat100) #declare MJHMat100 = material {MJHMissingMat} #end
#ifndef (MJHMat100Slope) #declare MJHMat100Slope = material {MJHMissingMat} #end

// row 83 - Violet
#ifndef (MJHTex110) #declare MJHTex110 = texture {MJHMissingTex} #end
#ifndef (MJHTex110Slope) #declare MJHTex110Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat110) #declare MJHMat110 = material {MJHMissingMat} #end
#ifndef (MJHMat110Slope) #declare MJHMat110Slope = material {MJHMissingMat} #end

// row 84 - Medium_Violet
#ifndef (MJHTex112) #declare MJHTex112 = texture {MJHMissingTex} #end
#ifndef (MJHTex112Slope) #declare MJHTex112Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat112) #declare MJHMat112 = material {MJHMissingMat} #end
#ifndef (MJHMat112Slope) #declare MJHMat112Slope = material {MJHMissingMat} #end

// row 85 - Glitter_Trans_Dark_Pink
#ifndef (MJHTex114) #declare MJHTex114 = texture {MJHMissingTex} #end
#ifndef (MJHTex114Slope) #declare MJHTex114Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat114) #declare MJHMat114 = material {MJHMissingMat} #end
#ifndef (MJHMat114Slope) #declare MJHMat114Slope = material {MJHMissingMat} #end

// row 86 - Medium_Lime
#ifndef (MJHTex115) #declare MJHTex115 = texture {MJHMissingTex} #end
#ifndef (MJHTex115Slope) #declare MJHTex115Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat115) #declare MJHMat115 = material {MJHMissingMat} #end
#ifndef (MJHMat115Slope) #declare MJHMat115Slope = material {MJHMissingMat} #end

// row 87 - Glitter_Trans_Clear
#ifndef (MJHTex117) #declare MJHTex117 = texture {MJHMissingTex} #end
#ifndef (MJHTex117Slope) #declare MJHTex117Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat117) #declare MJHMat117 = material {MJHMissingMat} #end
#ifndef (MJHMat117Slope) #declare MJHMat117Slope = material {MJHMissingMat} #end

// row 88 - Aqua
#ifndef (MJHTex118) #declare MJHTex118 = texture {MJHMissingTex} #end
#ifndef (MJHTex118Slope) #declare MJHTex118Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat118) #declare MJHMat118 = material {MJHMissingMat} #end
#ifndef (MJHMat118Slope) #declare MJHMat118Slope = material {MJHMissingMat} #end

// row 89 - Light_Lime
#ifndef (MJHTex120) #declare MJHTex120 = texture {MJHMissingTex} #end
#ifndef (MJHTex120Slope) #declare MJHTex120Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat120) #declare MJHMat120 = material {MJHMissingMat} #end
#ifndef (MJHMat120Slope) #declare MJHMat120Slope = material {MJHMissingMat} #end

// row 90 - Light_Orange
#ifndef (MJHTex125) #declare MJHTex125 = texture {MJHMissingTex} #end
#ifndef (MJHTex125Slope) #declare MJHTex125Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat125) #declare MJHMat125 = material {MJHMissingMat} #end
#ifndef (MJHMat125Slope) #declare MJHMat125Slope = material {MJHMissingMat} #end

// row 91 - Dark_Nougat
#ifndef (MJHTex128) #declare MJHTex128 = texture {MJHMissingTex} #end
#ifndef (MJHTex128Slope) #declare MJHTex128Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat128) #declare MJHMat128 = material {MJHMissingMat} #end
#ifndef (MJHMat128Slope) #declare MJHMat128Slope = material {MJHMissingMat} #end

// row 92 - Glitter_Trans_Purple
#ifndef (MJHTex129) #declare MJHTex129 = texture {MJHMissingTex} #end
#ifndef (MJHTex129Slope) #declare MJHTex129Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat129) #declare MJHMat129 = material {MJHMissingMat} #end
#ifndef (MJHMat129Slope) #declare MJHMat129Slope = material {MJHMissingMat} #end

// row 93 - Speckle_Black_Silver
#ifndef (MJHTex132) #declare MJHTex132 = texture {MJHMissingTex} #end
#ifndef (MJHTex132Slope) #declare MJHTex132Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat132) #declare MJHMat132 = material {MJHMissingMat} #end
#ifndef (MJHMat132Slope) #declare MJHMat132Slope = material {MJHMissingMat} #end

// row 94 - Speckle_Black_Gold
#ifndef (MJHTex133) #declare MJHTex133 = texture {MJHMissingTex} #end
#ifndef (MJHTex133Slope) #declare MJHTex133Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat133) #declare MJHMat133 = material {MJHMissingMat} #end
#ifndef (MJHMat133Slope) #declare MJHMat133Slope = material {MJHMissingMat} #end

// row 95 - Copper
#ifndef (MJHTex134) #declare MJHTex134 = texture {MJHMissingTex} #end
#ifndef (MJHTex134Slope) #declare MJHTex134Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat134) #declare MJHMat134 = material {MJHMissingMat} #end
#ifndef (MJHMat134Slope) #declare MJHMat134Slope = material {MJHMissingMat} #end

// row 96 - Pearl_Light_Grey
#ifndef (MJHTex135) #declare MJHTex135 = texture {MJHMissingTex} #end
#ifndef (MJHTex135Slope) #declare MJHTex135Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat135) #declare MJHMat135 = material {MJHMissingMat} #end
#ifndef (MJHMat135Slope) #declare MJHMat135Slope = material {MJHMissingMat} #end

// row 97 - Metal_Blue
#ifndef (MJHTex137) #declare MJHTex137 = texture {MJHMissingTex} #end
#ifndef (MJHTex137Slope) #declare MJHTex137Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat137) #declare MJHMat137 = material {MJHMissingMat} #end
#ifndef (MJHMat137Slope) #declare MJHMat137Slope = material {MJHMissingMat} #end

// row 98 - Pearl_Light_Gold
#ifndef (MJHTex142) #declare MJHTex142 = texture {MJHMissingTex} #end
#ifndef (MJHTex142Slope) #declare MJHTex142Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat142) #declare MJHMat142 = material {MJHMissingMat} #end
#ifndef (MJHMat142Slope) #declare MJHMat142Slope = material {MJHMissingMat} #end

// row 99 - Pearl_Dark_Grey
#ifndef (MJHTex148) #declare MJHTex148 = texture {MJHMissingTex} #end
#ifndef (MJHTex148Slope) #declare MJHTex148Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat148) #declare MJHMat148 = material {MJHMissingMat} #end
#ifndef (MJHMat148Slope) #declare MJHMat148Slope = material {MJHMissingMat} #end

// row 100 - Pearl_Very_Light_Grey
#ifndef (MJHTex150) #declare MJHTex150 = texture {MJHMissingTex} #end
#ifndef (MJHTex150Slope) #declare MJHTex150Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat150) #declare MJHMat150 = material {MJHMissingMat} #end
#ifndef (MJHMat150Slope) #declare MJHMat150Slope = material {MJHMissingMat} #end

// row 101 - Very_Light_Bluish_Grey
#ifndef (MJHTex151) #declare MJHTex151 = texture {MJHMissingTex} #end
#ifndef (MJHTex151Slope) #declare MJHTex151Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat151) #declare MJHMat151 = material {MJHMissingMat} #end
#ifndef (MJHMat151Slope) #declare MJHMat151Slope = material {MJHMissingMat} #end

// row 102 - Flat_Dark_Gold
#ifndef (MJHTex178) #declare MJHTex178 = texture {MJHMissingTex} #end
#ifndef (MJHTex178Slope) #declare MJHTex178Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat178) #declare MJHMat178 = material {MJHMissingMat} #end
#ifndef (MJHMat178Slope) #declare MJHMat178Slope = material {MJHMissingMat} #end

// row 103 - Flat_Silver
#ifndef (MJHTex179) #declare MJHTex179 = texture {MJHMissingTex} #end
#ifndef (MJHTex179Slope) #declare MJHTex179Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat179) #declare MJHMat179 = material {MJHMissingMat} #end
#ifndef (MJHMat179Slope) #declare MJHMat179Slope = material {MJHMissingMat} #end

// row 104 - Pearl_White
#ifndef (MJHTex183) #declare MJHTex183 = texture {MJHMissingTex} #end
#ifndef (MJHTex183Slope) #declare MJHTex183Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat183) #declare MJHMat183 = material {MJHMissingMat} #end
#ifndef (MJHMat183Slope) #declare MJHMat183Slope = material {MJHMissingMat} #end

// row 105 - Metallic_Bright_Red
#ifndef (MJHTex184) #declare MJHTex184 = texture {MJHMissingTex} #end
#ifndef (MJHTex184Slope) #declare MJHTex184Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat184) #declare MJHMat184 = material {MJHMissingMat} #end
#ifndef (MJHMat184Slope) #declare MJHMat184Slope = material {MJHMissingMat} #end

// row 106 - Metallic_Dark_Green
#ifndef (MJHTex186) #declare MJHTex186 = texture {MJHMissingTex} #end
#ifndef (MJHTex186Slope) #declare MJHTex186Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat186) #declare MJHMat186 = material {MJHMissingMat} #end
#ifndef (MJHMat186Slope) #declare MJHMat186Slope = material {MJHMissingMat} #end

// row 107 - Reddish_Gold
#ifndef (MJHTex189) #declare MJHTex189 = texture {MJHMissingTex} #end
#ifndef (MJHTex189Slope) #declare MJHTex189Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat189) #declare MJHMat189 = material {MJHMissingMat} #end
#ifndef (MJHMat189Slope) #declare MJHMat189Slope = material {MJHMissingMat} #end

// row 108 - Bright_Light_Orange
#ifndef (MJHTex191) #declare MJHTex191 = texture {MJHMissingTex} #end
#ifndef (MJHTex191Slope) #declare MJHTex191Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat191) #declare MJHMat191 = material {MJHMissingMat} #end
#ifndef (MJHMat191Slope) #declare MJHMat191Slope = material {MJHMissingMat} #end

// row 109 - Bright_Light_Blue
#ifndef (MJHTex212) #declare MJHTex212 = texture {MJHMissingTex} #end
#ifndef (MJHTex212Slope) #declare MJHTex212Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat212) #declare MJHMat212 = material {MJHMissingMat} #end
#ifndef (MJHMat212Slope) #declare MJHMat212Slope = material {MJHMissingMat} #end

// row 110 - Rust
#ifndef (MJHTex216) #declare MJHTex216 = texture {MJHMissingTex} #end
#ifndef (MJHTex216Slope) #declare MJHTex216Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat216) #declare MJHMat216 = material {MJHMissingMat} #end
#ifndef (MJHMat216Slope) #declare MJHMat216Slope = material {MJHMissingMat} #end

// row 111 - Reddish_Lilac
#ifndef (MJHTex218) #declare MJHTex218 = texture {MJHMissingTex} #end
#ifndef (MJHTex218Slope) #declare MJHTex218Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat218) #declare MJHMat218 = material {MJHMissingMat} #end
#ifndef (MJHMat218Slope) #declare MJHMat218Slope = material {MJHMissingMat} #end

// row 112 - Lilac
#ifndef (MJHTex219) #declare MJHTex219 = texture {MJHMissingTex} #end
#ifndef (MJHTex219Slope) #declare MJHTex219Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat219) #declare MJHMat219 = material {MJHMissingMat} #end
#ifndef (MJHMat219Slope) #declare MJHMat219Slope = material {MJHMissingMat} #end

// row 113 - Bright_Light_Yellow
#ifndef (MJHTex226) #declare MJHTex226 = texture {MJHMissingTex} #end
#ifndef (MJHTex226Slope) #declare MJHTex226Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat226) #declare MJHMat226 = material {MJHMissingMat} #end
#ifndef (MJHMat226Slope) #declare MJHMat226Slope = material {MJHMissingMat} #end

// row 114 - Trans_Bright_Light_Orange
#ifndef (MJHTex231) #declare MJHTex231 = texture {MJHMissingTex} #end
#ifndef (MJHTex231Slope) #declare MJHTex231Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat231) #declare MJHMat231 = material {MJHMissingMat} #end
#ifndef (MJHMat231Slope) #declare MJHMat231Slope = material {MJHMissingMat} #end

// row 115 - Sky_Blue
#ifndef (MJHTex232) #declare MJHTex232 = texture {MJHMissingTex} #end
#ifndef (MJHTex232Slope) #declare MJHTex232Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat232) #declare MJHMat232 = material {MJHMissingMat} #end
#ifndef (MJHMat232Slope) #declare MJHMat232Slope = material {MJHMissingMat} #end

// row 116 - Trans_Fire_Yellow
#ifndef (MJHTex234) #declare MJHTex234 = texture {MJHMissingTex} #end
#ifndef (MJHTex234Slope) #declare MJHTex234Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat234) #declare MJHMat234 = material {MJHMissingMat} #end
#ifndef (MJHMat234Slope) #declare MJHMat234Slope = material {MJHMissingMat} #end

// row 117 - Rubber_Black
#ifndef (MJHTex256) #declare MJHTex256 = texture {MJHMissingTex} #end
#ifndef (MJHTex256Slope) #declare MJHTex256Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat256) #declare MJHMat256 = material {MJHMissingMat} #end
#ifndef (MJHMat256Slope) #declare MJHMat256Slope = material {MJHMissingMat} #end

// row 118 - Dark_Blue
#ifndef (MJHTex272) #declare MJHTex272 = texture {MJHMissingTex} #end
#ifndef (MJHTex272Slope) #declare MJHTex272Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat272) #declare MJHMat272 = material {MJHMissingMat} #end
#ifndef (MJHMat272Slope) #declare MJHMat272Slope = material {MJHMissingMat} #end

// row 119 - Rubber_Blue
#ifndef (MJHTex273) #declare MJHTex273 = texture {MJHMissingTex} #end
#ifndef (MJHTex273Slope) #declare MJHTex273Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat273) #declare MJHMat273 = material {MJHMissingMat} #end
#ifndef (MJHMat273Slope) #declare MJHMat273Slope = material {MJHMissingMat} #end

// row 120 - Trans_Reddish_Lilac
#ifndef (MJHTex284) #declare MJHTex284 = texture {MJHMissingTex} #end
#ifndef (MJHTex284Slope) #declare MJHTex284Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat284) #declare MJHMat284 = material {MJHMissingMat} #end
#ifndef (MJHMat284Slope) #declare MJHMat284Slope = material {MJHMissingMat} #end

// row 121 - Trans_Light_Green
#ifndef (MJHTex285) #declare MJHTex285 = texture {MJHMissingTex} #end
#ifndef (MJHTex285Slope) #declare MJHTex285Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat285) #declare MJHMat285 = material {MJHMissingMat} #end
#ifndef (MJHMat285Slope) #declare MJHMat285Slope = material {MJHMissingMat} #end

// row 122 - Dark_Green
#ifndef (MJHTex288) #declare MJHTex288 = texture {MJHMissingTex} #end
#ifndef (MJHTex288Slope) #declare MJHTex288Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat288) #declare MJHMat288 = material {MJHMissingMat} #end
#ifndef (MJHMat288Slope) #declare MJHMat288Slope = material {MJHMissingMat} #end

// row 123 - Trans_Light_Blue_Violet
#ifndef (MJHTex293) #declare MJHTex293 = texture {MJHMissingTex} #end
#ifndef (MJHTex293Slope) #declare MJHTex293Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat293) #declare MJHMat293 = material {MJHMissingMat} #end
#ifndef (MJHMat293Slope) #declare MJHMat293Slope = material {MJHMissingMat} #end

// row 124 - Glow_In_Dark_Trans
#ifndef (MJHTex294) #declare MJHTex294 = texture {MJHMissingTex} #end
#ifndef (MJHTex294Slope) #declare MJHTex294Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat294) #declare MJHMat294 = material {MJHMissingMat} #end
#ifndef (MJHMat294Slope) #declare MJHMat294Slope = material {MJHMissingMat} #end

// row 125 - Flamingo_Pink
#ifndef (MJHTex295) #declare MJHTex295 = texture {MJHMissingTex} #end
#ifndef (MJHTex295Slope) #declare MJHTex295Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat295) #declare MJHMat295 = material {MJHMissingMat} #end
#ifndef (MJHMat295Slope) #declare MJHMat295Slope = material {MJHMissingMat} #end

// row 126 - Pearl_Gold
#ifndef (MJHTex297) #declare MJHTex297 = texture {MJHMissingTex} #end
#ifndef (MJHTex297Slope) #declare MJHTex297Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat297) #declare MJHMat297 = material {MJHMissingMat} #end
#ifndef (MJHMat297Slope) #declare MJHMat297Slope = material {MJHMissingMat} #end

// row 127 - Metallic_Copper
#ifndef (MJHTex300) #declare MJHTex300 = texture {MJHMissingTex} #end
#ifndef (MJHTex300Slope) #declare MJHTex300Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat300) #declare MJHMat300 = material {MJHMissingMat} #end
#ifndef (MJHMat300Slope) #declare MJHMat300Slope = material {MJHMissingMat} #end

// row 128 - Glitter_Trans_Light_Blue
#ifndef (MJHTex302) #declare MJHTex302 = texture {MJHMissingTex} #end
#ifndef (MJHTex302Slope) #declare MJHTex302Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat302) #declare MJHMat302 = material {MJHMissingMat} #end
#ifndef (MJHMat302Slope) #declare MJHMat302Slope = material {MJHMissingMat} #end

// row 129 - Dark_Brown
#ifndef (MJHTex308) #declare MJHTex308 = texture {MJHMissingTex} #end
#ifndef (MJHTex308Slope) #declare MJHTex308Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat308) #declare MJHMat308 = material {MJHMissingMat} #end
#ifndef (MJHMat308Slope) #declare MJHMat308Slope = material {MJHMissingMat} #end

// row 130 - Maersk_Blue
#ifndef (MJHTex313) #declare MJHTex313 = texture {MJHMissingTex} #end
#ifndef (MJHTex313Slope) #declare MJHTex313Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat313) #declare MJHMat313 = material {MJHMissingMat} #end
#ifndef (MJHMat313Slope) #declare MJHMat313Slope = material {MJHMissingMat} #end

// row 131 - Dark_Red
#ifndef (MJHTex320) #declare MJHTex320 = texture {MJHMissingTex} #end
#ifndef (MJHTex320Slope) #declare MJHTex320Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat320) #declare MJHMat320 = material {MJHMissingMat} #end
#ifndef (MJHMat320Slope) #declare MJHMat320Slope = material {MJHMissingMat} #end

// row 132 - Dark_Azure
#ifndef (MJHTex321) #declare MJHTex321 = texture {MJHMissingTex} #end
#ifndef (MJHTex321Slope) #declare MJHTex321Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat321) #declare MJHMat321 = material {MJHMissingMat} #end
#ifndef (MJHMat321Slope) #declare MJHMat321Slope = material {MJHMissingMat} #end

// row 133 - Medium_Azure
#ifndef (MJHTex322) #declare MJHTex322 = texture {MJHMissingTex} #end
#ifndef (MJHTex322Slope) #declare MJHTex322Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat322) #declare MJHMat322 = material {MJHMissingMat} #end
#ifndef (MJHMat322Slope) #declare MJHMat322Slope = material {MJHMissingMat} #end

// row 134 - Light_Aqua
#ifndef (MJHTex323) #declare MJHTex323 = texture {MJHMissingTex} #end
#ifndef (MJHTex323Slope) #declare MJHTex323Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat323) #declare MJHMat323 = material {MJHMissingMat} #end
#ifndef (MJHMat323Slope) #declare MJHMat323Slope = material {MJHMissingMat} #end

// row 135 - Rubber_Red
#ifndef (MJHTex324) #declare MJHTex324 = texture {MJHMissingTex} #end
#ifndef (MJHTex324Slope) #declare MJHTex324Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat324) #declare MJHMat324 = material {MJHMissingMat} #end
#ifndef (MJHMat324Slope) #declare MJHMat324Slope = material {MJHMissingMat} #end

// row 136 - Yellowish_Green
#ifndef (MJHTex326) #declare MJHTex326 = texture {MJHMissingTex} #end
#ifndef (MJHTex326Slope) #declare MJHTex326Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat326) #declare MJHMat326 = material {MJHMissingMat} #end
#ifndef (MJHMat326Slope) #declare MJHMat326Slope = material {MJHMissingMat} #end

// row 137 - Glow_In_Dark_White
#ifndef (MJHTex329) #declare MJHTex329 = texture {MJHMissingTex} #end
#ifndef (MJHTex329Slope) #declare MJHTex329Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat329) #declare MJHMat329 = material {MJHMissingMat} #end
#ifndef (MJHMat329Slope) #declare MJHMat329Slope = material {MJHMissingMat} #end

// row 138 - Olive_Green
#ifndef (MJHTex330) #declare MJHTex330 = texture {MJHMissingTex} #end
#ifndef (MJHTex330Slope) #declare MJHTex330Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat330) #declare MJHMat330 = material {MJHMissingMat} #end
#ifndef (MJHMat330Slope) #declare MJHMat330Slope = material {MJHMissingMat} #end

// row 139 - Chrome_Gold
#ifndef (MJHTex334) #declare MJHTex334 = texture {MJHMissingTex} #end
#ifndef (MJHTex334Slope) #declare MJHTex334Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat334) #declare MJHMat334 = material {MJHMissingMat} #end
#ifndef (MJHMat334Slope) #declare MJHMat334Slope = material {MJHMissingMat} #end

// row 140 - Sand_Red
#ifndef (MJHTex335) #declare MJHTex335 = texture {MJHMissingTex} #end
#ifndef (MJHTex335Slope) #declare MJHTex335Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat335) #declare MJHMat335 = material {MJHMissingMat} #end
#ifndef (MJHMat335Slope) #declare MJHMat335Slope = material {MJHMissingMat} #end

// row 141 - Glitter_Trans_Neon_Green
#ifndef (MJHTex339) #declare MJHTex339 = texture {MJHMissingTex} #end
#ifndef (MJHTex339Slope) #declare MJHTex339Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat339) #declare MJHMat339 = material {MJHMissingMat} #end
#ifndef (MJHMat339Slope) #declare MJHMat339Slope = material {MJHMissingMat} #end

// row 142 - Rubber_Orange
#ifndef (MJHTex350) #declare MJHTex350 = texture {MJHMissingTex} #end
#ifndef (MJHTex350Slope) #declare MJHTex350Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat350) #declare MJHMat350 = material {MJHMissingMat} #end
#ifndef (MJHMat350Slope) #declare MJHMat350Slope = material {MJHMissingMat} #end

// row 143 - Medium_Dark_Pink
#ifndef (MJHTex351) #declare MJHTex351 = texture {MJHMissingTex} #end
#ifndef (MJHTex351Slope) #declare MJHTex351Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat351) #declare MJHMat351 = material {MJHMissingMat} #end
#ifndef (MJHMat351Slope) #declare MJHMat351Slope = material {MJHMissingMat} #end

// row 145 - Earth_Orange
#ifndef (MJHTex366) #declare MJHTex366 = texture {MJHMissingTex} #end
#ifndef (MJHTex366Slope) #declare MJHTex366Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat366) #declare MJHMat366 = material {MJHMissingMat} #end
#ifndef (MJHMat366Slope) #declare MJHMat366Slope = material {MJHMissingMat} #end

// row 146 - Sand_Purple
#ifndef (MJHTex373) #declare MJHTex373 = texture {MJHMissingTex} #end
#ifndef (MJHTex373Slope) #declare MJHTex373Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat373) #declare MJHMat373 = material {MJHMissingMat} #end
#ifndef (MJHMat373Slope) #declare MJHMat373Slope = material {MJHMissingMat} #end

// row 147 - Rubber_Light_Grey
#ifndef (MJHTex375) #declare MJHTex375 = texture {MJHMissingTex} #end
#ifndef (MJHTex375Slope) #declare MJHTex375Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat375) #declare MJHMat375 = material {MJHMissingMat} #end
#ifndef (MJHMat375Slope) #declare MJHMat375Slope = material {MJHMissingMat} #end

// row 148 - Sand_Green
#ifndef (MJHTex378) #declare MJHTex378 = texture {MJHMissingTex} #end
#ifndef (MJHTex378Slope) #declare MJHTex378Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat378) #declare MJHMat378 = material {MJHMissingMat} #end
#ifndef (MJHMat378Slope) #declare MJHMat378Slope = material {MJHMissingMat} #end

// row 149 - Sand_Blue
#ifndef (MJHTex379) #declare MJHTex379 = texture {MJHMissingTex} #end
#ifndef (MJHTex379Slope) #declare MJHTex379Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat379) #declare MJHMat379 = material {MJHMissingMat} #end
#ifndef (MJHMat379Slope) #declare MJHMat379Slope = material {MJHMissingMat} #end

// row 150 - Chrome_Silver
#ifndef (MJHTex383) #declare MJHTex383 = texture {MJHMissingTex} #end
#ifndef (MJHTex383Slope) #declare MJHTex383Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat383) #declare MJHMat383 = material {MJHMissingMat} #end
#ifndef (MJHMat383Slope) #declare MJHMat383Slope = material {MJHMissingMat} #end

// row 151 - Rubber_Dark_Blue
#ifndef (MJHTex406) #declare MJHTex406 = texture {MJHMissingTex} #end
#ifndef (MJHTex406Slope) #declare MJHTex406Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat406) #declare MJHMat406 = material {MJHMissingMat} #end
#ifndef (MJHMat406Slope) #declare MJHMat406Slope = material {MJHMissingMat} #end

// row 152 - Rubber_Purple
#ifndef (MJHTex449) #declare MJHTex449 = texture {MJHMissingTex} #end
#ifndef (MJHTex449Slope) #declare MJHTex449Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat449) #declare MJHMat449 = material {MJHMissingMat} #end
#ifndef (MJHMat449Slope) #declare MJHMat449Slope = material {MJHMissingMat} #end

// row 153 - Fabuland_Brown
#ifndef (MJHTex450) #declare MJHTex450 = texture {MJHMissingTex} #end
#ifndef (MJHTex450Slope) #declare MJHTex450Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat450) #declare MJHMat450 = material {MJHMissingMat} #end
#ifndef (MJHMat450Slope) #declare MJHMat450Slope = material {MJHMissingMat} #end

// row 154 - Medium_Orange
#ifndef (MJHTex462) #declare MJHTex462 = texture {MJHMissingTex} #end
#ifndef (MJHTex462Slope) #declare MJHTex462Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat462) #declare MJHMat462 = material {MJHMissingMat} #end
#ifndef (MJHMat462Slope) #declare MJHMat462Slope = material {MJHMissingMat} #end

// row 155 - Dark_Orange
#ifndef (MJHTex484) #declare MJHTex484 = texture {MJHMissingTex} #end
#ifndef (MJHTex484Slope) #declare MJHTex484Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat484) #declare MJHMat484 = material {MJHMissingMat} #end
#ifndef (MJHMat484Slope) #declare MJHMat484Slope = material {MJHMissingMat} #end

// row 156 - Rubber_Lime
#ifndef (MJHTex490) #declare MJHTex490 = texture {MJHMissingTex} #end
#ifndef (MJHTex490Slope) #declare MJHTex490Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat490) #declare MJHMat490 = material {MJHMissingMat} #end
#ifndef (MJHMat490Slope) #declare MJHMat490Slope = material {MJHMissingMat} #end

// row 157 - Magnet
#ifndef (MJHTex493) #declare MJHTex493 = texture {MJHMissingTex} #end
#ifndef (MJHTex493Slope) #declare MJHTex493Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat493) #declare MJHMat493 = material {MJHMissingMat} #end
#ifndef (MJHMat493Slope) #declare MJHMat493Slope = material {MJHMissingMat} #end

// row 158 - Electric_Contact_Alloy
#ifndef (MJHTex494) #declare MJHTex494 = texture {MJHMissingTex} #end
#ifndef (MJHTex494Slope) #declare MJHTex494Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat494) #declare MJHMat494 = material {MJHMissingMat} #end
#ifndef (MJHMat494Slope) #declare MJHMat494Slope = material {MJHMissingMat} #end

// row 159 - Electric_Contact_Copper
#ifndef (MJHTex495) #declare MJHTex495 = texture {MJHMissingTex} #end
#ifndef (MJHTex495Slope) #declare MJHTex495Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat495) #declare MJHMat495 = material {MJHMissingMat} #end
#ifndef (MJHMat495Slope) #declare MJHMat495Slope = material {MJHMissingMat} #end

// row 160 - Rubber_Light_Bluish_Grey
#ifndef (MJHTex496) #declare MJHTex496 = texture {MJHMissingTex} #end
#ifndef (MJHTex496Slope) #declare MJHTex496Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat496) #declare MJHMat496 = material {MJHMissingMat} #end
#ifndef (MJHMat496Slope) #declare MJHMat496Slope = material {MJHMissingMat} #end

// row 161 - Very_Light_Grey
#ifndef (MJHTex503) #declare MJHTex503 = texture {MJHMissingTex} #end
#ifndef (MJHTex503Slope) #declare MJHTex503Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat503) #declare MJHMat503 = material {MJHMissingMat} #end
#ifndef (MJHMat503Slope) #declare MJHMat503Slope = material {MJHMissingMat} #end

// row 162 - Rubber_Flat_Silver
#ifndef (MJHTex504) #declare MJHTex504 = texture {MJHMissingTex} #end
#ifndef (MJHTex504Slope) #declare MJHTex504Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat504) #declare MJHMat504 = material {MJHMissingMat} #end
#ifndef (MJHMat504Slope) #declare MJHMat504Slope = material {MJHMissingMat} #end

// row 166 - Rubber_White
#ifndef (MJHTex511) #declare MJHTex511 = texture {MJHMissingTex} #end
#ifndef (MJHTex511Slope) #declare MJHTex511Slope = texture {MJHMissingTex} #end
#ifndef (MJHMat511) #declare MJHMat511 = material {MJHMissingMat} #end
#ifndef (MJHMat511Slope) #declare MJHMat511Slope = material {MJHMissingMat} #end
